// GENERATED by tools/codegen.ts — do not edit
import AppKit
import Foundation
import CNd  // libnd C surface (nd_plugin_view_* for the <nativeView> arms)

// JSON-string -> [String: Any] (M6b-D1: JSONSerialization, not a typed decoder).
func parseProps(_ json: String) -> [String: Any] {
    guard let data = json.data(using: .utf8),
          let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
    else { return [:] }
    return obj
}
func propStr(_ p: [String: Any], _ k: String) -> String? { p[k] as? String }
func propInt(_ p: [String: Any], _ k: String) -> Int? { (p[k] as? NSNumber)?.intValue }
func propDouble(_ p: [String: Any], _ k: String) -> Double? { (p[k] as? NSNumber)?.doubleValue }
func propBool(_ p: [String: Any], _ k: String) -> Bool? { (p[k] as? NSNumber)?.boolValue }
func propArray(_ p: [String: Any], _ k: String) -> [String]? { (p[k] as? [Any])?.compactMap { $0 as? String } }
func propObjArray(_ p: [String: Any], _ k: String) -> [[String: Any]]? { (p[k] as? [Any])?.compactMap { $0 as? [String: Any] } }

// Every container view class is flipped (top-left y-down) — GLOBAL CONSTRAINT.
final class FlippedView: NSView { override var isFlipped: Bool { true } }

// SplitView's `sidebarWidth`/`collapsed` (create-time props on the
// NSSplitView itself) are read again when the sidebar child later appends
// and becomes an NSSplitViewItem — stashed here since the item doesn't exist
// yet at create time.
nonisolated(unsafe) private var splitViewSidebarFraction: [ObjectIdentifier: Double] = [:]
nonisolated(unsafe) private var splitViewCollapsed: [ObjectIdentifier: Bool] = [:]
// M13: three-pane SplitView's `listWidth` (create-time prop for the
// contentList NSSplitViewItem) — same stash-until-append mechanism as
// `splitViewSidebarFraction`, keyed by the same outer splitView identity.
nonisolated(unsafe) private var splitViewListFraction: [ObjectIdentifier: Double] = [:]

func ndCreate(_ kind: String, _ propsJson: String) -> NSView? {
    let props = parseProps(propsJson)
    if kind == "Window" {
        let content = FlippedView()
        let winW = propInt(props, "defaultWidth") ?? 480
        let winH = propInt(props, "defaultHeight") ?? 320
        let win = NSWindow(contentRect: NSRect(x: 0, y: 0, width: CGFloat(winW), height: CGFloat(winH)), styleMask: [.titled, .closable, .miniaturizable, .resizable, .fullSizeContentView], backing: .buffered, defer: false)
        if let t = propStr(props, "title") { win.title = t }
        win.titlebarAppearsTransparent = true
        // The core (not AppKit) owns window lifetime: close() must never
        // dealloc the window while the retained tree still references it.
        win.isReleasedWhenClosed = false
        win.contentView = content
        gWindow = win
        let manager = NDToolbarManager()
        ndWindowToolbarManager = manager
        ndEnsureMenuManager() // M13: install the default NSApp.mainMenu (App/File/Edit/View/Window/Help)
        // Tab-aware presentation (WindowTabs.swift): a `tabGroup` window
        // joins its group's native tab bar via addTabbedWindow; a plain
        // window centers and orders front as before.
        ndWindowTabsPresent(win, tabGroup: propStr(props, "tabGroup"))
        return content
    } else if kind == "Box" {
        let stack = NSStackView()
        let vertical = (propStr(props, "orientation") ?? "vertical") == "vertical"
        stack.orientation = vertical ? .vertical : .horizontal
        stack.spacing = CGFloat(propInt(props, "spacing") ?? 0)
        stack.alignment = vertical ? .leading : .centerY
        stack.distribution = .gravityAreas
        return stack
    } else if kind == "Label" {
        let text = propStr(props, "text") ?? ""
        let label = NDTextField(labelWithString: text)
        if propBool(props, "ellipsize") ?? false {
            // Truncate instead of forcing the min width to the full text.
            label.lineBreakMode = .byTruncatingTail
            label.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
        }
        return label
    } else if kind == "Button" {
        let lbl = propStr(props, "label") ?? "Button"
        let b = NDButton(title: lbl, target: nil, action: nil)
        b.setButtonType(.momentaryPushIn); b.bezelStyle = .rounded
        if let icon = propStr(props, "iconName") {
            ndApplyButtonIcon(b, iconName: icon, label: lbl)  // NDShell/Icons.swift (hand-written)
        }
        switch propStr(props, "labelAlign") ?? "center" {
        case "start": b.alignment = .left
        case "end": b.alignment = .right
        default: break
        }
        if propBool(props, "ellipsize") ?? false {
            b.lineBreakMode = .byTruncatingTail
            b.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
        }
        if let tt = propStr(props, "tooltip") { b.toolTip = tt }
        return b
    } else if kind == "TextInput" {
        let field = NDTextField(string: propStr(props, "text") ?? "")
        if let ph = propStr(props, "placeholder") { field.placeholderString = ph }
        if let e = propBool(props, "editable") { field.isEditable = e }
        return field
    } else if kind == "TextArea" {
        let scroll = NSScrollView()
        scroll.hasVerticalScroller = true
        let textView = NSTextView()
        textView.string = propStr(props, "text") ?? ""
        scroll.documentView = textView
        let minH = propInt(props, "minContentHeight") ?? 120
        if minH > 0 {
            scroll.frame.size.height = CGFloat(minH)
            let floor_ = scroll.heightAnchor.constraint(greaterThanOrEqualToConstant: CGFloat(minH))
            floor_.priority = NSLayoutConstraint.Priority(999)
            floor_.isActive = true
        }
        return scroll
    } else if kind == "Checkbox" {
        let cb = NSButton(checkboxWithTitle: propStr(props, "label") ?? "", target: nil, action: nil)
        cb.state = (propBool(props, "checked") ?? false) ? .on : .off
        return cb
    } else if kind == "Radio" {
        let r = NSButton(radioButtonWithTitle: propStr(props, "label") ?? "", target: nil, action: nil)
        r.state = (propBool(props, "checked") ?? false) ? .on : .off
        if let g = propStr(props, "group") {
            radioGroupIdentifier[ObjectIdentifier(r)] = g   // mutual exclusion wired in connectEvents (T4)
        } else {
            FileHandle.standardError.write("ND_WARN Radio without group prop\n".data(using: .utf8)!)
        }
        return r
    } else if kind == "Select" {
        let pop = NSPopUpButton(frame: .zero, pullsDown: false)
        if let opts = propArray(props, "options") { pop.addItems(withTitles: opts) }
        let idx = propInt(props, "selectedIndex") ?? 0
        if idx >= 0 && idx < pop.numberOfItems { pop.selectItem(at: idx) }
        return pop
    } else if kind == "Slider" {
        let min = propDouble(props, "min") ?? 0
        let max = propDouble(props, "max") ?? 100
        let value = propDouble(props, "value") ?? 0
        let slider = NSSlider(value: value, minValue: min, maxValue: max, target: nil, action: nil)
        slider.isVertical = (propStr(props, "orientation") ?? "horizontal") == "vertical"
        return slider
    } else if kind == "ProgressBar" {
        let pb = NSProgressIndicator()
        pb.style = .bar
        pb.isIndeterminate = false
        pb.minValue = 0; pb.maxValue = 100
        pb.doubleValue = (propDouble(props, "fraction") ?? 0) * 100
        return pb
    } else if kind == "Image" {
        let iv = NSImageView()
        if let p = propStr(props, "path") {
            iv.image = NSImage(contentsOfFile: p)
        } else if let n = propStr(props, "iconName") {
            iv.image = ndResolveSymbolImage(n)  // NDShell/Icons.swift (hand-written)
        }
        return iv
    } else if kind == "ScrollView" {
        let sv = NSScrollView()
        sv.hasVerticalScroller = true
        if propStr(props, "hscroll") == "never" { sv.hasHorizontalScroller = false }
        sv.drawsBackground = false
        let doc = FlippedView()
        sv.documentView = doc
        doc.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            doc.leadingAnchor.constraint(equalTo: sv.contentView.leadingAnchor),
            doc.trailingAnchor.constraint(equalTo: sv.contentView.trailingAnchor),
            doc.topAnchor.constraint(equalTo: sv.contentView.topAnchor),
            doc.widthAnchor.constraint(equalTo: sv.contentView.widthAnchor),
        ])
        let minH = propInt(props, "minContentHeight") ?? 0
        if minH > 0 {
            sv.frame.size.height = CGFloat(minH)
            let floor_ = sv.heightAnchor.constraint(greaterThanOrEqualToConstant: CGFloat(minH))
            floor_.priority = NSLayoutConstraint.Priority(999)
            floor_.isActive = true
        }
        return sv
    } else if kind == "Separator" {
        let sep = NSBox()
        sep.boxType = .separator
        let vertical = (propStr(props, "orientation") ?? "horizontal") == "vertical"
        sep.frame = vertical ? NSRect(x: 0, y: 0, width: 1, height: 24) : NSRect(x: 0, y: 0, width: 24, height: 1)
        return sep
    } else if kind == "Spinner" {
        let sp = NSProgressIndicator()
        sp.style = .spinning
        sp.isIndeterminate = true
        if propBool(props, "spinning") ?? true { sp.startAnimation(nil) } else { sp.stopAnimation(nil) }
        return sp
    } else if kind == "TabView" {
        // selectedIndex is ignored at create: pages attach afterwards (mirrors genZigCreateBody).
        let tabs = NSTabView()
        return tabs
    } else if kind == "Grid" {
        let grid = NSGridView(numberOfColumns: 1, rows: 0)
        return grid
    } else if kind == "ListView" {
        return makeListView(props)  // NSScrollView+NSTableView, view-based recycling (M6b-D2)
    } else if kind == "WebView" {
        return NDWebView(url: propStr(props, "url"))  // WKWebView subclass (M14, NDShell/NDWebView.swift)
    } else if kind == "NativeView" {
        let viewKind = propStr(props, "viewKind") ?? ""
        let propsJson = propStr(props, "props") ?? "{}"
        if let p = nd_plugin_view_create(viewKind, propsJson) {
            return unsafeBitCast(p, to: NSView.self)
        }
        return NSView()
    } else if kind == "SplitView" {
        let controller = NSSplitViewController()
        controller.splitView.isVertical = true
        controller.splitView.dividerStyle = .thin
        ndSplitControllers[ObjectIdentifier(controller.splitView)] = controller
        if let w = propDouble(props, "sidebarWidth"), w > 0 {
            splitViewSidebarFraction[ObjectIdentifier(controller.splitView)] = w
        }
        if let lw = propDouble(props, "listWidth"), lw > 0 {
            splitViewListFraction[ObjectIdentifier(controller.splitView)] = lw
        }
        if propBool(props, "collapsed") ?? false {
            splitViewCollapsed[ObjectIdentifier(controller.splitView)] = true
        }
        return controller.splitView
    } else if kind == "HeaderBar" {
        let bar = NDHeaderBarView()
        bar.ndTitle = propStr(props, "title") ?? ""
        ndHeaderBarApplyNav(bar, canGoBack: propBool(props, "canGoBack"), canGoForward: propBool(props, "canGoForward"))
        return bar
    } else if kind == "ToolbarView" {
        return NDToolbarPaneView()
    } else if kind == "SearchInput" {
        let search = NDSearchField(string: propStr(props, "text") ?? "")
        if let ph = propStr(props, "placeholder") { search.placeholderString = ph }
        return search
    } else if kind == "SourceList" {
        return makeSourceList(props)  // NSScrollView+NSTableView(.sourceList) (M11 Wave 2, NDGen/SourceList.swift)
    } else if kind == "SourceTree" {
        return makeSourceTree(props)  // NSOutlineView .sourceList in NSScrollView (NDShell/SourceTrees.swift)
    } else if kind == "Menubar" {
        return ndMenubarCreate(propBool(props, "defaults") ?? true)
    } else if kind == "Menu" {
        return ndMenuCreate(propStr(props, "label") ?? "")
    } else if kind == "MenuItem" {
        return ndMenuItemCreate(props)
    } else if kind == "SettingsGroup" {
        let group = NDSettingsGroupView()
        group.spacing = CGFloat(propInt(props, "spacing") ?? 0)
        return group
    } else if kind == "Switch" {
        let toggle = NSSwitch()
        toggle.state = (propBool(props, "checked") ?? false) ? .on : .off
        return toggle
    } else if kind == "ToggleButton" {
        let lbl = propStr(props, "label") ?? ""
        let b = NDButton(title: lbl, target: nil, action: nil)
        b.setButtonType(.pushOnPushOff); b.bezelStyle = .rounded
        if let icon = propStr(props, "iconName") {
            ndApplyButtonIcon(b, iconName: icon, label: lbl)  // NDShell/Icons.swift (hand-written)
        }
        b.state = (propBool(props, "active") ?? false) ? .on : .off
        return b
    } else if kind == "SegmentedControl" {
        let seg = NSSegmentedControl(labels: propArray(props, "options") ?? [], trackingMode: .selectOne, target: nil, action: nil)
        let idx = propInt(props, "selectedIndex") ?? 0
        if idx >= 0 && idx < seg.segmentCount { seg.selectedSegment = idx }
        return seg
    } else if kind == "NumberInput" {
        return makeNumberInput(props)  // NSTextField+NSStepper composite (M15, NDShell/NumberInput.swift)
    } else if kind == "LinkButton" {
        return makeLinkButton(props)  // SwiftUI .buttonStyle(.link) in NSHostingView (M15, NDShell/LinkButtons.swift)
    } else if kind == "LevelIndicator" {
        let li = NSLevelIndicator()
        li.levelIndicatorStyle = (propBool(props, "discrete") ?? false) ? .discreteCapacity : .continuousCapacity
        li.minValue = propDouble(props, "min") ?? 0
        li.maxValue = propDouble(props, "max") ?? 1
        li.warningValue = propDouble(props, "warningValue") ?? (li.maxValue + 1)
        li.criticalValue = propDouble(props, "criticalValue") ?? (li.maxValue + 1)
        li.doubleValue = propDouble(props, "value") ?? 0
        return li
    } else if kind == "ColorPicker" {
        return makeColorPicker(props)  // NSColorWell .minimal (M15, NDShell/ColorWells.swift)
    } else if kind == "Banner" {
        return makeBanner(props)  // SwiftUI chrome in NSHostingView (M15, NDShell/Banners.swift)
    } else if kind == "MenuButton" {
        return makeMenuButton(props)  // NSComboButton .unified (M15, NDShell/ComboButtons.swift)
    } else if kind == "SplitButton" {
        return makeSplitButton(props)  // NSComboButton .split (M15, NDShell/ComboButtons.swift)
    } else if kind == "Popover" {
        return makePopover(props)  // host-only handle owning a lazy .transient NSPopover (M15, NDShell/Popovers.swift)
    } else if kind == "Expander" {
        return makeExpander(props)  // .pushDisclosure + collapsible section (M15, NDShell/Expanders.swift)
    } else if kind == "StatusPage" {
        return makeStatusPage(props)  // SwiftUI ContentUnavailableView + actions row (M15, NDShell/StatusPages.swift)
    } else if kind == "ToastOverlay" {
        return makeToastOverlay(props)  // child-window toast presenter (M15, NDShell/Toasts.swift)
    } else if kind == "DatePicker" {
        return makeDatePicker(props)  // NSDatePicker .yearMonthDay, pinned UTC (M15, NDShell/DatePickers.swift)
    } else if kind == "Table" {
        return makeTable(props)  // view-based NSTableView in NSScrollView (M15, NDShell/Tables.swift)
    } else if kind == "TreeView" {
        return makeTreeView(props)  // NSOutlineView in NSScrollView (M15, NDShell/TreeViews.swift)
    } else if kind == "FontPicker" {
        return makeFontPicker(props)  // shared NSFontPanel + coordinator (M15, NDShell/FontPickers.swift)
    } else if kind == "Video" {
        return makeVideoView(props)  // AVKit AVPlayerView (M15, NDShell/Videos.swift)
    } else if kind == "TrayItem" {
        return makeTrayItem(props)  // NSStatusItem behind a host-only handle (M15, NDShell/TrayItems.swift)
    } else if kind == "ShareButton" {
        return makeShareButton(props)  // NSSharingServicePicker anchor button (M15, NDShell/ShareButtons.swift)
    } else if kind == "Terminal" {
        let cols = propInt(props, "cols") ?? 80
        let rows = propInt(props, "rows") ?? 24
        let fontSize = propInt(props, "fontSize") ?? 13
        let fontFamily = propStr(props, "fontFamily")
        let palette = propStr(props, "palette")
        let foreground = propStr(props, "foreground") ?? "#cccccc"
        let background = propStr(props, "background") ?? "#000000"
        // SEAM: NDTerminalView init signatures are the published contract with NDTerminalView.swift (package nd-terminal-surfaces) — keep both sides byte-for-byte in sync.
        //   init(command: String?, cwd: String?, fontSize: Int, fontFamily: String?, palette: String?, foreground: String, background: String, cols: Int, rows: Int)
        //   init(remote: Bool, host: String?, port: Int, sessionId: String?, ticket: String?, restoreScrollback: Bool, fontSize: Int, fontFamily: String?, palette: String?, foreground: String, background: String, cols: Int, rows: Int)
        if propBool(props, "remote") ?? false {
            return NDTerminalView(remote: true, host: propStr(props, "host"), port: propInt(props, "port") ?? 4618, sessionId: propStr(props, "sessionId"), ticket: propStr(props, "ticket"), restoreScrollback: propBool(props, "restoreScrollback") ?? false, fontSize: fontSize, fontFamily: fontFamily, palette: palette, foreground: foreground, background: background, cols: cols, rows: rows)
        }
        return NDTerminalView(command: propStr(props, "command"), cwd: propStr(props, "cwd"), fontSize: fontSize, fontFamily: fontFamily, palette: palette, foreground: foreground, background: background, cols: cols, rows: rows)
    } else if kind == "Paned" {
        let horizontal = (propStr(props, "orientation") ?? "horizontal") != "vertical"
        let split = NSSplitView()
        split.isVertical = horizontal
        let controller = PanedController(split: split)
        ndPanedControllers[ObjectIdentifier(split)] = controller
        controller.setPositionFraction(propDouble(props, "position") ?? 0.5)
        return split
    } else if kind == "CommandPalette" {
        return makeCommandPalette(props)  // host-only handle: dimmed scrim + centered card over the window (NDShell/CommandPalette.swift)
    }
    FileHandle.standardError.write("ND_WARN unknown widget kind=\(kind)\n".data(using: .utf8)!)
    return nil
}

func ndApplyProps(_ view: NSView, _ kind: String, _ propsJson: String) {
    let props = parseProps(propsJson)
    if kind == "Window" {
        if let t = propStr(props, "title"), let win = view.window { win.title = t }
    } else if kind == "Box" {
        if let sp = propInt(props, "spacing"), let stack = view as? NSStackView {
            stack.spacing = CGFloat(sp)
        }
    } else if kind == "Button" {
        if let tt = propStr(props, "tooltip"), let btn = view as? NSButton { btn.toolTip = tt }
    } else if kind == "TextInput" {
        if let t = propStr(props, "text"), let field = view as? NSTextField, field.stringValue != t {
            withEchoSuppressed(view) { field.stringValue = t }
        }
        if let ph = propStr(props, "placeholder"), let field = view as? NSTextField {
            field.placeholderString = ph
        }
        if let e = propBool(props, "editable"), let field = view as? NSTextField {
            field.isEditable = e
        }
    } else if kind == "TextArea" {
        if let t = propStr(props, "text"), let scroll = view as? NSScrollView,
           let textView = scroll.documentView as? NSTextView, textView.string != t {
            withEchoSuppressed(view) { textView.string = t }
        }
    } else if kind == "Checkbox" {
        if let c = propBool(props, "checked"), let btn = view as? NSButton {
            let want: NSControl.StateValue = c ? .on : .off
            if btn.state != want {
                withEchoSuppressed(view) { btn.state = want }
            }
        }
        if let l = propStr(props, "label"), let btn = view as? NSButton {
            btn.title = l
        }
    } else if kind == "Radio" {
        if let c = propBool(props, "checked"), let btn = view as? NSButton {
            let want: NSControl.StateValue = c ? .on : .off
            if btn.state != want {
                withEchoSuppressed(view) { btn.state = want }
            }
        }
        if let l = propStr(props, "label"), let btn = view as? NSButton {
            btn.title = l
        }
    } else if kind == "Select" {
        if let idx = propInt(props, "selectedIndex"), let pop = view as? NSPopUpButton, pop.indexOfSelectedItem != idx {
            withEchoSuppressed(view) { pop.selectItem(at: idx) }
        }
    } else if kind == "Slider" {
        if let v = propDouble(props, "value"), let slider = view as? NSSlider, abs(slider.doubleValue - v) > 1e-9 {
            withEchoSuppressed(view) { slider.doubleValue = v }
        }
    } else if kind == "ProgressBar" {
        if let f = propDouble(props, "fraction"), let pb = view as? NSProgressIndicator {
            pb.doubleValue = f * 100
        }
    } else if kind == "Image" {
        if let p_ = propStr(props, "path"), let iv = view as? NSImageView {
            iv.image = NSImage(contentsOfFile: p_)
        }
        if let n = propStr(props, "iconName"), let iv = view as? NSImageView {
            iv.image = ndResolveSymbolImage(n)  // NDShell/Icons.swift (hand-written)
        }
    } else if kind == "Spinner" {
        if let sp = propBool(props, "spinning"), let ind = view as? NSProgressIndicator {
            if sp { ind.startAnimation(nil) } else { ind.stopAnimation(nil) }
        }
    } else if kind == "TabView" {
        if let idx = propInt(props, "selectedIndex"), let tabs = view as? NSTabView,
           idx >= 0 && idx < tabs.numberOfTabViewItems {
            tabs.selectTabViewItem(at: idx)
        }
    } else if kind == "ListView" {
        if let items = propArray(props, "items") {
            ndListViewSetItems(view, items)  // NDGen/ListView.swift (T3, hand-written)
        }
        if let idx = propInt(props, "selectedIndex") {
            ndListViewSetSelectedIndex(view, idx)  // NDGen/ListView.swift (T3, hand-written)
        }
    } else if kind == "WebView" {
        if let u = propStr(props, "url"), let wv = view as? NDWebView { wv.ndSetURL(u) }
    } else if kind == "NativeView" {
        if let pj = propStr(props, "props"), let vk = propStr(props, "viewKind") {
            nd_plugin_view_apply_props(vk, Unmanaged.passUnretained(view).toOpaque(), pj)
        }
    } else if kind == "SplitView" {
        if let c = propBool(props, "collapsed"), let split = view as? NSSplitView,
           let controller = ndSplitViewController(for: split), let sidebarItem = controller.splitViewItems.first {
            sidebarItem.isCollapsed = c
        }
    } else if kind == "HeaderBar" {
        if let bar = view as? NDHeaderBarView {
            ndHeaderBarApplyNav(bar, canGoBack: propBool(props, "canGoBack"), canGoForward: propBool(props, "canGoForward"))
        }
    } else if kind == "SearchInput" {
        if let t = propStr(props, "text"), let field = view as? NSTextField, field.stringValue != t {
            withEchoSuppressed(view) { field.stringValue = t }
        }
        if let ph = propStr(props, "placeholder"), let field = view as? NSTextField {
            field.placeholderString = ph
        }
    } else if kind == "SourceList" {
        if let raw = propObjArray(props, "items") {
            ndSourceListSetItems(view, raw)  // NDGen/SourceList.swift (M11 Wave 2, hand-written)
        }
        if let idx = propInt(props, "selectedIndex") {
            ndSourceListSetSelectedIndex(view, idx)  // NDGen/SourceList.swift (M11 Wave 2, hand-written)
        }
    } else if kind == "SourceTree" {
        if let nodes = propObjArray(props, "nodes") { ndSourceTreeSetNodes(view, nodes) }
        if let actions = propObjArray(props, "actions") { ndSourceTreeSetActions(view, actions) }
        if let sel = propStr(props, "selectedId") { ndSourceTreeSetSelectedId(view, sel) }
    } else if kind == "MenuItem" {
        if let en = propBool(props, "enabled") { ndMenuItemSetEnabled(view, en) }
    } else if kind == "SettingsGroup" {
        if let sp = propInt(props, "spacing"), let stack = view as? NSStackView {
            stack.spacing = CGFloat(sp)
        }
    } else if kind == "Switch" {
        if let c = propBool(props, "checked"), let btn = view as? NSButton {
            let want: NSControl.StateValue = c ? .on : .off
            if btn.state != want {
                withEchoSuppressed(view) { btn.state = want }
            }
        }
    } else if kind == "ToggleButton" {
        if let l = propStr(props, "label"), let btn = view as? NSButton {
            btn.title = l
        }
        if let a = propBool(props, "active"), let btn = view as? NSButton {
            let want: NSControl.StateValue = a ? .on : .off
            if btn.state != want {
                withEchoSuppressed(view) { btn.state = want }
            }
        }
    } else if kind == "SegmentedControl" {
        if let idx = propInt(props, "selectedIndex"), let seg = view as? NSSegmentedControl,
           idx >= 0 && idx < seg.segmentCount && seg.selectedSegment != idx {
            withEchoSuppressed(view) { seg.selectedSegment = idx }
        }
    } else if kind == "NumberInput" {
        if let v = propDouble(props, "value") {
            withEchoSuppressed(view) { ndNumberInputSetValue(view, v) }
        }
    } else if kind == "LinkButton" {
        ndLinkButtonApply(view, props)
        // "uri" handled by ndLinkButtonApply above (merged).
        // "visited" handled by ndLinkButtonApply above (merged).
        // "openExternal" handled by ndLinkButtonApply above (merged).
    } else if kind == "LevelIndicator" {
        if let v = propDouble(props, "value"), let li = view as? NSLevelIndicator { li.doubleValue = v }
        if let wv = propDouble(props, "warningValue"), let li = view as? NSLevelIndicator { li.warningValue = wv }
        if let cv = propDouble(props, "criticalValue"), let li = view as? NSLevelIndicator { li.criticalValue = cv }
    } else if kind == "ColorPicker" {
        if let v = propStr(props, "value") { ndColorPickerSetValue(view, v) }
    } else if kind == "Banner" {
        ndBannerApply(view, props)  // title/buttonLabel/revealed merged
        // "buttonLabel" handled by ndBannerApply above (merged).
        // "revealed" handled by ndBannerApply above (merged).
    } else if kind == "MenuButton" {
        if let l = propStr(props, "label"), let combo = view as? NSComboButton { combo.title = l }
        if let ic = propStr(props, "iconName"), let combo = view as? NSComboButton { ndApplyComboIcon(combo, ic) }
    } else if kind == "SplitButton" {
        if let l = propStr(props, "label"), let combo = view as? NSComboButton { combo.title = l }
        if let ic = propStr(props, "iconName"), let combo = view as? NSComboButton { ndApplyComboIcon(combo, ic) }
    } else if kind == "Popover" {
        if let o = propBool(props, "open") { ndPopoverApplyOpen(view, o) }
        if let pos = propStr(props, "position") { ndPopoverApplyPosition(view, pos) }
    } else if kind == "Expander" {
        ndExpanderApply(view, props)  // label/expanded merged (expanded is echo-suppressed inside)
        // "expanded" handled by ndExpanderApply above (merged).
    } else if kind == "StatusPage" {
        ndStatusPageApply(view, props)  // iconName/title/description merged
        // "title" handled by ndStatusPageApply above (merged).
        // "description" handled by ndStatusPageApply above (merged).
    } else if kind == "DatePicker" {
        if let v = propStr(props, "value") { ndDatePickerSetValue(view, v) }
        // min/max merge in one call (absent keys keep prior state).
        ndDatePickerSetLimits(view, propStr(props, "minDate"), propStr(props, "maxDate"))
        // handled together with minDate above (ndDatePickerSetLimits merges both).
    } else if kind == "Table" {
        if let cols = propObjArray(props, "columns") { ndTableSetColumns(view, cols) }
        if let rows = propObjArray(props, "rows") { ndTableSetRows(view, rows) }
        if let idx = propInt(props, "selectedIndex") { ndTableSetSelectedIndex(view, idx) }
        if let sep = propBool(props, "showRowSeparators") { ndTableSetShowRowSeparators(view, sep) }
    } else if kind == "TreeView" {
        if let nodes = propObjArray(props, "nodes") { ndTreeViewSetNodes(view, nodes) }
        if let idx = propInt(props, "selectedIndex") { ndTreeViewSetSelectedIndex(view, idx) }
    } else if kind == "FontPicker" {
        if let v = propStr(props, "value") { ndFontPickerSetValue(view, v) }
    } else if kind == "Video" {
        if let s = propStr(props, "src") { ndVideoSetSrc(view, s) }
        if let l = propBool(props, "loop") { ndVideoSetLoop(view, l) }
    } else if kind == "TrayItem" {
        ndTrayItemApply(view, props)  // iconName/tooltip merged
        // "tooltip" handled by ndTrayItemApply above (merged).
    } else if kind == "ShareButton" {
        ndShareButtonApply(view, props)  // label/items merged
        // "items" handled by ndShareButtonApply above (merged).
    } else if kind == "Paned" {
        if let f = propDouble(props, "position"), let split = view as? NSSplitView,
           let controller = ndPanedController(for: split) {
            controller.setPositionFraction(f)
        }
    } else if kind == "CommandPalette" {
        if let o = propBool(props, "open") { ndCommandPaletteApplyOpen(view, o) }
        if let ph = propStr(props, "placeholder") { ndCommandPaletteApplyPlaceholder(view, ph) }
        if let q = propStr(props, "query") { ndCommandPaletteApplyQuery(view, q) }
        if let raw = propObjArray(props, "items") { ndCommandPaletteApplyItems(view, raw) }
    }
}

func ndConnectEvents(_ view: NSView, _ kind: String, _ nodeID: UInt32) {
    if kind == "Window" {
        ndWindowDialogsConnect(view, nodeID: nodeID)
        ndWindowTabsConnect(view, nodeID: nodeID)
    } else if kind == "Box" {
        ndHoverConnect(view, nodeID: nodeID)
    } else if kind == "Button" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "clicked", payload: .none, action: #selector(EventDispatcher.fireNone(_:)))
        ndHoverConnect(view, nodeID: nodeID)
    } else if kind == "TextInput" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "changed", payload: .text, action: #selector(EventDispatcher.fireText(_:)))
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "activate", payload: .text, action: #selector(EventDispatcher.fireText(_:)))
    } else if kind == "TextArea" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "changed", payload: .text, action: #selector(EventDispatcher.fireText(_:)))
    } else if kind == "Checkbox" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "toggled", payload: .checked, action: #selector(EventDispatcher.fireChecked(_:)))
    } else if kind == "Radio" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "toggled", payload: .checked, action: #selector(EventDispatcher.fireChecked(_:)))
    } else if kind == "Select" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "selectionChanged", payload: .index, action: #selector(EventDispatcher.fireIndex(_:)))
    } else if kind == "Slider" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "valueChanged", payload: .value, action: #selector(EventDispatcher.fireValue(_:)))
    } else if kind == "ListView" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "rowActivated", payload: .index, action: #selector(EventDispatcher.fireIndex(_:)))
    } else if kind == "WebView" {
        ndWebViewConnect(view, nodeID: nodeID)
    } else if kind == "NativeView" {
    } else if kind == "HeaderBar" {
        ndHeaderBarConnectNav(view, nodeID: nodeID)
    } else if kind == "SearchInput" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "changed", payload: .text, action: #selector(EventDispatcher.fireText(_:)))
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "activate", payload: .text, action: #selector(EventDispatcher.fireText(_:)))
    } else if kind == "SourceList" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "selectionChanged", payload: .index, action: #selector(EventDispatcher.fireIndex(_:)))
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "rowActivated", payload: .index, action: #selector(EventDispatcher.fireIndex(_:)))
    } else if kind == "SourceTree" {
        ndSourceTreeConnect(view, nodeID: nodeID)
    } else if kind == "MenuItem" {
        ndMenuItemConnect(view, nodeID: nodeID) // M13: NSMenuItem target/action, not EventDispatcher
    } else if kind == "Switch" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "toggled", payload: .checked, action: #selector(EventDispatcher.fireChecked(_:)))
    } else if kind == "ToggleButton" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "toggled", payload: .checked, action: #selector(EventDispatcher.fireChecked(_:)))
    } else if kind == "SegmentedControl" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "selectionChanged", payload: .index, action: #selector(EventDispatcher.fireIndex(_:)))
    } else if kind == "NumberInput" {
        ndNumberInputConnect(view, nodeID: nodeID)
    } else if kind == "LinkButton" {
        ndLinkButtonConnect(view, nodeID: nodeID)
    } else if kind == "ColorPicker" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "colorChanged", payload: .text, action: #selector(EventDispatcher.fireColorText(_:)))
    } else if kind == "Banner" {
        ndBannerConnect(view, nodeID: nodeID)
    } else if kind == "SplitButton" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "clicked", payload: .none, action: #selector(EventDispatcher.fireNone(_:)))
    } else if kind == "Popover" {
        ndPopoverConnect(view, nodeID: nodeID)
    } else if kind == "Expander" {
        ndExpanderConnect(view, nodeID: nodeID)
    } else if kind == "ToastOverlay" {
        ndToastOverlayConnect(view, nodeID: nodeID)
    } else if kind == "DatePicker" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "dateChanged", payload: .text, action: #selector(EventDispatcher.fireDateText(_:)))
    } else if kind == "Table" {
        ndTableConnect(view, nodeID: nodeID)
    } else if kind == "TreeView" {
        ndTreeViewConnect(view, nodeID: nodeID)
    } else if kind == "FontPicker" {
        ndFontPickerConnect(view, nodeID: nodeID)
    } else if kind == "Terminal" {
        ndTerminalConnect(view, nodeID: nodeID)
    } else if kind == "Paned" {
        ndPanedConnect(view, nodeID: nodeID)
    } else if kind == "CommandPalette" {
        ndCommandPaletteConnect(view, nodeID: nodeID)
    }
}

/// App -> widget imperative commands (widgetCommand NDP frame, M14).
func ndWidgetCommand(_ view: NSView, _ kind: String, _ command: String, _ argJson: String) {
    if kind == "Window" {
        if command == "showTabOverview" || command == "present" { ndWindowTabsCommand(view, command, argJson); return }
        ndWindowCommand(view, command, argJson)
    } else if kind == "WebView" {
        ndWebViewCommand(view, command, argJson)
    } else if kind == "ToastOverlay" {
        ndToastOverlayCommand(view, command, argJson)
    } else if kind == "Terminal" {
        ndTerminalCommand(view, command, argJson)
    } else {
        FileHandle.standardError.write("ND_WARN widgetCommand on kind=\(kind) with no commands\n".data(using: .utf8)!)
    }
}

func ndAppendChild(_ parent: NSView, _ parentKind: String, _ child: NSView, _ attachedJson: String) {
    // Cross-cutting (M15): a Popover child anchors on its tree parent
    // (never box-packed); a TrayItem is menu-bar chrome, never content.
    if ndPopoverStructuralAttach(child, parent) { return }
    if ndTrayItemStructuralAttach(child) { return }
    let attached = parseProps(attachedJson)
    let attachedTabLabel = propStr(attached, "tabLabel") ?? ""
    let attachedGridRow = propInt(attached, "gridRow") ?? 0
    let attachedGridColumn = propInt(attached, "gridColumn") ?? 0
    let attachedGridRowSpan = propInt(attached, "gridRowSpan") ?? 1
    let attachedGridColumnSpan = propInt(attached, "gridColumnSpan") ?? 1
    let attachedSlot = propStr(attached, "slot") ?? "content"
    if parentKind == "Window" {
        if ndMenuAttachToWindow(child) { return } // M13: a <menubar> child is app chrome (NSApp.mainMenu), not window content
        let window = parent.window ?? gWindow
        parent.subviews.forEach { $0.removeFromSuperview() }
        if let pane = child as? NDToolbarPaneView {
            if let win = window, win.contentViewController != nil {
                win.contentViewController = nil
                win.contentView = parent
            }
            ndToolbarPaneAttachedToWindow(pane)
            let content = pane.contentView ?? pane
            parent.addSubview(content)
            content.translatesAutoresizingMaskIntoConstraints = false
            NSLayoutConstraint.activate([
                content.topAnchor.constraint(equalTo: parent.safeAreaLayoutGuide.topAnchor),
                content.leadingAnchor.constraint(equalTo: parent.leadingAnchor),
                content.trailingAnchor.constraint(equalTo: parent.trailingAnchor),
                content.bottomAnchor.constraint(equalTo: parent.bottomAnchor),
            ])
            return
        }
        if let split = child as? NSSplitView, let controller = ndSplitViewController(for: split), let win = window {
            ndInstallSplitAsWindowContent(split, controller, win)
        } else if let overlay = child as? NDToastOverlayView, let split = overlay.ndEmbeddedSplit,
                  let controller = ndSplitViewController(for: split), let win = window {
            ndInstallSplitAsWindowContent(split, controller, win)
            overlay.ndHostWindow = win
        } else {
            if let win = window, win.contentViewController != nil {
                win.contentViewController = nil
                win.contentView = parent
            }
            parent.addSubview(child)
            child.translatesAutoresizingMaskIntoConstraints = false
            NSLayoutConstraint.activate([
                child.topAnchor.constraint(equalTo: parent.safeAreaLayoutGuide.topAnchor),
                child.leadingAnchor.constraint(equalTo: parent.leadingAnchor),
                child.trailingAnchor.constraint(equalTo: parent.trailingAnchor),
                child.bottomAnchor.constraint(equalTo: parent.bottomAnchor),
            ])
        }
    } else if parentKind == "Box" {
        let stack = parent as! NSStackView
        stack.addArrangedSubview(child)
        ndBoxChildAttached(stack, child)
    } else if parentKind == "ScrollView" {
        let sv = parent as! NSScrollView
        let doc = sv.documentView!
        doc.subviews.forEach { $0.removeFromSuperview() }
        child.translatesAutoresizingMaskIntoConstraints = false
        doc.addSubview(child)
        NSLayoutConstraint.activate([
            child.leadingAnchor.constraint(equalTo: doc.leadingAnchor),
            child.trailingAnchor.constraint(equalTo: doc.trailingAnchor),
            child.topAnchor.constraint(equalTo: doc.topAnchor),
            child.bottomAnchor.constraint(equalTo: doc.bottomAnchor),
        ])
    } else if parentKind == "TabView" {
        let tabs = parent as! NSTabView
        let item = NSTabViewItem()
        item.view = child
        item.label = attachedTabLabel
        tabs.addTabViewItem(item)
    } else if parentKind == "Grid" {
        let grid = parent as! NSGridView
        ndGridPlace(grid, child, row: attachedGridRow, column: attachedGridColumn, rowSpan: attachedGridRowSpan, columnSpan: attachedGridColumnSpan)
    } else if parentKind == "SplitView" {
        let split = parent as! NSSplitView
        let controller = ndSplitViewController(for: split)!
        var realChild = child
        if let pane = child as? NDToolbarPaneView {
            ndToolbarPaneAttachedToSplit(pane, split: split, slot: attachedSlot)
            realChild = pane.contentView ?? child
        }
        let vc = ndMakePaneViewController(realChild)
        if attachedSlot == "sidebar" {
            let item = NSSplitViewItem(sidebarWithViewController: vc)
            item.minimumThickness = 180
            if let fraction = splitViewSidebarFraction[ObjectIdentifier(split)] {
                item.preferredThicknessFraction = fraction
            }
            item.canCollapse = true
            item.isCollapsed = splitViewCollapsed[ObjectIdentifier(split)] ?? false
            controller.insertSplitViewItem(item, at: 0)
        } else if attachedSlot == "list" {
            let item = NSSplitViewItem(contentListWithViewController: vc)
            item.minimumThickness = 240
            item.canCollapse = true
            if let fraction = splitViewListFraction[ObjectIdentifier(split)] {
                item.preferredThicknessFraction = fraction
            }
            let insertIndex = controller.splitViewItems.first?.behavior == .sidebar ? 1 : 0
            controller.insertSplitViewItem(item, at: insertIndex)
        } else {
            let item = NSSplitViewItem(viewController: vc)
            item.automaticallyAdjustsSafeAreaInsets = true
            controller.addSplitViewItem(item)
        }
    } else if parentKind == "HeaderBar" {
        ndHeaderBarPack(parent as! NDHeaderBarView, child, slot: attachedSlot)
    } else if parentKind == "ToolbarView" {
        ndToolbarPanePack(parent as! NDToolbarPaneView, child)
    } else if parentKind == "Menubar" {
        ndMenuAppendChild(parent, child)
    } else if parentKind == "Menu" {
        ndMenuAppendChild(parent, child)
    } else if parentKind == "SettingsGroup" {
        let group = parent as! NDSettingsGroupView
        group.appendReactView(child)
    } else if parentKind == "MenuButton" {
        ndMenuOwnerAppend(parent, child)
    } else if parentKind == "SplitButton" {
        ndMenuOwnerAppend(parent, child)
    } else if parentKind == "Popover" {
        ndPopoverSetChild(parent, child)
    } else if parentKind == "Expander" {
        (parent as! NDExpanderView).setContentChild(child)
    } else if parentKind == "StatusPage" {
        ndStatusPagePack(parent, child, before: nil)
    } else if parentKind == "ToastOverlay" {
        ndToastOverlaySetChild(parent, child)
    } else if parentKind == "TrayItem" {
        ndMenuOwnerAppend(parent, child)
    } else if parentKind == "Paned" {
        let split = parent as! NSSplitView
        split.addSubview(child)
        ndPanedController(for: split)?.reapplyFraction()
    } else {
        FileHandle.standardError.write("ND_WARN append to non-container kind=\(parentKind)\n".data(using: .utf8)!)
    }
}

func ndInsertBefore(_ parent: NSView, _ parentKind: String, _ child: NSView, _ before: NSView?, _ attachedJson: String) {
    // nil `before` degenerates to append everywhere (matches the M4 hand-written contract).
    guard let before = before else { return ndAppendChild(parent, parentKind, child, attachedJson) }
    // Cross-cutting (M15): Popover/TrayItem children are position-independent.
    if ndPopoverStructuralAttach(child, parent) { return }
    if ndTrayItemStructuralAttach(child) { return }
    let attached = parseProps(attachedJson)
    let attachedTabLabel = propStr(attached, "tabLabel") ?? ""
    let attachedGridRow = propInt(attached, "gridRow") ?? 0
    let attachedGridColumn = propInt(attached, "gridColumn") ?? 0
    let attachedGridRowSpan = propInt(attached, "gridRowSpan") ?? 1
    let attachedGridColumnSpan = propInt(attached, "gridColumnSpan") ?? 1
    let attachedSlot = propStr(attached, "slot") ?? "content"
    if parentKind == "Box" {
        let stack = parent as! NSStackView
        if stack.arrangedSubviews.contains(child) { stack.removeArrangedSubview(child) }
        let idx = stack.arrangedSubviews.firstIndex(of: before) ?? stack.arrangedSubviews.count
        stack.insertArrangedSubview(child, at: idx)
        ndBoxChildAttached(stack, child)
    } else if parentKind == "TabView" {
        let tabs = parent as! NSTabView
        let item = NSTabViewItem()
        item.view = child
        item.label = attachedTabLabel
        let idx = tabs.tabViewItems.firstIndex { $0.view === before } ?? tabs.tabViewItems.count
        tabs.insertTabViewItem(item, at: idx)
    } else if parentKind == "Grid" {
        // Grid children are position-addressed; sibling order is irrelevant.
        let grid = parent as! NSGridView
        ndGridPlace(grid, child, row: attachedGridRow, column: attachedGridColumn, rowSpan: attachedGridRowSpan, columnSpan: attachedGridColumnSpan)
    } else if parentKind == "SplitView" {
        let split = parent as! NSSplitView
        let controller = ndSplitViewController(for: split)!
        var realChild = child
        if let pane = child as? NDToolbarPaneView {
            ndToolbarPaneAttachedToSplit(pane, split: split, slot: attachedSlot)
            realChild = pane.contentView ?? child
        }
        let vc = ndMakePaneViewController(realChild)
        if attachedSlot == "sidebar" {
            let item = NSSplitViewItem(sidebarWithViewController: vc)
            item.minimumThickness = 180
            if let fraction = splitViewSidebarFraction[ObjectIdentifier(split)] {
                item.preferredThicknessFraction = fraction
            }
            item.canCollapse = true
            item.isCollapsed = splitViewCollapsed[ObjectIdentifier(split)] ?? false
            controller.insertSplitViewItem(item, at: 0)
        } else if attachedSlot == "list" {
            let item = NSSplitViewItem(contentListWithViewController: vc)
            item.minimumThickness = 240
            item.canCollapse = true
            if let fraction = splitViewListFraction[ObjectIdentifier(split)] {
                item.preferredThicknessFraction = fraction
            }
            let insertIndex = controller.splitViewItems.first?.behavior == .sidebar ? 1 : 0
            controller.insertSplitViewItem(item, at: insertIndex)
        } else {
            let item = NSSplitViewItem(viewController: vc)
            item.automaticallyAdjustsSafeAreaInsets = true
            controller.addSplitViewItem(item)
        }
    } else if parentKind == "HeaderBar" {
        ndHeaderBarPack(parent as! NDHeaderBarView, child, slot: attachedSlot)
    } else if parentKind == "ToolbarView" {
        ndToolbarPanePack(parent as! NDToolbarPaneView, child)
    } else if parentKind == "Menubar" {
        ndMenuAppendChild(parent, child)
    } else if parentKind == "Menu" {
        ndMenuAppendChild(parent, child)
    } else if parentKind == "SettingsGroup" {
        let group = parent as! NDSettingsGroupView
        group.insertReactView(child, before: before)
    } else if parentKind == "MenuButton" {
        ndMenuOwnerAppend(parent, child)
    } else if parentKind == "SplitButton" {
        ndMenuOwnerAppend(parent, child)
    } else if parentKind == "StatusPage" {
        ndStatusPagePack(parent, child, before: before)
    } else if parentKind == "TrayItem" {
        ndMenuOwnerAppend(parent, child)
    } else if parentKind == "Paned" {
        let split = parent as! NSSplitView
        let idx = split.arrangedSubviews.firstIndex(of: before) ?? split.arrangedSubviews.count
        split.insertArrangedSubview(child, at: idx)
        ndPanedController(for: split)?.reapplyFraction()
    } else {
        // single-child containers: insertBefore degenerates to appendChild.
        ndAppendChild(parent, parentKind, child, attachedJson)
    }
}

func ndRemoveChild(_ parent: NSView, _ parentKind: String, _ child: NSView) {
    // Cross-cutting (M15): detach an anchored Popover / tear down a
    // TrayItem's NSStatusItem — neither was ever a layout child.
    if ndPopoverStructuralDetach(child, parent) { return }
    if ndTrayItemStructuralDetach(child) { return }
    // Cross-cutting: deregister a torn-down `<paned>`'s controller (no-op
    // unless `child` is itself a Paned's outer split view) — additive, not a
    // short-circuit, since the split view still needs the ordinary
    // removeFromSuperview dispatch below.
    ndPanedTeardown(child)
    if parentKind == "Window" {
        if ndIsMenuNode(child) { return } // M13: menubar detach is a no-op (mainMenu rebuilt on next change)
        if let pane = child as? NDToolbarPaneView {
            ndToolbarPaneDetachedFromSplit(pane) // same unregister path as the split arm
            (pane.contentView ?? pane).removeFromSuperview()
            return
        }
        if let split = child as? NSSplitView, let controller = ndSplitViewController(for: split),
           let window = parent.window ?? gWindow, window.contentViewController === controller {
            window.contentViewController = nil
            window.contentView = parent
        } else if let overlay = child as? NDToastOverlayView, let split = overlay.ndEmbeddedSplit,
                  let controller = ndSplitViewController(for: split),
                  let window = overlay.ndHostWindow ?? parent.window ?? gWindow, window.contentViewController === controller {
            window.contentViewController = nil
            window.contentView = parent
            overlay.ndHostWindow = nil
        } else {
            child.removeFromSuperview()
        }
    } else if parentKind == "Box" {
        let stack = parent as! NSStackView
        stack.removeArrangedSubview(child)
        ndBoxChildDetached(stack, child)
        child.removeFromSuperview()
    } else if parentKind == "ScrollView" {
        let sv = parent as! NSScrollView
        if child.superview === sv.documentView { child.removeFromSuperview() }
    } else if parentKind == "TabView" {
        let tabs = parent as! NSTabView
        if let item = tabs.tabViewItems.first(where: { $0.view === child }) {
            tabs.removeTabViewItem(item)
        }
    } else if parentKind == "Grid" {
        let grid = parent as! NSGridView
        ndGridRemove(grid, child)
    } else if parentKind == "SplitView" {
        let split = parent as! NSSplitView
        let controller = ndSplitViewController(for: split)!
        var realChild = child
        if let pane = child as? NDToolbarPaneView {
            ndToolbarPaneDetachedFromSplit(pane)
            realChild = pane.contentView ?? child
        }
        if let item = controller.splitViewItems.first(where: { $0.viewController.view === realChild || realChild.isDescendant(of: $0.viewController.view) }) {
            controller.removeSplitViewItem(item)
        } else {
            split.removeArrangedSubview(realChild)
            realChild.removeFromSuperview()
        }
    } else if parentKind == "HeaderBar" {
        ndHeaderBarUnpack(parent as! NDHeaderBarView, child)
    } else if parentKind == "ToolbarView" {
        ndToolbarPaneUnpack(parent as! NDToolbarPaneView, child)
    } else if parentKind == "Menubar" {
        ndMenuRemoveChild(parent, child)
    } else if parentKind == "Menu" {
        ndMenuRemoveChild(parent, child)
    } else if parentKind == "SettingsGroup" {
        let group = parent as! NDSettingsGroupView
        group.removeReactView(child)
    } else if parentKind == "MenuButton" {
        ndMenuOwnerRemove(parent, child)
    } else if parentKind == "SplitButton" {
        ndMenuOwnerRemove(parent, child)
    } else if parentKind == "Popover" {
        ndPopoverClearChild(parent, child)
    } else if parentKind == "Expander" {
        (parent as! NDExpanderView).clearContentChild(child)
    } else if parentKind == "StatusPage" {
        ndStatusPageUnpack(parent, child)
    } else if parentKind == "ToastOverlay" {
        ndToastOverlayClearChild(parent, child)
    } else if parentKind == "TrayItem" {
        ndMenuOwnerRemove(parent, child)
    } else if parentKind == "Paned" {
        let split = parent as! NSSplitView
        child.removeFromSuperview()
        ndPanedController(for: split)?.reapplyFraction()
    } else {
        FileHandle.standardError.write("ND_WARN remove from non-container kind=\(parentKind)\n".data(using: .utf8)!)
    }
}
