// GENERATED by tools/codegen.ts — do not edit
import AppKit
import Foundation

// JSON-string -> [String: Any] (M6b-D1: JSONSerialization, not a typed decoder).
func parseProps(_ json: String) -> [String: Any] {
    guard let data = json.data(using: .utf8),
          let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
    else { return [:] }
    return obj
}
func propStr(_ p: [String: Any], _ k: String) -> String? { p[k] as? String }
func propInt(_ p: [String: Any], _ k: String) -> Int? { (p[k] as? NSNumber)?.intValue }
func propDouble(_ p: [String: Any], _ k: String) -> Double? { (p[k] as? NSNumber)?.doubleValue }
func propBool(_ p: [String: Any], _ k: String) -> Bool? { (p[k] as? NSNumber)?.boolValue }
func propArray(_ p: [String: Any], _ k: String) -> [String]? { (p[k] as? [Any])?.compactMap { $0 as? String } }
func propObjArray(_ p: [String: Any], _ k: String) -> [[String: Any]]? { (p[k] as? [Any])?.compactMap { $0 as? [String: Any] } }

// Every container view class is flipped (top-left y-down) — GLOBAL CONSTRAINT.
final class FlippedView: NSView { override var isFlipped: Bool { true } }

// SplitView's `sidebarWidth`/`collapsed` (create-time props on the
// NSSplitView itself) are read again when the sidebar child later appends
// and becomes an NSSplitViewItem — stashed here since the item doesn't exist
// yet at create time.
nonisolated(unsafe) private var splitViewSidebarFraction: [ObjectIdentifier: Double] = [:]
nonisolated(unsafe) private var splitViewCollapsed: [ObjectIdentifier: Bool] = [:]
// M13: three-pane SplitView's `listWidth` (create-time prop for the
// contentList NSSplitViewItem) — same stash-until-append mechanism as
// `splitViewSidebarFraction`, keyed by the same outer splitView identity.
nonisolated(unsafe) private var splitViewListFraction: [ObjectIdentifier: Double] = [:]

func ndCreate(_ kind: String, _ propsJson: String) -> NSView? {
    let props = parseProps(propsJson)
    if kind == "Window" {
        let content = FlippedView()
        let winW = propInt(props, "defaultWidth") ?? 480
        let winH = propInt(props, "defaultHeight") ?? 320
        let win = NSWindow(contentRect: NSRect(x: 0, y: 0, width: CGFloat(winW), height: CGFloat(winH)), styleMask: [.titled, .closable, .resizable, .fullSizeContentView], backing: .buffered, defer: false)
        if let t = propStr(props, "title") { win.title = t }
        win.titlebarAppearsTransparent = true
        win.contentView = content
        gWindow = win
        let manager = NDToolbarManager()
        ndWindowToolbarManager = manager
        win.toolbar = manager.toolbar
        win.toolbarStyle = .unified
        ndEnsureMenuManager() // M13: install the default NSApp.mainMenu (App/File/Edit/View/Window/Help)
        win.center(); win.makeKeyAndOrderFront(nil)
        return content
    } else if kind == "Box" {
        let stack = NSStackView()
        let vertical = (propStr(props, "orientation") ?? "vertical") == "vertical"
        stack.orientation = vertical ? .vertical : .horizontal
        stack.spacing = CGFloat(propInt(props, "spacing") ?? 0)
        stack.alignment = vertical ? .leading : .centerY
        stack.distribution = .gravityAreas
        return stack
    } else if kind == "Label" {
        let text = propStr(props, "text") ?? ""
        let label = NDTextField(labelWithString: text)
        return label
    } else if kind == "Button" {
        let lbl = propStr(props, "label") ?? "Button"
        let b = NDButton(title: lbl, target: nil, action: nil)
        b.setButtonType(.momentaryPushIn); b.bezelStyle = .rounded
        if let icon = propStr(props, "iconName") {
            ndApplyButtonIcon(b, iconName: icon, label: lbl)  // NDShell/Icons.swift (hand-written)
        }
        switch propStr(props, "labelAlign") ?? "center" {
        case "start": b.alignment = .left
        case "end": b.alignment = .right
        default: break
        }
        return b
    } else if kind == "TextInput" {
        let field = NDTextField(string: propStr(props, "text") ?? "")
        if let ph = propStr(props, "placeholder") { field.placeholderString = ph }
        if let e = propBool(props, "editable") { field.isEditable = e }
        return field
    } else if kind == "TextArea" {
        let scroll = NSScrollView()
        scroll.hasVerticalScroller = true
        let textView = NSTextView()
        textView.string = propStr(props, "text") ?? ""
        scroll.documentView = textView
        let minH = propInt(props, "minContentHeight") ?? 120
        if minH > 0 {
            scroll.frame.size.height = CGFloat(minH)
            let floor_ = scroll.heightAnchor.constraint(greaterThanOrEqualToConstant: CGFloat(minH))
            floor_.priority = NSLayoutConstraint.Priority(999)
            floor_.isActive = true
        }
        return scroll
    } else if kind == "Checkbox" {
        let cb = NSButton(checkboxWithTitle: propStr(props, "label") ?? "", target: nil, action: nil)
        cb.state = (propBool(props, "checked") ?? false) ? .on : .off
        return cb
    } else if kind == "Radio" {
        let r = NSButton(radioButtonWithTitle: propStr(props, "label") ?? "", target: nil, action: nil)
        r.state = (propBool(props, "checked") ?? false) ? .on : .off
        if let g = propStr(props, "group") {
            radioGroupIdentifier[ObjectIdentifier(r)] = g   // mutual exclusion wired in connectEvents (T4)
        } else {
            FileHandle.standardError.write("ND_WARN Radio without group prop\n".data(using: .utf8)!)
        }
        return r
    } else if kind == "Select" {
        let pop = NSPopUpButton(frame: .zero, pullsDown: false)
        if let opts = propArray(props, "options") { pop.addItems(withTitles: opts) }
        let idx = propInt(props, "selectedIndex") ?? 0
        if idx >= 0 && idx < pop.numberOfItems { pop.selectItem(at: idx) }
        return pop
    } else if kind == "Slider" {
        let min = propDouble(props, "min") ?? 0
        let max = propDouble(props, "max") ?? 100
        let value = propDouble(props, "value") ?? 0
        let slider = NSSlider(value: value, minValue: min, maxValue: max, target: nil, action: nil)
        slider.isVertical = (propStr(props, "orientation") ?? "horizontal") == "vertical"
        return slider
    } else if kind == "ProgressBar" {
        let pb = NSProgressIndicator()
        pb.style = .bar
        pb.isIndeterminate = false
        pb.minValue = 0; pb.maxValue = 100
        pb.doubleValue = (propDouble(props, "fraction") ?? 0) * 100
        return pb
    } else if kind == "Image" {
        let iv = NSImageView()
        if let p = propStr(props, "path") {
            iv.image = NSImage(contentsOfFile: p)
        } else if let n = propStr(props, "iconName") {
            iv.image = NSImage(named: n)
        }
        return iv
    } else if kind == "ScrollView" {
        let sv = NSScrollView()
        sv.hasVerticalScroller = true
        sv.drawsBackground = false
        let doc = FlippedView()
        sv.documentView = doc
        doc.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            doc.leadingAnchor.constraint(equalTo: sv.contentView.leadingAnchor),
            doc.trailingAnchor.constraint(equalTo: sv.contentView.trailingAnchor),
            doc.topAnchor.constraint(equalTo: sv.contentView.topAnchor),
            doc.widthAnchor.constraint(equalTo: sv.contentView.widthAnchor),
        ])
        let minH = propInt(props, "minContentHeight") ?? 0
        if minH > 0 {
            sv.frame.size.height = CGFloat(minH)
            let floor_ = sv.heightAnchor.constraint(greaterThanOrEqualToConstant: CGFloat(minH))
            floor_.priority = NSLayoutConstraint.Priority(999)
            floor_.isActive = true
        }
        return sv
    } else if kind == "Separator" {
        let sep = NSBox()
        sep.boxType = .separator
        let vertical = (propStr(props, "orientation") ?? "horizontal") == "vertical"
        sep.frame = vertical ? NSRect(x: 0, y: 0, width: 1, height: 24) : NSRect(x: 0, y: 0, width: 24, height: 1)
        return sep
    } else if kind == "Spinner" {
        let sp = NSProgressIndicator()
        sp.style = .spinning
        sp.isIndeterminate = true
        if propBool(props, "spinning") ?? true { sp.startAnimation(nil) } else { sp.stopAnimation(nil) }
        return sp
    } else if kind == "TabView" {
        // selectedIndex is ignored at create: pages attach afterwards (mirrors genZigCreateBody).
        let tabs = NSTabView()
        return tabs
    } else if kind == "Grid" {
        let grid = NSGridView(numberOfColumns: 1, rows: 0)
        return grid
    } else if kind == "ListView" {
        return makeListView(props)  // NSScrollView+NSTableView, view-based recycling (M6b-D2)
    } else if kind == "WebView" {
        FileHandle.standardError.write("ND_WARN WebView is a v1 stub (no WKWebView); rendering placeholder label\n".data(using: .utf8)!)
        let placeholder = NSTextField(labelWithString: "WebView unavailable (v1 stub)")
        return placeholder
    } else if kind == "SplitView" {
        let controller = NSSplitViewController()
        controller.splitView.isVertical = true
        controller.splitView.dividerStyle = .thin
        ndSplitControllers[ObjectIdentifier(controller.splitView)] = controller
        if let w = propDouble(props, "sidebarWidth"), w > 0 {
            splitViewSidebarFraction[ObjectIdentifier(controller.splitView)] = w
        }
        if let lw = propDouble(props, "listWidth"), lw > 0 {
            splitViewListFraction[ObjectIdentifier(controller.splitView)] = lw
        }
        if propBool(props, "collapsed") ?? false {
            splitViewCollapsed[ObjectIdentifier(controller.splitView)] = true
        }
        return controller.splitView
    } else if kind == "HeaderBar" {
        let bar = NDHeaderBarView()
        bar.ndTitle = propStr(props, "title") ?? ""
        return bar
    } else if kind == "ToolbarView" {
        return NDToolbarPaneView()
    } else if kind == "SearchInput" {
        let search = NSSearchField(string: propStr(props, "text") ?? "")
        if let ph = propStr(props, "placeholder") { search.placeholderString = ph }
        return search
    } else if kind == "SourceList" {
        return makeSourceList(props)  // NSScrollView+NSTableView(.sourceList) (M11 Wave 2, NDGen/SourceList.swift)
    } else if kind == "Menubar" {
        return ndMenubarCreate(propBool(props, "defaults") ?? true)
    } else if kind == "Menu" {
        return ndMenuCreate(propStr(props, "label") ?? "")
    } else if kind == "MenuItem" {
        return ndMenuItemCreate(props)
    }
    FileHandle.standardError.write("ND_WARN unknown widget kind=\(kind)\n".data(using: .utf8)!)
    return nil
}

func ndApplyProps(_ view: NSView, _ kind: String, _ propsJson: String) {
    let props = parseProps(propsJson)
    if kind == "Window" {
        if let t = propStr(props, "title"), let win = view.window { win.title = t }
    } else if kind == "Box" {
        if let sp = propInt(props, "spacing"), let stack = view as? NSStackView {
            stack.spacing = CGFloat(sp)
        }
    } else if kind == "TextInput" {
        if let t = propStr(props, "text"), let field = view as? NSTextField, field.stringValue != t {
            withEchoSuppressed(view) { field.stringValue = t }
        }
        if let ph = propStr(props, "placeholder"), let field = view as? NSTextField {
            field.placeholderString = ph
        }
        if let e = propBool(props, "editable"), let field = view as? NSTextField {
            field.isEditable = e
        }
    } else if kind == "TextArea" {
        if let t = propStr(props, "text"), let scroll = view as? NSScrollView,
           let textView = scroll.documentView as? NSTextView, textView.string != t {
            withEchoSuppressed(view) { textView.string = t }
        }
    } else if kind == "Checkbox" {
        if let c = propBool(props, "checked"), let btn = view as? NSButton {
            let want: NSControl.StateValue = c ? .on : .off
            if btn.state != want {
                withEchoSuppressed(view) { btn.state = want }
            }
        }
        if let l = propStr(props, "label"), let btn = view as? NSButton {
            btn.title = l
        }
    } else if kind == "Radio" {
        if let c = propBool(props, "checked"), let btn = view as? NSButton {
            let want: NSControl.StateValue = c ? .on : .off
            if btn.state != want {
                withEchoSuppressed(view) { btn.state = want }
            }
        }
        if let l = propStr(props, "label"), let btn = view as? NSButton {
            btn.title = l
        }
    } else if kind == "Select" {
        if let idx = propInt(props, "selectedIndex"), let pop = view as? NSPopUpButton, pop.indexOfSelectedItem != idx {
            withEchoSuppressed(view) { pop.selectItem(at: idx) }
        }
    } else if kind == "Slider" {
        if let v = propDouble(props, "value"), let slider = view as? NSSlider, abs(slider.doubleValue - v) > 1e-9 {
            withEchoSuppressed(view) { slider.doubleValue = v }
        }
    } else if kind == "ProgressBar" {
        if let f = propDouble(props, "fraction"), let pb = view as? NSProgressIndicator {
            pb.doubleValue = f * 100
        }
    } else if kind == "Image" {
        if let p_ = propStr(props, "path"), let iv = view as? NSImageView {
            iv.image = NSImage(contentsOfFile: p_)
        }
        if let n = propStr(props, "iconName"), let iv = view as? NSImageView {
            iv.image = NSImage(named: n)
        }
    } else if kind == "Spinner" {
        if let sp = propBool(props, "spinning"), let ind = view as? NSProgressIndicator {
            if sp { ind.startAnimation(nil) } else { ind.stopAnimation(nil) }
        }
    } else if kind == "TabView" {
        if let idx = propInt(props, "selectedIndex"), let tabs = view as? NSTabView,
           idx >= 0 && idx < tabs.numberOfTabViewItems {
            tabs.selectTabViewItem(at: idx)
        }
    } else if kind == "ListView" {
        if let items = propArray(props, "items") {
            ndListViewSetItems(view, items)  // NDGen/ListView.swift (T3, hand-written)
        }
        if let idx = propInt(props, "selectedIndex") {
            ndListViewSetSelectedIndex(view, idx)  // NDGen/ListView.swift (T3, hand-written)
        }
    } else if kind == "SplitView" {
        if let c = propBool(props, "collapsed"), let split = view as? NSSplitView,
           let controller = ndSplitViewController(for: split), let sidebarItem = controller.splitViewItems.first {
            sidebarItem.isCollapsed = c
        }
    } else if kind == "SearchInput" {
        if let t = propStr(props, "text"), let field = view as? NSTextField, field.stringValue != t {
            withEchoSuppressed(view) { field.stringValue = t }
        }
        if let ph = propStr(props, "placeholder"), let field = view as? NSTextField {
            field.placeholderString = ph
        }
    } else if kind == "SourceList" {
        if let raw = propObjArray(props, "items") {
            ndSourceListSetItems(view, raw)  // NDGen/SourceList.swift (M11 Wave 2, hand-written)
        }
        if let idx = propInt(props, "selectedIndex") {
            ndSourceListSetSelectedIndex(view, idx)  // NDGen/SourceList.swift (M11 Wave 2, hand-written)
        }
    } else if kind == "MenuItem" {
        if let en = propBool(props, "enabled") { ndMenuItemSetEnabled(view, en) }
    }
}

func ndConnectEvents(_ view: NSView, _ kind: String, _ nodeID: UInt32) {
    if kind == "Button" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "clicked", payload: .none, action: #selector(EventDispatcher.fireNone(_:)))
    } else if kind == "TextInput" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "changed", payload: .text, action: #selector(EventDispatcher.fireText(_:)))
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "activate", payload: .text, action: #selector(EventDispatcher.fireText(_:)))
    } else if kind == "TextArea" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "changed", payload: .text, action: #selector(EventDispatcher.fireText(_:)))
    } else if kind == "Checkbox" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "toggled", payload: .checked, action: #selector(EventDispatcher.fireChecked(_:)))
    } else if kind == "Radio" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "toggled", payload: .checked, action: #selector(EventDispatcher.fireChecked(_:)))
    } else if kind == "Select" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "selectionChanged", payload: .index, action: #selector(EventDispatcher.fireIndex(_:)))
    } else if kind == "Slider" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "valueChanged", payload: .value, action: #selector(EventDispatcher.fireValue(_:)))
    } else if kind == "ListView" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "rowActivated", payload: .index, action: #selector(EventDispatcher.fireIndex(_:)))
    } else if kind == "SearchInput" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "changed", payload: .text, action: #selector(EventDispatcher.fireText(_:)))
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "activate", payload: .text, action: #selector(EventDispatcher.fireText(_:)))
    } else if kind == "SourceList" {
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "selectionChanged", payload: .index, action: #selector(EventDispatcher.fireIndex(_:)))
        EventDispatcher.shared.wire(view, nodeID: nodeID, name: "rowActivated", payload: .index, action: #selector(EventDispatcher.fireIndex(_:)))
    } else if kind == "MenuItem" {
        ndMenuItemConnect(view, nodeID: nodeID) // M13: NSMenuItem target/action, not EventDispatcher
    }
}

func ndAppendChild(_ parent: NSView, _ parentKind: String, _ child: NSView, _ attachedJson: String) {
    let attached = parseProps(attachedJson)
    let attachedTabLabel = propStr(attached, "tabLabel") ?? ""
    let attachedGridRow = propInt(attached, "gridRow") ?? 0
    let attachedGridColumn = propInt(attached, "gridColumn") ?? 0
    let attachedGridRowSpan = propInt(attached, "gridRowSpan") ?? 1
    let attachedGridColumnSpan = propInt(attached, "gridColumnSpan") ?? 1
    let attachedSlot = propStr(attached, "slot") ?? "content"
    if parentKind == "Window" {
        if ndMenuAttachToWindow(child) { return } // M13: a <menubar> child is app chrome (NSApp.mainMenu), not window content
        let window = parent.window ?? gWindow
        parent.subviews.forEach { $0.removeFromSuperview() }
        if let split = child as? NSSplitView, let controller = ndSplitViewController(for: split), let win = window {
            let ndSavedFrame = win.frame
            win.contentViewController = controller
            win.setFrame(ndSavedFrame, display: true)
        } else {
            if let win = window, win.contentViewController != nil {
                win.contentViewController = nil
                win.contentView = parent
            }
            parent.addSubview(child)
            child.frame = parent.bounds
            child.autoresizingMask = [.width, .height]
        }
    } else if parentKind == "Box" {
        let stack = parent as! NSStackView
        stack.addArrangedSubview(child)
        ndBoxChildAttached(stack, child)
    } else if parentKind == "ScrollView" {
        let sv = parent as! NSScrollView
        let doc = sv.documentView!
        doc.subviews.forEach { $0.removeFromSuperview() }
        child.translatesAutoresizingMaskIntoConstraints = false
        doc.addSubview(child)
        NSLayoutConstraint.activate([
            child.leadingAnchor.constraint(equalTo: doc.leadingAnchor),
            child.trailingAnchor.constraint(equalTo: doc.trailingAnchor),
            child.topAnchor.constraint(equalTo: doc.topAnchor),
            child.bottomAnchor.constraint(equalTo: doc.bottomAnchor),
        ])
    } else if parentKind == "TabView" {
        let tabs = parent as! NSTabView
        let item = NSTabViewItem()
        item.view = child
        item.label = attachedTabLabel
        tabs.addTabViewItem(item)
    } else if parentKind == "Grid" {
        let grid = parent as! NSGridView
        ndGridPlace(grid, child, row: attachedGridRow, column: attachedGridColumn, rowSpan: attachedGridRowSpan, columnSpan: attachedGridColumnSpan)
    } else if parentKind == "SplitView" {
        let split = parent as! NSSplitView
        let controller = ndSplitViewController(for: split)!
        var realChild = child
        if let pane = child as? NDToolbarPaneView {
            ndToolbarPaneAttachedToSplit(pane, split: split, slot: attachedSlot)
            realChild = pane.contentView ?? child
        }
        let vc = ndMakePaneViewController(realChild)
        if attachedSlot == "sidebar" {
            let item = NSSplitViewItem(sidebarWithViewController: vc)
            item.minimumThickness = 180
            if let fraction = splitViewSidebarFraction[ObjectIdentifier(split)] {
                item.preferredThicknessFraction = fraction
            }
            item.canCollapse = true
            item.isCollapsed = splitViewCollapsed[ObjectIdentifier(split)] ?? false
            controller.insertSplitViewItem(item, at: 0)
        } else if attachedSlot == "list" {
            let item = NSSplitViewItem(contentListWithViewController: vc)
            item.minimumThickness = 240
            item.canCollapse = true
            if let fraction = splitViewListFraction[ObjectIdentifier(split)] {
                item.preferredThicknessFraction = fraction
            }
            let insertIndex = controller.splitViewItems.first?.behavior == .sidebar ? 1 : 0
            controller.insertSplitViewItem(item, at: insertIndex)
        } else {
            let item = NSSplitViewItem(viewController: vc)
            item.automaticallyAdjustsSafeAreaInsets = true
            controller.addSplitViewItem(item)
        }
    } else if parentKind == "HeaderBar" {
        ndHeaderBarPack(parent as! NDHeaderBarView, child, slot: attachedSlot)
    } else if parentKind == "ToolbarView" {
        ndToolbarPanePack(parent as! NDToolbarPaneView, child)
    } else if parentKind == "Menubar" {
        ndMenuAppendChild(parent, child)
    } else if parentKind == "Menu" {
        ndMenuAppendChild(parent, child)
    } else {
        FileHandle.standardError.write("ND_WARN append to non-container kind=\(parentKind)\n".data(using: .utf8)!)
    }
}

func ndInsertBefore(_ parent: NSView, _ parentKind: String, _ child: NSView, _ before: NSView?, _ attachedJson: String) {
    // nil `before` degenerates to append everywhere (matches the M4 hand-written contract).
    guard let before = before else { return ndAppendChild(parent, parentKind, child, attachedJson) }
    let attached = parseProps(attachedJson)
    let attachedTabLabel = propStr(attached, "tabLabel") ?? ""
    let attachedGridRow = propInt(attached, "gridRow") ?? 0
    let attachedGridColumn = propInt(attached, "gridColumn") ?? 0
    let attachedGridRowSpan = propInt(attached, "gridRowSpan") ?? 1
    let attachedGridColumnSpan = propInt(attached, "gridColumnSpan") ?? 1
    let attachedSlot = propStr(attached, "slot") ?? "content"
    if parentKind == "Box" {
        let stack = parent as! NSStackView
        if stack.arrangedSubviews.contains(child) { stack.removeArrangedSubview(child) }
        let idx = stack.arrangedSubviews.firstIndex(of: before) ?? stack.arrangedSubviews.count
        stack.insertArrangedSubview(child, at: idx)
        ndBoxChildAttached(stack, child)
    } else if parentKind == "TabView" {
        let tabs = parent as! NSTabView
        let item = NSTabViewItem()
        item.view = child
        item.label = attachedTabLabel
        let idx = tabs.tabViewItems.firstIndex { $0.view === before } ?? tabs.tabViewItems.count
        tabs.insertTabViewItem(item, at: idx)
    } else if parentKind == "Grid" {
        // Grid children are position-addressed; sibling order is irrelevant.
        let grid = parent as! NSGridView
        ndGridPlace(grid, child, row: attachedGridRow, column: attachedGridColumn, rowSpan: attachedGridRowSpan, columnSpan: attachedGridColumnSpan)
    } else if parentKind == "SplitView" {
        let split = parent as! NSSplitView
        let controller = ndSplitViewController(for: split)!
        var realChild = child
        if let pane = child as? NDToolbarPaneView {
            ndToolbarPaneAttachedToSplit(pane, split: split, slot: attachedSlot)
            realChild = pane.contentView ?? child
        }
        let vc = ndMakePaneViewController(realChild)
        if attachedSlot == "sidebar" {
            let item = NSSplitViewItem(sidebarWithViewController: vc)
            item.minimumThickness = 180
            if let fraction = splitViewSidebarFraction[ObjectIdentifier(split)] {
                item.preferredThicknessFraction = fraction
            }
            item.canCollapse = true
            item.isCollapsed = splitViewCollapsed[ObjectIdentifier(split)] ?? false
            controller.insertSplitViewItem(item, at: 0)
        } else if attachedSlot == "list" {
            let item = NSSplitViewItem(contentListWithViewController: vc)
            item.minimumThickness = 240
            item.canCollapse = true
            if let fraction = splitViewListFraction[ObjectIdentifier(split)] {
                item.preferredThicknessFraction = fraction
            }
            let insertIndex = controller.splitViewItems.first?.behavior == .sidebar ? 1 : 0
            controller.insertSplitViewItem(item, at: insertIndex)
        } else {
            let item = NSSplitViewItem(viewController: vc)
            item.automaticallyAdjustsSafeAreaInsets = true
            controller.addSplitViewItem(item)
        }
    } else if parentKind == "HeaderBar" {
        ndHeaderBarPack(parent as! NDHeaderBarView, child, slot: attachedSlot)
    } else if parentKind == "ToolbarView" {
        ndToolbarPanePack(parent as! NDToolbarPaneView, child)
    } else if parentKind == "Menubar" {
        ndMenuAppendChild(parent, child)
    } else if parentKind == "Menu" {
        ndMenuAppendChild(parent, child)
    } else {
        // single-child containers: insertBefore degenerates to appendChild.
        ndAppendChild(parent, parentKind, child, attachedJson)
    }
}

func ndRemoveChild(_ parent: NSView, _ parentKind: String, _ child: NSView) {
    if parentKind == "Window" {
        if ndIsMenuNode(child) { return } // M13: menubar detach is a no-op (mainMenu rebuilt on next change)
        if let split = child as? NSSplitView, let controller = ndSplitViewController(for: split),
           let window = parent.window ?? gWindow, window.contentViewController === controller {
            window.contentViewController = nil
            window.contentView = parent
        } else {
            child.removeFromSuperview()
        }
    } else if parentKind == "Box" {
        let stack = parent as! NSStackView
        stack.removeArrangedSubview(child)
        ndBoxChildDetached(stack, child)
        child.removeFromSuperview()
    } else if parentKind == "ScrollView" {
        let sv = parent as! NSScrollView
        if child.superview === sv.documentView { child.removeFromSuperview() }
    } else if parentKind == "TabView" {
        let tabs = parent as! NSTabView
        if let item = tabs.tabViewItems.first(where: { $0.view === child }) {
            tabs.removeTabViewItem(item)
        }
    } else if parentKind == "Grid" {
        let grid = parent as! NSGridView
        ndGridRemove(grid, child)
    } else if parentKind == "SplitView" {
        let split = parent as! NSSplitView
        let controller = ndSplitViewController(for: split)!
        var realChild = child
        if let pane = child as? NDToolbarPaneView {
            ndToolbarPaneDetachedFromSplit(pane)
            realChild = pane.contentView ?? child
        }
        if let item = controller.splitViewItems.first(where: { $0.viewController.view === realChild || realChild.isDescendant(of: $0.viewController.view) }) {
            controller.removeSplitViewItem(item)
        } else {
            split.removeArrangedSubview(realChild)
            realChild.removeFromSuperview()
        }
    } else if parentKind == "HeaderBar" {
        ndHeaderBarUnpack(parent as! NDHeaderBarView, child)
    } else if parentKind == "ToolbarView" {
        ndToolbarPaneUnpack(parent as! NDToolbarPaneView, child)
    } else if parentKind == "Menubar" {
        ndMenuRemoveChild(parent, child)
    } else if parentKind == "Menu" {
        ndMenuRemoveChild(parent, child)
    } else {
        FileHandle.standardError.write("ND_WARN remove from non-container kind=\(parentKind)\n".data(using: .utf8)!)
    }
}
