#!/usr/bin/env bun
// tools/codegen.ts — reads schema/widgets.json and emits the generated
// TS/JSX intrinsics, Zig widget appliers, docs, and automation meta tables.
// Deterministic: widgets and props are emitted in schema-declaration order.
// Run: `bun tools/codegen.ts`. Never hand-edit the generated files.

import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const HEADER_TS = "// GENERATED by tools/codegen.ts — do not edit\n";
const HEADER_ZIG = "// GENERATED by tools/codegen.ts — do not edit\n";

type PropType = "string" | "int" | "bool" | "enum" | "float" | "stringList";
type AppliesTo = "create" | "createAndUpdate" | "meta";
type PayloadKind = "none" | "text" | "checked" | "value" | "index";

interface Prop {
  name: string;
  type: PropType;
  values?: string[];
  default?: string | number | boolean;
  required?: boolean;
  appliesTo: AppliesTo;
}
interface Event { name: string; ndpName?: string; payload?: PayloadKind }
interface AttachedProp { name: string; type: PropType; values?: string[]; default?: string | number | boolean }
interface Container { childModel: "single" | "multi"; attachedProps?: AttachedProp[] }
interface Widget {
  name: string;
  intrinsic: string;
  container: Container | null;
  stub?: boolean;
  props: Prop[];
  events: Event[];
  automation: { role: string; textFrom: string | null };
}
type StyleKeyKind = "color" | "int" | "bool" | "enum" | "string" | "object" | "spacing";
interface StyleField { kind: StyleKeyKind; css?: string; unit?: string; values?: string[] }
interface StyleKey extends StyleField { fields?: Record<string, StyleField>; target?: "css" | "widget" }
interface StyleDef { keys: Record<string, StyleKey> }
interface Schema { schemaVersion: number; style?: StyleDef; cssClasses?: string[]; widgets: Widget[] }

function tsTypeOf(p: { type: PropType; values?: string[] }): string {
  switch (p.type) {
    case "string": return "string";
    case "int": return "number";
    case "float": return "number";
    case "bool": return "boolean";
    case "stringList": return "string[]";
    case "enum": return (p.values ?? []).map((v) => JSON.stringify(v)).join(" | ");
  }
}

function tsHandlerType(e: Event): string {
  switch (e.payload ?? "none") {
    case "none": return "() => void";
    case "text": return "(e: { text: string }) => void";
    case "checked": return "(e: { checked: boolean }) => void";
    case "value": return "(e: { value: number }) => void";
    case "index": return "(e: { index: number }) => void";
  }
}

/** Union of all containers' attachedProps, deduped by name, schema order.
 *  Two containers may declare an attached prop with the same name but a
 *  different domain (e.g. SplitView's `slot` is "sidebar"|"content", while
 *  HeaderBar's is "start"|"end") — the wire representation is an opaque
 *  string either way (protocol.Attached.slot: ?[]const u8), so the merged
 *  TS type just unions the enum values rather than throwing. */
function collectAttachedProps(s: Schema): AttachedProp[] {
  const seen = new Map<string, AttachedProp>();
  const out: AttachedProp[] = [];
  for (const w of s.widgets) {
    for (const ap of w.container?.attachedProps ?? []) {
      const existing = seen.get(ap.name);
      if (!existing) {
        seen.set(ap.name, ap);
        out.push(ap);
      } else if (existing.type === "enum" && ap.type === "enum") {
        const merged = new Set([...(existing.values ?? []), ...(ap.values ?? [])]);
        existing.values = [...merged];
      } else if (existing.type !== ap.type) {
        throw new Error(`attached prop ${JSON.stringify(ap.name)} redeclared with incompatible type (${existing.type} vs ${ap.type})`);
      }
    }
  }
  return out;
}

function zigLit(p: Prop): string {
  if (p.type === "int") return String(p.default ?? 0);
  if (p.type === "bool") return String(p.default ?? false);
  return JSON.stringify(String(p.default ?? "")); // string/enum default as a Zig string literal
}

// ---- style: shared StyleProp TS type + runtime valid-key manifest ----
function tsStyleField(f: StyleField): string {
  switch (f.kind) {
    case "color": return "string";
    case "string": return "string";
    case "int": return "number";
    case "bool": return "boolean";
    case "enum": return (f.values ?? []).map((v) => JSON.stringify(v)).join(" | ");
    case "spacing": return "number | { top?: number; right?: number; bottom?: number; left?: number }";
    case "object": return "{ " + Object.entries(f.fields ?? {}).map(([k, v]) => `${k}?: ${tsStyleField(v)}`).join("; ") + " }";
  }
}

function genStyleProp(s: Schema): string {
  const style = s.style;
  if (!style) return "export type StyleProp = Record<string, never>;\n";
  let out = "export interface StyleProp {\n";
  for (const [k, def] of Object.entries(style.keys)) out += `  ${k}?: ${tsStyleField(def)};\n`;
  out += "}\n";
  // Runtime manifest the validator consumes (nested keys included).
  out += "export const styleKeySpec: Record<string, string[] | null> = {\n";
  for (const [k, def] of Object.entries(style.keys)) {
    const nested = def.kind === "object" ? Object.keys(def.fields ?? {}) : null;
    out += `  ${JSON.stringify(k)}: ${nested ? JSON.stringify(nested) : "null"},\n`;
  }
  out += "};\n";
  return out;
}

function genCssClassSpec(s: Schema): string {
  const classes = s.cssClasses ?? [];
  return `export const cssClassSpec: string[] = ${JSON.stringify(classes)};\n`;
}

function genZigCssClassSpec(s: Schema): string {
  const classes = s.cssClasses ?? [];
  let out = "pub const css_class_spec = [_][]const u8{";
  out += classes.map((c) => JSON.stringify(c)).join(", ");
  out += "};\n";
  return out;
}

// ---- artifact (a): TS/JSX intrinsics ----
function genIntrinsics(s: Schema): string {
  let out = HEADER_TS;
  out += 'import type { ReactNode } from "react";\n\n';
  out += "export { jsx, jsxs, Fragment } from \"react/jsx-runtime\";\n\n";
  out += "export type WidgetName = " + s.widgets.map((w) => JSON.stringify(w.name)).join(" | ") + ";\n";
  out += "export type WidgetType = " + s.widgets.map((w) => JSON.stringify(w.intrinsic)).join(" | ") + ";\n\n";
  out += genStyleProp(s);
  out += genCssClassSpec(s);
  out += "\n";
  out += "export namespace JSX {\n";
  out += "  export interface IntrinsicElements {\n";
  const attached = collectAttachedProps(s);
  for (const w of s.widgets) {
    const fields: string[] = [];
    for (const p of w.props) fields.push(`${p.name}?: ${tsTypeOf(p)}`);
    for (const e of w.events) fields.push(`${e.ndpName ?? e.name}?: ${tsHandlerType(e)}`);
    for (const ap of attached) fields.push(`${ap.name}?: ${tsTypeOf(ap)}`);
    fields.push("style?: StyleProp");
    fields.push("cssClasses?: string[]");
    fields.push("key?: string | number | null");
    fields.push("children?: ReactNode");
    out += `    ${w.intrinsic}: { ${fields.join("; ")} };\n`;
  }
  out += "  }\n";
  out += "  export type Element = ReactNode;\n";
  out += "  export interface IntrinsicAttributes {\n    key?: string | number | null;\n  }\n";
  out += "  export interface ElementChildrenAttribute {\n    children: {};\n  }\n";
  out += "}\n";
  return out;
}

// ---- artifact (d): automation role/textFrom meta ----
function genSchemaMeta(s: Schema): string {
  let out = HEADER_TS;
  out += "export interface WidgetMeta {\n  role: string;\n  textFrom: string | null;\n  childModel: \"single\" | \"multi\" | null;\n}\n\n";
  out += "export const widgetMeta: Record<string, WidgetMeta> = {\n";
  for (const w of s.widgets) {
    const cm = w.container ? JSON.stringify(w.container.childModel) : "null";
    out += `  ${JSON.stringify(w.name)}: { role: ${JSON.stringify(w.automation.role)}, textFrom: ${w.automation.textFrom === null ? "null" : JSON.stringify(w.automation.textFrom)}, childModel: ${cm} },\n`;
  }
  out += "};\n";

  out += "\nexport const intrinsicToName: Record<string, string> = {\n";
  for (const w of s.widgets) out += `  ${JSON.stringify(w.intrinsic)}: ${JSON.stringify(w.name)},\n`;
  out += "};\n";

  out += "\nexport interface WidgetEvent {\n  name: string;\n  handler: string;\n  payload: \"none\" | \"text\" | \"checked\" | \"value\" | \"index\";\n}\n";
  out += "export const widgetEvents: Record<string, WidgetEvent[]> = {\n";
  for (const w of s.widgets) {
    const evs = w.events.map((e) =>
      `{ name: ${JSON.stringify(e.name)}, handler: ${JSON.stringify(e.ndpName ?? e.name)}, payload: ${JSON.stringify(e.payload ?? "none")} }`);
    out += `  ${JSON.stringify(w.intrinsic)}: [${evs.join(", ")}],\n`;
  }
  out += "};\n";

  out += "\nexport const handlerPropNames: Record<string, string[]> = {\n";
  for (const w of s.widgets) {
    out += `  ${JSON.stringify(w.intrinsic)}: [${w.events.map((e) => JSON.stringify(e.ndpName ?? e.name)).join(", ")}],\n`;
  }
  out += "};\n";
  return out;
}

// ---- artifact (b): Zig widget appliers ----
const ZIG_HELPERS = `fn propStr(props: ?std.json.Value, key: []const u8) ?[]const u8 {
    const v = props orelse return null;
    if (v != .object) return null;
    const field = v.object.get(key) orelse return null;
    return switch (field) {
        .string => field.string,
        else => null,
    };
}

fn propInt(props: ?std.json.Value, key: []const u8) ?i64 {
    const v = props orelse return null;
    if (v != .object) return null;
    const field = v.object.get(key) orelse return null;
    return switch (field) {
        .integer => field.integer,
        else => null,
    };
}

fn propFloat(props: ?std.json.Value, key: []const u8) ?f64 {
    const v = props orelse return null;
    if (v != .object) return null;
    const field = v.object.get(key) orelse return null;
    return switch (field) {
        .float => field.float,
        .integer => @floatFromInt(field.integer),
        else => null,
    };
}

fn propBool(props: ?std.json.Value, key: []const u8) ?bool {
    const v = props orelse return null;
    if (v != .object) return null;
    const field = v.object.get(key) orelse return null;
    return switch (field) {
        .bool => field.bool,
        else => null,
    };
}

fn propArray(props: ?std.json.Value, key: []const u8) ?std.json.Array {
    const v = props orelse return null;
    if (v != .object) return null;
    const field = v.object.get(key) orelse return null;
    return switch (field) {
        .array => field.array,
        else => null,
    };
}

fn asObject(ptr: anytype) *gobject.Object {
    return @ptrCast(@alignCast(ptr));
}

/// Builds a NULL-terminated strv (\`?[*]const [*:0]const u8\`) from a JSON
/// string array in ONE bulk allocation, for bulk GtkStringList construction
/// (gtk_string_list_new/splice both deep-copy the strings, so the returned
/// buffer only needs to live until that call returns — free it with
/// \`std.heap.page_allocator.free(buf)\`). O(n), not the O(n^2) per-item
/// StringList.append loop.
fn buildStrv(arr: ?std.json.Array, dupeZ: *const fn ([]const u8) [:0]const u8) []?[*:0]const u8 {
    const items = arr orelse std.json.Array.init(std.heap.page_allocator);
    const buf = std.heap.page_allocator.alloc(?[*:0]const u8, items.items.len + 1) catch @panic("OOM building strv");
    var n: usize = 0;
    for (items.items) |item| {
        if (item != .string) continue;
        buf[n] = dupeZ(item.string);
        n += 1;
    }
    buf[n] = null;
    return buf[0 .. n + 1];
}
`;

const ZIG_EVENT_STATE = `// ---- event wiring state (installed once by gtk_backend.setEventSink via
// initEvents, BEFORE the NDP socket accepts — so before any widget exists) ----
pub const EmitFn = *const fn (node_id: u32, name: []const u8, payload: protocol.EventPayload) void;
var emit: ?EmitFn = null;
var events_gpa: std.mem.Allocator = undefined;
var events_ready = false;
/// GObject ptr -> the ONE suppressible (change-echo) handler id on it.
var suppress_map: std.AutoHashMapUnmanaged(usize, c_ulong) = .empty;
/// Radio group name -> first CheckButton in the group (lives for process lifetime).
var radio_groups: std.StringHashMapUnmanaged(*gtk.CheckButton) = .empty;

pub fn initEvents(gpa: std.mem.Allocator, emit_fn: EmitFn) void {
    events_gpa = gpa;
    emit = emit_fn;
    events_ready = true;
}

fn noteSuppressible(obj: *gobject.Object, handler_id: c_ulong) void {
    suppress_map.put(events_gpa, @intFromPtr(obj), handler_id) catch {};
}

fn blockEcho(obj: *gobject.Object) void {
    if (suppress_map.get(@intFromPtr(obj))) |hid| gobject.signalHandlerBlock(obj, hid);
}

fn unblockEcho(obj: *gobject.Object) void {
    if (suppress_map.get(@intFromPtr(obj))) |hid| gobject.signalHandlerUnblock(obj, hid);
}
`;

function genZig(s: Schema): string {
  let out = HEADER_ZIG;
  out += "const std = @import(\"std\");\n";
  out += "const gtk = @import(\"gtk\");\n";
  out += "const gio = @import(\"gio\");\n";
  out += "const glib = @import(\"glib\");\n";
  out += "const gobject = @import(\"gobject\");\n";
  out += "const adw = @import(\"adw\");\n";
  out += "const protocol = @import(\"../protocol.zig\");\n\n";
  out += ZIG_HELPERS;
  out += "\n";
  out += ZIG_EVENT_STATE;
  out += "\n";
  out += "/// The GTK create dispatcher. `dupeZ` turns a wire string into a NUL-\n";
  out += "/// terminated GTK string using the backend arena (passed by the caller).\n";
  out += "pub fn create(\n";
  out += "    app: *gtk.Application,\n";
  out += "    kind: []const u8,\n";
  out += "    props: ?std.json.Value,\n";
  out += "    dupeZ: *const fn ([]const u8) [:0]const u8,\n";
  out += "    the_window: *?*gtk.Window,\n";
  out += ") !*gtk.Widget {\n";
  for (let i = 0; i < s.widgets.length; i++) {
    const w = s.widgets[i]!;
    const kw = i === 0 ? "if" : "} else if";
    out += `    ${kw} (std.mem.eql(u8, kind, ${JSON.stringify(w.name)})) {\n`;
    out += genZigCreateBody(w);
  }
  out += "    }\n";
  out += "    std.debug.print(\"ND_WARN unknown widget kind={s}\\n\", .{kind});\n";
  out += "    return error.UnknownWidget;\n";
  out += "}\n\n";
  out += "/// The GTK update dispatcher for createAndUpdate props.\n";
  out += "pub fn applyProps(widget: *gtk.Widget, kind: []const u8, props: ?std.json.Value, dupeZ: *const fn ([]const u8) [:0]const u8) void {\n";
  let firstApply = true;
  for (const w of s.widgets) {
    const updProps = w.props.filter((p) => p.appliesTo === "createAndUpdate");
    if (updProps.length === 0) continue;
    const kw = firstApply ? "if" : "} else if";
    firstApply = false;
    out += `    ${kw} (std.mem.eql(u8, kind, ${JSON.stringify(w.name)})) {\n`;
    out += genZigApplyBody(w, updProps);
  }
  if (!firstApply) out += "    }\n";
  out += "}\n\n";
  out += genZigEvents(s);
  out += genZigStructural(s);
  out += genZigStyleTable(s);
  out += genZigCssClassSpec(s);
  return out;
}

/// Data-only style-key tables `src/style.zig` walks to compile any `style`
/// object with zero per-key Zig code (D6's spirit for the style surface).
function genZigStyleTable(s: Schema): string {
  const style = s.style;
  if (!style) return "pub const style_keys = [_]StyleKeyDef{};\n";
  let out = "\npub const StyleTarget = enum { css, widget };\n";
  out += "pub const StyleKeyDef = struct { name: []const u8, css: ?[]const u8, target: StyleTarget, kind: []const u8, unit: ?[]const u8 };\n";
  out += "pub const style_keys = [_]StyleKeyDef{\n";
  for (const [k, def] of Object.entries(style.keys)) {
    const target = def.target === "widget" ? ".widget" : ".css";
    const css = def.css ? JSON.stringify(def.css) : "null";
    const unit = def.unit ? JSON.stringify(def.unit) : "null";
    out += `    .{ .name = ${JSON.stringify(k)}, .css = ${css}, .target = ${target}, .kind = ${JSON.stringify(def.kind)}, .unit = ${unit} },\n`;
  }
  out += "};\n";
  // Nested object/border/font sub-fields, flattened for the compiler.
  out += "pub const StyleSubDef = struct { parent: []const u8, name: []const u8, css: []const u8, kind: []const u8, unit: ?[]const u8 };\n";
  out += "pub const style_subkeys = [_]StyleSubDef{\n";
  for (const [k, def] of Object.entries(style.keys)) {
    if (def.kind !== "object") continue;
    for (const [sk, sf] of Object.entries(def.fields ?? {})) {
      const unit = sf.unit ? JSON.stringify(sf.unit) : "null";
      out += `    .{ .parent = ${JSON.stringify(k)}, .name = ${JSON.stringify(sk)}, .css = ${JSON.stringify(sf.css ?? sk)}, .kind = ${JSON.stringify(sf.kind)}, .unit = ${unit} },\n`;
    }
  }
  out += "};\n";
  return out;
}

function dflt(w: Widget, prop: string): string {
  const p = w.props.find((x) => x.name === prop)!;
  return String(p.default);
}
function zigDefaultStr(w: Widget, prop: string): string {
  const p = w.props.find((x) => x.name === prop)!;
  return JSON.stringify(String(p.default ?? ""));
}

function genZigCreateBody(w: Widget): string {
  let out = "";
  if (w.name === "Window") {
    out += "        const window = adw.ApplicationWindow.new(app);\n";
    out += "        const win = window.as(gtk.Window);\n";
    out += "        the_window.* = win;\n";
    out += "        if (propStr(props, \"title\")) |t| gtk.Window.setTitle(win, dupeZ(t));\n";
    out += `        const w: c_int = @intCast(propInt(props, "defaultWidth") orelse ${dflt(w, "defaultWidth")});\n`;
    out += `        const h: c_int = @intCast(propInt(props, "defaultHeight") orelse ${dflt(w, "defaultHeight")});\n`;
    out += "        gtk.Window.setDefaultSize(win, w, h);\n";
    out += "        gtk.Window.present(win);\n";
    out += "        return window.as(gtk.Widget);\n";
  } else if (w.name === "Box") {
    out += "        const vertical = if (propStr(props, \"orientation\")) |o| std.mem.eql(u8, o, \"vertical\") else true;\n";
    out += "        const orientation: gtk.Orientation = if (vertical) .vertical else .horizontal;\n";
    out += `        const spacing: c_int = @intCast(propInt(props, "spacing") orelse ${dflt(w, "spacing")});\n`;
    out += "        const box = gtk.Box.new(orientation, spacing);\n";
    out += "        return box.as(gtk.Widget);\n";
  } else if (w.name === "Label") {
    out += `        const text = propStr(props, "text") orelse ${zigDefaultStr(w, "text")};\n`;
    out += "        const label = gtk.Label.new(dupeZ(text));\n";
    out += "        return label.as(gtk.Widget);\n";
  } else if (w.name === "Button") {
    out += `        const lbl = propStr(props, "label") orelse ${zigDefaultStr(w, "label")};\n`;
    out += "        const button = gtk.Button.newWithLabel(dupeZ(lbl));\n";
    out += "        return button.as(gtk.Widget);\n";
  } else if (w.name === "TextInput") {
    out += "        const entry = gtk.Entry.new();\n";
    out += "        const editable = entry.as(gtk.Editable);\n";
    out += "        if (propStr(props, \"text\")) |t| { if (t.len > 0) gtk.Editable.setText(editable, dupeZ(t)); }\n";
    out += "        if (propStr(props, \"placeholder\")) |p| gtk.Entry.setPlaceholderText(entry, dupeZ(p));\n";
    out += "        if (propBool(props, \"editable\")) |e| gtk.Editable.setEditable(editable, @intFromBool(e));\n";
    out += "        return entry.as(gtk.Widget);\n";
  } else if (w.name === "TextArea") {
    out += "        const view = gtk.TextView.new();\n";
    out += "        const buf = gtk.TextView.getBuffer(view);\n";
    out += "        if (propStr(props, \"text\")) |t| { if (t.len > 0) gtk.TextBuffer.setText(buf, dupeZ(t), -1); }\n";
    out += "        if (propInt(props, \"minContentHeight\")) |h| { if (h > 0) gtk.Widget.setSizeRequest(view.as(gtk.Widget), -1, @intCast(h)); }\n";
    out += "        return view.as(gtk.Widget);\n";
  } else if (w.name === "Checkbox") {
    out += `        const cb = gtk.CheckButton.newWithLabel(dupeZ(propStr(props, "label") orelse ""));\n`;
    out += "        if (propBool(props, \"checked\") orelse false) gtk.CheckButton.setActive(cb, 1);\n";
    out += "        return cb.as(gtk.Widget);\n";
  } else if (w.name === "Radio") {
    out += `        const cb = gtk.CheckButton.newWithLabel(dupeZ(propStr(props, "label") orelse ""));\n`;
    out += "        if (propStr(props, \"group\")) |g| {\n";
    out += "            std.debug.assert(events_ready); // initEvents runs before any create (runtime.zig startup order)\n";
    out += "            if (radio_groups.get(g)) |first| {\n";
    out += "                gtk.CheckButton.setGroup(cb, first);\n";
    out += "            } else {\n";
    out += "                const key = events_gpa.dupe(u8, g) catch g;\n";
    out += "                radio_groups.put(events_gpa, key, cb) catch {};\n";
    out += "            }\n";
    out += "        } else {\n";
    out += "            std.debug.print(\"ND_WARN Radio without group prop\\n\", .{});\n";
    out += "        }\n";
    out += "        if (propBool(props, \"checked\") orelse false) gtk.CheckButton.setActive(cb, 1);\n";
    out += "        return cb.as(gtk.Widget);\n";
  } else if (w.name === "Select") {
    out += "        const sl = gtk.StringList.new(null);\n";
    out += "        if (propArray(props, \"options\")) |arr| {\n";
    out += "            for (arr.items) |item| {\n";
    out += "                if (item == .string) gtk.StringList.append(sl, dupeZ(item.string));\n";
    out += "            }\n";
    out += "        }\n";
    out += "        const dd = gtk.DropDown.new(sl.as(gio.ListModel), null); // transfer-full: DropDown owns the model\n";
    out += `        const idx = propInt(props, "selectedIndex") orelse ${dflt(w, "selectedIndex")};\n`;
    out += "        if (idx > 0) gtk.DropDown.setSelected(dd, @intCast(idx));\n";
    out += "        return dd.as(gtk.Widget);\n";
  } else if (w.name === "Slider") {
    out += `        const min = propFloat(props, "min") orelse ${dflt(w, "min")};\n`;
    out += `        const max = propFloat(props, "max") orelse ${dflt(w, "max")};\n`;
    out += `        const step = propFloat(props, "step") orelse ${dflt(w, "step")};\n`;
    out += "        const vertical = if (propStr(props, \"orientation\")) |o| std.mem.eql(u8, o, \"vertical\") else false;\n";
    out += "        const scale = gtk.Scale.newWithRange(if (vertical) .vertical else .horizontal, min, max, step);\n";
    out += `        gtk.Range.setValue(scale.as(gtk.Range), propFloat(props, "value") orelse ${dflt(w, "value")});\n`;
    out += "        return scale.as(gtk.Widget);\n";
  } else if (w.name === "ProgressBar") {
    out += "        const pb = gtk.ProgressBar.new();\n";
    out += "        if (propFloat(props, \"fraction\")) |f| gtk.ProgressBar.setFraction(pb, f);\n";
    out += "        return pb.as(gtk.Widget);\n";
  } else if (w.name === "Image") {
    out += "        const img = gtk.Image.new();\n";
    out += "        if (propStr(props, \"path\")) |p| {\n";
    out += "            gtk.Image.setFromFile(img, dupeZ(p));\n";
    out += "        } else if (propStr(props, \"iconName\")) |n| {\n";
    out += "            gtk.Image.setFromIconName(img, dupeZ(n));\n";
    out += "        }\n";
    out += "        return img.as(gtk.Widget);\n";
  } else if (w.name === "ScrollView") {
    out += "        const sw = gtk.ScrolledWindow.new();\n";
    out += "        if (propInt(props, \"minContentHeight\")) |h| { if (h > 0) gtk.ScrolledWindow.setMinContentHeight(sw, @intCast(h)); }\n";
    out += "        return sw.as(gtk.Widget);\n";
  } else if (w.name === "Separator") {
    out += "        const vertical = if (propStr(props, \"orientation\")) |o| std.mem.eql(u8, o, \"vertical\") else false;\n";
    out += "        const sep = gtk.Separator.new(if (vertical) .vertical else .horizontal);\n";
    out += "        return sep.as(gtk.Widget);\n";
  } else if (w.name === "Spinner") {
    out += "        const sp = gtk.Spinner.new();\n";
    out += "        if (propBool(props, \"spinning\") orelse true) gtk.Spinner.setSpinning(sp, 1);\n";
    out += "        return sp.as(gtk.Widget);\n";
  } else if (w.name === "TabView") {
    out += "        // selectedIndex is ignored at create: pages attach afterwards (M5b-D4).\n";
    out += "        const nb = gtk.Notebook.new();\n";
    out += "        return nb.as(gtk.Widget);\n";
  } else if (w.name === "Grid") {
    out += "        const grid = gtk.Grid.new();\n";
    out += "        return grid.as(gtk.Widget);\n";
  } else if (w.name === "ListView") {
    out += "        const strv = buildStrv(propArray(props, \"items\"), dupeZ); // O(n) bulk build, not per-item append\n";
    out += "        defer std.heap.page_allocator.free(strv);\n";
    out += "        const model = gtk.StringList.new(@ptrCast(strv.ptr));\n";
    out += "        const selection = gtk.SingleSelection.new(model.as(gio.ListModel)); // transfer-full: selection owns model\n";
    out += `        const sel_idx = propInt(props, "selectedIndex") orelse ${dflt(w, "selectedIndex")};\n`;
    out += "        if (sel_idx >= 0) gtk.SingleSelection.setSelected(selection, @intCast(sel_idx));\n";
    out += "        const factory = gtk.SignalListItemFactory.new();\n";
    out += "        _ = gobject.signalConnectData(asObject(factory), \"setup\", @ptrCast(&lvSetup), null, null, .{});\n";
    out += "        _ = gobject.signalConnectData(asObject(factory), \"bind\", @ptrCast(&lvBind), null, null, .{});\n";
    out += "        const list = gtk.ListView.new(selection.as(gtk.SelectionModel), factory.as(gtk.ListItemFactory)); // transfer-full: list owns selection+factory\n";
    out += "        const sw = gtk.ScrolledWindow.new(); // M5c-D3: ListView needs a scroller\n";
    out += "        gtk.ScrolledWindow.setChild(sw, list.as(gtk.Widget));\n";
    out += "        return sw.as(gtk.Widget);\n";
  } else if (w.name === "WebView") {
    out += "        std.debug.print(\"ND_WARN WebView is a v1 stub (no webkitgtk); rendering placeholder label\\n\", .{});\n";
    out += "        const label = gtk.Label.new(\"WebView unavailable (v1 stub)\");\n";
    out += "        return label.as(gtk.Widget);\n";
  } else if (w.name === "SplitView") {
    out += "        const sv = adw.OverlaySplitView.new();\n";
    out += "        if (propFloat(props, \"sidebarWidth\")) |sw| { if (sw > 0) adw.OverlaySplitView.setSidebarWidthFraction(sv, sw); }\n";
    out += "        if (propBool(props, \"collapsed\")) |c| adw.OverlaySplitView.setCollapsed(sv, @intFromBool(c));\n";
    out += "        return sv.as(gtk.Widget);\n";
  } else if (w.name === "HeaderBar") {
    out += "        const hb = adw.HeaderBar.new();\n";
    out += "        if (propStr(props, \"title\")) |t| {\n";
    out += "            if (t.len > 0) {\n";
    out += "                const wt = adw.WindowTitle.new(dupeZ(t), \"\");\n";
    out += "                adw.HeaderBar.setTitleWidget(hb, wt.as(gtk.Widget));\n";
    out += "            }\n";
    out += "        }\n";
    out += "        return hb.as(gtk.Widget);\n";
  } else if (w.name === "ToolbarView") {
    out += "        const tv = adw.ToolbarView.new();\n";
    out += "        return tv.as(gtk.Widget);\n";
  } else {
    throw new Error(`no create template for widget ${w.name} — add one when introducing it (M5b)`);
  }
  return out;
}

function genZigApplyBody(w: Widget, updProps: Prop[]): string {
  let out = "";
  for (const p of updProps) {
    if (w.name === "Box" && p.name === "spacing") {
      out += "        if (propInt(props, \"spacing\")) |s| {\n";
      out += "            const box: *gtk.Box = @ptrCast(@alignCast(widget));\n";
      out += "            gtk.Box.setSpacing(box, @intCast(s));\n";
      out += "        }\n";
    } else if (w.name === "Window" && p.name === "title") {
      out += "        if (propStr(props, \"title\")) |t| {\n";
      out += "            const win: *gtk.Window = @ptrCast(@alignCast(widget));\n";
      out += "            gtk.Window.setTitle(win, dupeZ(t));\n";
      out += "        }\n";
    } else if (w.name === "TextInput" && p.name === "text") {
      out += "        if (propStr(props, \"text\")) |t| {\n";
      out += "            const editable = @as(*gtk.Entry, @ptrCast(@alignCast(widget))).as(gtk.Editable);\n";
      out += "            const cur = std.mem.span(gtk.Editable.getText(editable));\n";
      out += "            if (!std.mem.eql(u8, cur, t)) {\n";
      out += "                blockEcho(asObject(widget));\n";
      out += "                gtk.Editable.setText(editable, dupeZ(t));\n";
      out += "                unblockEcho(asObject(widget));\n";
      out += "            }\n";
      out += "        }\n";
    } else if (w.name === "TextInput" && p.name === "placeholder") {
      out += "        if (propStr(props, \"placeholder\")) |p_| gtk.Entry.setPlaceholderText(@ptrCast(@alignCast(widget)), dupeZ(p_));\n";
    } else if (w.name === "TextInput" && p.name === "editable") {
      out += "        if (propBool(props, \"editable\")) |e| gtk.Editable.setEditable(@as(*gtk.Entry, @ptrCast(@alignCast(widget))).as(gtk.Editable), @intFromBool(e));\n";
    } else if (w.name === "TextArea" && p.name === "text") {
      out += "        if (propStr(props, \"text\")) |t| {\n";
      out += "            const view: *gtk.TextView = @ptrCast(@alignCast(widget));\n";
      out += "            const buf = gtk.TextView.getBuffer(view);\n";
      out += "            var s_it: gtk.TextIter = undefined;\n";
      out += "            var e_it: gtk.TextIter = undefined;\n";
      out += "            gtk.TextBuffer.getStartIter(buf, &s_it);\n";
      out += "            gtk.TextBuffer.getEndIter(buf, &e_it);\n";
      out += "            const cur = gtk.TextBuffer.getText(buf, &s_it, &e_it, 0);\n";
      out += "            defer glib.free(@ptrCast(cur));\n";
      out += "            if (!std.mem.eql(u8, std.mem.span(cur), t)) {\n";
      out += "                blockEcho(asObject(buf));\n";
      out += "                gtk.TextBuffer.setText(buf, dupeZ(t), -1);\n";
      out += "                unblockEcho(asObject(buf));\n";
      out += "            }\n";
      out += "        }\n";
    } else if ((w.name === "Checkbox" || w.name === "Radio") && p.name === "checked") {
      out += "        if (propBool(props, \"checked\")) |c| {\n";
      out += "            const cb: *gtk.CheckButton = @ptrCast(@alignCast(widget));\n";
      out += "            if ((gtk.CheckButton.getActive(cb) != 0) != c) {\n";
      out += "                blockEcho(asObject(widget));\n";
      out += "                gtk.CheckButton.setActive(cb, @intFromBool(c));\n";
      out += "                unblockEcho(asObject(widget));\n";
      out += "            }\n";
      out += "        }\n";
    } else if ((w.name === "Checkbox" || w.name === "Radio") && p.name === "label") {
      out += "        if (propStr(props, \"label\")) |l| gtk.CheckButton.setLabel(@ptrCast(@alignCast(widget)), dupeZ(l));\n";
    } else if (w.name === "Select" && p.name === "selectedIndex") {
      out += "        if (propInt(props, \"selectedIndex\")) |idx| {\n";
      out += "            const dd: *gtk.DropDown = @ptrCast(@alignCast(widget));\n";
      out += "            if (gtk.DropDown.getSelected(dd) != @as(c_uint, @intCast(idx))) {\n";
      out += "                blockEcho(asObject(widget));\n";
      out += "                gtk.DropDown.setSelected(dd, @intCast(idx));\n";
      out += "                unblockEcho(asObject(widget));\n";
      out += "            }\n";
      out += "        }\n";
    } else if (w.name === "Slider" && p.name === "value") {
      out += "        if (propFloat(props, \"value\")) |v| {\n";
      out += "            const range = @as(*gtk.Scale, @ptrCast(@alignCast(widget))).as(gtk.Range);\n";
      out += "            if (@abs(gtk.Range.getValue(range) - v) > 1e-9) {\n";
      out += "                blockEcho(asObject(widget));\n";
      out += "                gtk.Range.setValue(range, v);\n";
      out += "                unblockEcho(asObject(widget));\n";
      out += "            }\n";
      out += "        }\n";
    } else if (w.name === "ProgressBar" && p.name === "fraction") {
      out += "        if (propFloat(props, \"fraction\")) |f| gtk.ProgressBar.setFraction(@ptrCast(@alignCast(widget)), f);\n";
    } else if (w.name === "Image" && p.name === "path") {
      out += "        if (propStr(props, \"path\")) |p_| gtk.Image.setFromFile(@ptrCast(@alignCast(widget)), dupeZ(p_));\n";
    } else if (w.name === "Image" && p.name === "iconName") {
      out += "        if (propStr(props, \"iconName\")) |n| gtk.Image.setFromIconName(@ptrCast(@alignCast(widget)), dupeZ(n));\n";
    } else if (w.name === "Spinner" && p.name === "spinning") {
      out += "        if (propBool(props, \"spinning\")) |sp| gtk.Spinner.setSpinning(@ptrCast(@alignCast(widget)), @intFromBool(sp));\n";
    } else if (w.name === "TabView" && p.name === "selectedIndex") {
      out += "        if (propInt(props, \"selectedIndex\")) |idx| gtk.Notebook.setCurrentPage(@ptrCast(@alignCast(widget)), @intCast(idx));\n";
    } else if (w.name === "ListView" && p.name === "items") {
      out += "        {\n";
      out += "            const sw: *gtk.ScrolledWindow = @ptrCast(@alignCast(widget));\n";
      out += "            const list: *gtk.ListView = @ptrCast(@alignCast(gtk.ScrolledWindow.getChild(sw).?));\n";
      out += "            const selection: *gtk.SingleSelection = @ptrCast(@alignCast(gtk.ListView.getModel(list).?));\n";
      out += "            const model: *gtk.StringList = @ptrCast(@alignCast(gtk.SingleSelection.getModel(selection).?));\n";
      out += "            const n_old = gio.ListModel.getNItems(model.as(gio.ListModel));\n";
      out += "            const strv = buildStrv(propArray(props, \"items\"), dupeZ); // O(n) bulk build, not per-item append\n";
      out += "            defer std.heap.page_allocator.free(strv);\n";
      out += "            gtk.StringList.splice(model, 0, n_old, @ptrCast(strv.ptr)); // one call: replace-all\n";
      out += "        }\n";
    } else if (w.name === "ListView" && p.name === "selectedIndex") {
      out += "        if (propInt(props, \"selectedIndex\")) |idx| {\n";
      out += "            const sw: *gtk.ScrolledWindow = @ptrCast(@alignCast(widget));\n";
      out += "            const list: *gtk.ListView = @ptrCast(@alignCast(gtk.ScrolledWindow.getChild(sw).?));\n";
      out += "            const selection: *gtk.SingleSelection = @ptrCast(@alignCast(gtk.ListView.getModel(list).?));\n";
      out += "            if (idx >= 0) gtk.SingleSelection.setSelected(selection, @intCast(idx));\n";
      out += "        }\n";
    } else if (w.name === "SplitView" && p.name === "collapsed") {
      out += "        if (propBool(props, \"collapsed\")) |c| adw.OverlaySplitView.setCollapsed(@ptrCast(@alignCast(widget)), @intFromBool(c));\n";
    } else {
      throw new Error(`no applyProps template for ${w.name}.${p.name} — add one when introducing it (M5b)`);
    }
  }
  return out;
}

interface SignalTemplate { signal: string; target: "widget" | "buffer" | "listview-inner"; cb: string; suppress: boolean }
const SIGNALS: Record<string, SignalTemplate> = {
  "Button.clicked":          { signal: "clicked",          target: "widget", cb: "cbClicked",          suppress: false },
  "TextInput.changed":       { signal: "changed",          target: "widget", cb: "cbEditableChanged",  suppress: true },
  "TextInput.activate":      { signal: "activate",         target: "widget", cb: "cbEntryActivate",    suppress: false },
  "TextArea.changed":        { signal: "changed",          target: "buffer", cb: "cbBufferChanged",    suppress: true },
  "Checkbox.toggled":        { signal: "toggled",          target: "widget", cb: "cbCheckToggled",     suppress: true },
  "Radio.toggled":           { signal: "toggled",          target: "widget", cb: "cbCheckToggled",     suppress: true },
  "Select.selectionChanged": { signal: "notify::selected", target: "widget", cb: "cbDropDownSelected", suppress: true },
  "Slider.valueChanged":     { signal: "value-changed",    target: "widget", cb: "cbScaleValueChanged", suppress: true },
  "ListView.rowActivated":   { signal: "activate",         target: "listview-inner", cb: "cbListActivate", suppress: false },
};

const CALLBACK_BODIES: Record<string, string> = {
  cbClicked: `fn cbClicked(_: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    if (emit) |f| f(node_id, "clicked", .{});
}
`,
  cbEditableChanged: `fn cbEditableChanged(obj: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const editable: *gtk.Editable = @ptrCast(@alignCast(obj));
    const text = std.mem.span(gtk.Editable.getText(editable));
    if (emit) |f| f(node_id, "changed", .{ .text = text });
}
`,
  cbEntryActivate: `fn cbEntryActivate(obj: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const editable: *gtk.Editable = @ptrCast(@alignCast(obj));
    const text = std.mem.span(gtk.Editable.getText(editable));
    if (emit) |f| f(node_id, "activate", .{ .text = text });
}
`,
  cbBufferChanged: `fn cbBufferChanged(obj: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const buf: *gtk.TextBuffer = @ptrCast(@alignCast(obj));
    var s_it: gtk.TextIter = undefined;
    var e_it: gtk.TextIter = undefined;
    gtk.TextBuffer.getStartIter(buf, &s_it);
    gtk.TextBuffer.getEndIter(buf, &e_it);
    const ctext = gtk.TextBuffer.getText(buf, &s_it, &e_it, 0);
    defer glib.free(@ptrCast(ctext));
    if (emit) |f| f(node_id, "changed", .{ .text = std.mem.span(ctext) });
}
`,
  cbCheckToggled: `fn cbCheckToggled(obj: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const cb: *gtk.CheckButton = @ptrCast(@alignCast(obj));
    if (emit) |f| f(node_id, "toggled", .{ .checked = gtk.CheckButton.getActive(cb) != 0 });
}
`,
  cbDropDownSelected: `// notify:: handlers get (object, pspec, user_data).
fn cbDropDownSelected(obj: *gobject.Object, _: ?*anyopaque, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const dd: *gtk.DropDown = @ptrCast(@alignCast(obj));
    const sel = gtk.DropDown.getSelected(dd);
    if (sel == std.math.maxInt(c_uint)) return; // GTK_INVALID_LIST_POSITION
    if (emit) |f| f(node_id, "selectionChanged", .{ .index = @intCast(sel) });
}
`,
  cbScaleValueChanged: `fn cbScaleValueChanged(obj: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const range: *gtk.Range = @ptrCast(@alignCast(obj));
    if (emit) |f| f(node_id, "valueChanged", .{ .value = gtk.Range.getValue(range) });
}
`,
  cbListActivate: `// the ListView \`activate\` signal passes (list_view, position, user_data).
fn cbListActivate(obj: *gobject.Object, position: c_uint, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    _ = obj;
    if (emit) |f| f(node_id, "rowActivated", .{ .index = @intCast(position) });
}
`,
};

// ListView's row-factory callbacks connect at create time (not via
// connectEvents/SIGNALS — they wire the GtkSignalListItemFactory, not a
// per-node event). Emitted unconditionally alongside the other callbacks.
const LISTVIEW_CALLBACKS = `fn lvSetup(_: *gobject.Object, list_item: *gtk.ListItem, _: ?*anyopaque) callconv(.c) void {
    const label = gtk.Label.new(null);
    gtk.ListItem.setChild(list_item, label.as(gtk.Widget));
}
fn lvBind(_: *gobject.Object, list_item: *gtk.ListItem, _: ?*anyopaque) callconv(.c) void {
    const child = gtk.ListItem.getChild(list_item) orelse return;
    const label: *gtk.Label = @ptrCast(@alignCast(child));
    const obj = gtk.ListItem.getItem(list_item) orelse return;
    const so: *gtk.StringObject = @ptrCast(@alignCast(obj));
    gtk.Label.setText(label, gtk.StringObject.getString(so));
}
`;

/** Emits the signal-wiring table + callbacks. Throws on a schema event without
 *  a template (same fail-loud contract as the prop-template throws). */
function genZigEvents(s: Schema): string {
  const used = new Set<string>();
  for (const w of s.widgets) for (const e of w.events) {
    const key = `${w.name}.${e.name}`;
    const t = SIGNALS[key];
    if (!t) throw new Error(`no signal template for event ${key} — add one when introducing it`);
    used.add(t.cb);
  }

  let out = "";
  out += LISTVIEW_CALLBACKS + "\n";
  for (const cb of used) out += CALLBACK_BODIES[cb]! + "\n";

  out += "pub fn connectEvents(widget: *gtk.Widget, kind: []const u8, node_id: u32) void {\n";
  const withEvents = s.widgets.filter((w) => w.events.length > 0);
  if (withEvents.length === 0) {
    out += "    _ = widget;\n    _ = kind;\n    _ = node_id;\n";
    out += "}\n\n";
    return out;
  }
  out += "    const data: ?*anyopaque = @ptrFromInt(@as(usize, node_id));\n";
  let first = true;
  for (const w of s.widgets) {
    if (w.events.length === 0) continue;
    out += `    ${first ? "if" : "} else if"} (std.mem.eql(u8, kind, ${JSON.stringify(w.name)})) {\n`;
    first = false;
    for (const e of w.events) {
      const t = SIGNALS[`${w.name}.${e.name}`]!;
      const objExpr = t.target === "buffer"
        ? "asObject(gtk.TextView.getBuffer(@ptrCast(@alignCast(widget))))"
        : t.target === "listview-inner"
        ? "asObject(gtk.ScrolledWindow.getChild(@ptrCast(@alignCast(widget))).?)" // ListView's tracked widget is the ScrolledWindow (M5c-D3); connect on the inner GtkListView.
        : "asObject(widget)";
      const suffix = `${w.name}_${e.name}`;
      out += `        const obj_${suffix} = ${objExpr};\n`;
      out += `        const hid_${suffix} = gobject.signalConnectData(obj_${suffix}, ${JSON.stringify(t.signal)}, @ptrCast(&${t.cb}), data, null, .{});\n`;
      out += t.suppress ? `        noteSuppressible(obj_${suffix}, hid_${suffix});\n` : `        _ = hid_${suffix};\n`;
    }
  }
  if (!first) out += "    }\n";
  out += "}\n\n";
  return out;
}

interface StructuralTemplate {
  append: (childExpr: string) => string;
  insertBefore?: (childExpr: string, beforeExpr: string) => string;
  remove: (childExpr: string) => string;
}

const STRUCTURAL: Record<string, StructuralTemplate> = {
  Window: {
    // adw.ApplicationWindow is edge-to-edge: content is a single child set via
    // setContent (NOT gtk.Window.setChild — that targets the internal handle
    // AdwApplicationWindow wraps). Headers no longer mount at window level;
    // they live inside a <toolbarview> pane.
    append: () => "        adw.ApplicationWindow.setContent(@ptrCast(@alignCast(parent)), child);\n",
    remove: () => "        adw.ApplicationWindow.setContent(@ptrCast(@alignCast(parent)), null);\n",
  },
  Box: {
    append: () => {
      let s = "        const box: *gtk.Box = @ptrCast(@alignCast(parent));\n";
      s += "        if (gtk.Widget.getParent(child) != null) {\n";
      s += "            // Moving an already-mounted child to the end (e.g. `insertBefore`\n";
      s += "            // degenerating here because `before` was null — see insertBefore\n";
      s += "            // below): `gtk_box_append` asserts the child has no parent, same\n";
      s += "            // constraint as `insertChildAfter`. `reorderChildAfter` anchored\n";
      s += "            // on the current last child is GTK's move-to-end primitive.\n";
      s += "            gtk.Box.reorderChildAfter(box, child, gtk.Widget.getLastChild(parent));\n";
      s += "        } else {\n";
      s += "            gtk.Box.append(box, child);\n";
      s += "        }\n";
      return s;
    },
    insertBefore: () => {
      let s = "        const box: *gtk.Box = @ptrCast(@alignCast(parent));\n";
      s += "        const prev = gtk.Widget.getPrevSibling(b);\n";
      s += "        if (gtk.Widget.getParent(child) != null) {\n";
      s += "            // Reordering an already-mounted child (e.g. a pin-sort), not a\n";
      s += "            // fresh insert: `gtk_box_insert_child_after` asserts the child\n";
      s += "            // has no parent and would silently no-op (Gtk-CRITICAL) here.\n";
      s += "            // `reorderChildAfter` is GTK's dedicated move primitive — it\n";
      s += "            // repositions the child in place with no unparent, so it can't\n";
      s += "            // cascade-destroy the moved child's own children (the M8 GC\n";
      s += "            // lesson: unparenting an interior node destroys its subtree).\n";
      s += "            gtk.Box.reorderChildAfter(box, child, prev);\n";
      s += "        } else {\n";
      s += "            gtk.Box.insertChildAfter(box, child, prev);\n";
      s += "        }\n";
      return s;
    },
    remove: () => "        gtk.Box.remove(@ptrCast(@alignCast(parent)), child);\n",
  },
  ScrollView: {
    append: () => "        gtk.ScrolledWindow.setChild(@ptrCast(@alignCast(parent)), child);\n",
    remove: () => "        gtk.ScrolledWindow.setChild(@ptrCast(@alignCast(parent)), null);\n",
  },
  TabView: {
    append: () => {
      let s = "        const nb: *gtk.Notebook = @ptrCast(@alignCast(parent));\n";
      s += "        _ = gtk.Notebook.appendPage(nb, child, null);\n";
      s += "        if (attached.tab_label) |tl| gtk.Notebook.setTabLabelText(nb, child, dupeZ(tl));\n";
      return s;
    },
    insertBefore: () => {
      let s = "        const nb: *gtk.Notebook = @ptrCast(@alignCast(parent));\n";
      s += "        const pos = gtk.Notebook.pageNum(nb, b);\n";
      s += "        _ = gtk.Notebook.insertPage(nb, child, null, pos);\n";
      s += "        if (attached.tab_label) |tl| gtk.Notebook.setTabLabelText(nb, child, dupeZ(tl));\n";
      return s;
    },
    remove: () => {
      let s = "        const nb: *gtk.Notebook = @ptrCast(@alignCast(parent));\n";
      s += "        const pos = gtk.Notebook.pageNum(nb, child);\n";
      s += "        if (pos >= 0) gtk.Notebook.removePage(nb, pos);\n";
      return s;
    },
  },
  Grid: {
    append: () => "        gtk.Grid.attach(@ptrCast(@alignCast(parent)), child, @intCast(attached.grid_column), @intCast(attached.grid_row), @intCast(attached.grid_column_span), @intCast(attached.grid_row_span));\n",
    insertBefore: () => "        // Grid children are position-addressed; sibling order is irrelevant.\n        gtk.Grid.attach(@ptrCast(@alignCast(parent)), child, @intCast(attached.grid_column), @intCast(attached.grid_row), @intCast(attached.grid_column_span), @intCast(attached.grid_row_span));\n",
    remove: () => "        gtk.Grid.remove(@ptrCast(@alignCast(parent)), child);\n",
  },
  SplitView: {
    append: () => {
      let s = "        const sv: *adw.OverlaySplitView = @ptrCast(@alignCast(parent));\n";
      s += "        if (attached.slot) |sl| {\n";
      s += "            if (std.mem.eql(u8, sl, \"sidebar\")) adw.OverlaySplitView.setSidebar(sv, child)\n";
      s += "            else adw.OverlaySplitView.setContent(sv, child);\n";
      s += "        } else adw.OverlaySplitView.setContent(sv, child);\n";
      return s;
    },
    insertBefore: () => {
      // Two named slots, not an ordered list — insertBefore is set-by-slot,
      // same as append. `before` (already unwrapped into `b` by the caller,
      // src/generated/widgets.zig's `insertBefore` dispatcher) plays no part.
      let s = "        const sv: *adw.OverlaySplitView = @ptrCast(@alignCast(parent));\n";
      s += "        if (attached.slot) |sl| {\n";
      s += "            if (std.mem.eql(u8, sl, \"sidebar\")) adw.OverlaySplitView.setSidebar(sv, child)\n";
      s += "            else adw.OverlaySplitView.setContent(sv, child);\n";
      s += "        } else adw.OverlaySplitView.setContent(sv, child);\n";
      return s;
    },
    remove: () => {
      let s = "        const sv: *adw.OverlaySplitView = @ptrCast(@alignCast(parent));\n";
      s += "        if (adw.OverlaySplitView.getSidebar(sv) == child) adw.OverlaySplitView.setSidebar(sv, null)\n";
      s += "        else if (adw.OverlaySplitView.getContent(sv) == child) adw.OverlaySplitView.setContent(sv, null);\n";
      return s;
    },
  },
  HeaderBar: {
    append: () => {
      let s = "        const hb: *adw.HeaderBar = @ptrCast(@alignCast(parent));\n";
      s += "        if (attached.slot) |sl| {\n";
      s += "            if (std.mem.eql(u8, sl, \"end\")) adw.HeaderBar.packEnd(hb, child)\n";
      s += "            else adw.HeaderBar.packStart(hb, child);\n";
      s += "        } else adw.HeaderBar.packStart(hb, child);\n";
      return s;
    },
    insertBefore: () => {
      let s = "        const hb: *adw.HeaderBar = @ptrCast(@alignCast(parent));\n";
      s += "        if (attached.slot) |sl| {\n";
      s += "            if (std.mem.eql(u8, sl, \"end\")) adw.HeaderBar.packEnd(hb, child)\n";
      s += "            else adw.HeaderBar.packStart(hb, child);\n";
      s += "        } else adw.HeaderBar.packStart(hb, child);\n";
      return s;
    },
    remove: () => "        adw.HeaderBar.remove(@ptrCast(@alignCast(parent)), child);\n",
  },
  ToolbarView: {
    // Child routing is by widget TYPE (like Window's HeaderBar check): a
    // HeaderBar child becomes a top bar, anything else the content pane.
    append: () => {
      let s = "        const tv: *adw.ToolbarView = @ptrCast(@alignCast(parent));\n";
      s += "        if (gobject.ext.isA(child, adw.HeaderBar)) adw.ToolbarView.addTopBar(tv, child)\n";
      s += "        else adw.ToolbarView.setContent(tv, child);\n";
      return s;
    },
    remove: () => "        adw.ToolbarView.remove(@ptrCast(@alignCast(parent)), child);\n",
  },
};

/** Kind-aware container ops, generated per container template. Throws if a
 *  schema widget declares `container != null` but has no structural template. */
function genZigStructural(s: Schema): string {
  const containers = s.widgets.filter((w) => w.container !== null);
  for (const w of containers) {
    if (!STRUCTURAL[w.name]) throw new Error(`no structural template for container widget ${w.name} — add one when introducing it (M5b)`);
  }

  let out = "";
  out += "pub fn appendChild(parent: *gtk.Widget, parent_kind: []const u8, child: *gtk.Widget, attached: protocol.Attached, dupeZ: *const fn ([]const u8) [:0]const u8) void {\n";
  let first = true;
  let appendBodies = "";
  for (const w of containers) {
    appendBodies += `    ${first ? "if" : "} else if"} (std.mem.eql(u8, parent_kind, ${JSON.stringify(w.name)})) {\n`;
    first = false;
    appendBodies += STRUCTURAL[w.name]!.append("child");
  }
  if (!appendBodies.includes("dupeZ(")) out += "    _ = dupeZ;\n";
  out += appendBodies;
  if (!first) out += "    } else {\n";
  else out += "    {\n";
  out += "        std.debug.print(\"ND_WARN append to non-container kind={s}\\n\", .{parent_kind});\n";
  out += "    }\n";
  out += "}\n\n";

  out += "pub fn insertBefore(parent: *gtk.Widget, parent_kind: []const u8, child: *gtk.Widget, before: ?*gtk.Widget, attached: protocol.Attached, dupeZ: *const fn ([]const u8) [:0]const u8) void {\n";
  out += "    // null `before` degenerates to append everywhere (matches the M4 hand-written contract).\n";
  out += "    const b = before orelse return appendChild(parent, parent_kind, child, attached, dupeZ);\n";
  first = true;
  const withInsert = containers.filter((w) => STRUCTURAL[w.name]!.insertBefore);
  for (const w of withInsert) {
    out += `    ${first ? "if" : "} else if"} (std.mem.eql(u8, parent_kind, ${JSON.stringify(w.name)})) {\n`;
    first = false;
    out += STRUCTURAL[w.name]!.insertBefore!("child", "b");
  }
  if (!first) out += "    } else {\n";
  else out += "    {\n";
  out += "        // single-child containers: insertBefore degenerates to appendChild.\n";
  out += "        appendChild(parent, parent_kind, child, attached, dupeZ);\n";
  out += "    }\n";
  out += "}\n\n";

  out += "pub fn removeChild(parent: *gtk.Widget, parent_kind: []const u8, child: *gtk.Widget) void {\n";
  first = true;
  for (const w of containers) {
    out += `    ${first ? "if" : "} else if"} (std.mem.eql(u8, parent_kind, ${JSON.stringify(w.name)})) {\n`;
    first = false;
    out += STRUCTURAL[w.name]!.remove("child");
  }
  if (!first) out += "    } else {\n";
  else out += "    {\n";
  out += "        std.debug.print(\"ND_WARN remove from non-container kind={s}\\n\", .{parent_kind});\n";
  out += "    }\n";
  out += "}\n";
  return out;
}

// ---- artifact (f): Swift/AppKit widget emitter (M6b-D6) ----
const HEADER_SWIFT = "// GENERATED by tools/codegen.ts — do not edit\n";

const SWIFT_HELPERS = `import AppKit
import Foundation

// JSON-string -> [String: Any] (M6b-D1: JSONSerialization, not a typed decoder).
func parseProps(_ json: String) -> [String: Any] {
    guard let data = json.data(using: .utf8),
          let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
    else { return [:] }
    return obj
}
func propStr(_ p: [String: Any], _ k: String) -> String? { p[k] as? String }
func propInt(_ p: [String: Any], _ k: String) -> Int? { (p[k] as? NSNumber)?.intValue }
func propDouble(_ p: [String: Any], _ k: String) -> Double? { (p[k] as? NSNumber)?.doubleValue }
func propBool(_ p: [String: Any], _ k: String) -> Bool? { (p[k] as? NSNumber)?.boolValue }
func propArray(_ p: [String: Any], _ k: String) -> [String]? { (p[k] as? [Any])?.compactMap { $0 as? String } }

// Every container view class is flipped (top-left y-down) — GLOBAL CONSTRAINT.
final class FlippedView: NSView { override var isFlipped: Bool { true } }

// SplitView's \`sidebarWidth\`/\`collapsed\` (create-time props on the
// NSSplitView itself) are read again when the sidebar child later appends
// and becomes an NSSplitViewItem — stashed here since the item doesn't exist
// yet at create time.
nonisolated(unsafe) private var splitViewSidebarFraction: [ObjectIdentifier: Double] = [:]
nonisolated(unsafe) private var splitViewCollapsed: [ObjectIdentifier: Bool] = [:]
`;

function swiftStrLit(v: string): string {
  return JSON.stringify(v);
}
function swiftDefaultStr(w: Widget, prop: string): string {
  const p = w.props.find((x) => x.name === prop)!;
  return swiftStrLit(String(p.default ?? ""));
}
function swiftDefaultInt(w: Widget, prop: string): string {
  const p = w.props.find((x) => x.name === prop)!;
  return String(p.default ?? 0);
}
function swiftDefaultDouble(w: Widget, prop: string): string {
  const p = w.props.find((x) => x.name === prop)!;
  return String(p.default ?? 0);
}
function swiftDefaultBool(w: Widget, prop: string): string {
  const p = w.props.find((x) => x.name === prop)!;
  return String(p.default ?? false);
}

function genSwift(s: Schema): string {
  let out = HEADER_SWIFT + SWIFT_HELPERS + "\n";
  out += "func ndCreate(_ kind: String, _ propsJson: String) -> NSView? {\n";
  out += "    let props = parseProps(propsJson)\n";
  for (let i = 0; i < s.widgets.length; i++) {
    const w = s.widgets[i]!;
    const kw = i === 0 ? "if" : "} else if";
    out += `    ${kw} kind == ${JSON.stringify(w.name)} {\n`;
    out += genSwiftCreateBody(w);
  }
  out += "    }\n";
  out += '    FileHandle.standardError.write("ND_WARN unknown widget kind=\\(kind)\\n".data(using: .utf8)!)\n';
  out += "    return nil\n";
  out += "}\n\n";
  out += genSwiftApplyProps(s);
  out += genSwiftEvents(s);
  out += genSwiftStructural(s);
  return out;
}

function genSwiftCreateBody(w: Widget): string {
  let out = "";
  if (w.name === "Window") {
    out += "        let content = FlippedView()\n";
    out += `        let winW = propInt(props, "defaultWidth") ?? ${swiftDefaultInt(w, "defaultWidth")}\n`;
    out += `        let winH = propInt(props, "defaultHeight") ?? ${swiftDefaultInt(w, "defaultHeight")}\n`;
    // .fullSizeContentView + transparent titlebar: the content (the split's
    // vibrancy sidebar) reaches the very top so traffic lights float over the
    // sidebar, native Notes/Mail idiom. The single unified NSToolbar the pane
    // <headerbar>s feed is created and assigned here (empty until the panes
    // register their items); see ndWindowToolbarManager / NDToolbarManager.
    out += "        let win = NSWindow(contentRect: NSRect(x: 0, y: 0, width: CGFloat(winW), height: CGFloat(winH)), styleMask: [.titled, .closable, .resizable, .fullSizeContentView], backing: .buffered, defer: false)\n";
    out += '        if let t = propStr(props, "title") { win.title = t }\n';
    out += "        win.titlebarAppearsTransparent = true\n";
    out += "        win.contentView = content\n";
    out += "        gWindow = win\n";
    out += "        let manager = NDToolbarManager()\n";
    out += "        ndWindowToolbarManager = manager\n";
    out += "        win.toolbar = manager.toolbar\n";
    out += "        win.toolbarStyle = .unified\n";
    out += "        win.center(); win.makeKeyAndOrderFront(nil)\n";
    out += "        return content\n";
  } else if (w.name === "Box") {
    out += "        let stack = NSStackView()\n";
    out += '        let vertical = (propStr(props, "orientation") ?? "vertical") == "vertical"\n';
    out += "        stack.orientation = vertical ? .vertical : .horizontal\n";
    out += `        stack.spacing = CGFloat(propInt(props, "spacing") ?? ${swiftDefaultInt(w, "spacing")})\n`;
    out += "        stack.alignment = vertical ? .leading : .centerY\n";
    out += "        stack.distribution = .gravityAreas\n";
    out += "        return stack\n";
  } else if (w.name === "Label") {
    out += `        let text = propStr(props, "text") ?? ${swiftDefaultStr(w, "text")}\n`;
    out += "        let label = NDTextField(labelWithString: text)\n";
    out += "        return label\n";
  } else if (w.name === "Button") {
    out += `        let b = NDButton(title: propStr(props, "label") ?? ${swiftDefaultStr(w, "label")}, target: nil, action: nil)\n`;
    out += "        b.setButtonType(.momentaryPushIn); b.bezelStyle = .rounded\n";
    out += "        return b\n";
  } else if (w.name === "TextInput") {
    out += `        let field = NDTextField(string: propStr(props, "text") ?? ${swiftDefaultStr(w, "text")})\n`;
    out += '        if let ph = propStr(props, "placeholder") { field.placeholderString = ph }\n';
    out += '        if let e = propBool(props, "editable") { field.isEditable = e }\n';
    out += "        return field\n";
  } else if (w.name === "TextArea") {
    out += "        let scroll = NSScrollView()\n";
    out += "        scroll.hasVerticalScroller = true\n";
    out += "        let textView = NSTextView()\n";
    out += `        textView.string = propStr(props, "text") ?? ${swiftDefaultStr(w, "text")}\n`;
    out += "        scroll.documentView = textView\n";
    out += `        let minH = propInt(props, "minContentHeight") ?? ${swiftDefaultInt(w, "minContentHeight")}\n`;
    out += "        if minH > 0 {\n";
    out += "            scroll.frame.size.height = CGFloat(minH)\n";
    // The frame set above is ignored once `scroll` becomes an arranged
    // subview (translatesAutoresizingMaskIntoConstraints turns off), so the
    // floor needs to be a real constraint to survive layout.
    out += "            let floor_ = scroll.heightAnchor.constraint(greaterThanOrEqualToConstant: CGFloat(minH))\n";
    out += "            floor_.priority = NSLayoutConstraint.Priority(999)\n";
    out += "            floor_.isActive = true\n";
    out += "        }\n";
    out += "        return scroll\n";
  } else if (w.name === "Checkbox") {
    out += `        let cb = NSButton(checkboxWithTitle: propStr(props, "label") ?? ${swiftDefaultStr(w, "label")}, target: nil, action: nil)\n`;
    out += `        cb.state = (propBool(props, "checked") ?? ${swiftDefaultBool(w, "checked")}) ? .on : .off\n`;
    out += "        return cb\n";
  } else if (w.name === "Radio") {
    out += `        let r = NSButton(radioButtonWithTitle: propStr(props, "label") ?? ${swiftDefaultStr(w, "label")}, target: nil, action: nil)\n`;
    out += `        r.state = (propBool(props, "checked") ?? ${swiftDefaultBool(w, "checked")}) ? .on : .off\n`;
    out += '        if let g = propStr(props, "group") {\n';
    out += "            radioGroupIdentifier[ObjectIdentifier(r)] = g   // mutual exclusion wired in connectEvents (T4)\n";
    out += "        } else {\n";
    out += '            FileHandle.standardError.write("ND_WARN Radio without group prop\\n".data(using: .utf8)!)\n';
    out += "        }\n";
    out += "        return r\n";
  } else if (w.name === "Select") {
    out += "        let pop = NSPopUpButton(frame: .zero, pullsDown: false)\n";
    out += '        if let opts = propArray(props, "options") { pop.addItems(withTitles: opts) }\n';
    out += `        let idx = propInt(props, "selectedIndex") ?? ${swiftDefaultInt(w, "selectedIndex")}\n`;
    out += "        if idx >= 0 && idx < pop.numberOfItems { pop.selectItem(at: idx) }\n";
    out += "        return pop\n";
  } else if (w.name === "Slider") {
    out += `        let min = propDouble(props, "min") ?? ${swiftDefaultDouble(w, "min")}\n`;
    out += `        let max = propDouble(props, "max") ?? ${swiftDefaultDouble(w, "max")}\n`;
    out += `        let value = propDouble(props, "value") ?? ${swiftDefaultDouble(w, "value")}\n`;
    out += "        let slider = NSSlider(value: value, minValue: min, maxValue: max, target: nil, action: nil)\n";
    out += '        slider.isVertical = (propStr(props, "orientation") ?? "horizontal") == "vertical"\n';
    out += "        return slider\n";
  } else if (w.name === "ProgressBar") {
    out += "        let pb = NSProgressIndicator()\n";
    out += "        pb.style = .bar\n";
    out += "        pb.isIndeterminate = false\n";
    out += "        pb.minValue = 0; pb.maxValue = 100\n";
    out += `        pb.doubleValue = (propDouble(props, "fraction") ?? ${swiftDefaultDouble(w, "fraction")}) * 100\n`;
    out += "        return pb\n";
  } else if (w.name === "Image") {
    out += "        let iv = NSImageView()\n";
    out += '        if let p = propStr(props, "path") {\n';
    out += "            iv.image = NSImage(contentsOfFile: p)\n";
    out += '        } else if let n = propStr(props, "iconName") {\n';
    out += "            iv.image = NSImage(named: n)\n";
    out += "        }\n";
    out += "        return iv\n";
  } else if (w.name === "ScrollView") {
    out += "        let sv = NSScrollView()\n";
    out += "        sv.hasVerticalScroller = true\n";
    out += "        let doc = FlippedView()\n";
    out += "        sv.documentView = doc\n";
    // doc (the FlippedView) stays the permanent documentView so scrolled
    // content keeps top-anchored/flipped semantics; it is pinned to the clip
    // view's leading/trailing/top/width so appended content gets a real
    // width to lay out into. No bottom pin: doc's height is driven by the
    // appended child's own bottom-anchor constraint (see SWIFT_STRUCTURAL.ScrollView).
    out += "        doc.translatesAutoresizingMaskIntoConstraints = false\n";
    out += "        NSLayoutConstraint.activate([\n";
    out += "            doc.leadingAnchor.constraint(equalTo: sv.contentView.leadingAnchor),\n";
    out += "            doc.trailingAnchor.constraint(equalTo: sv.contentView.trailingAnchor),\n";
    out += "            doc.topAnchor.constraint(equalTo: sv.contentView.topAnchor),\n";
    out += "            doc.widthAnchor.constraint(equalTo: sv.contentView.widthAnchor),\n";
    out += "        ])\n";
    out += `        let minH = propInt(props, "minContentHeight") ?? ${swiftDefaultInt(w, "minContentHeight")}\n`;
    out += "        if minH > 0 {\n";
    out += "            sv.frame.size.height = CGFloat(minH)\n";
    out += "            let floor_ = sv.heightAnchor.constraint(greaterThanOrEqualToConstant: CGFloat(minH))\n";
    out += "            floor_.priority = NSLayoutConstraint.Priority(999)\n";
    out += "            floor_.isActive = true\n";
    out += "        }\n";
    out += "        return sv\n";
  } else if (w.name === "Separator") {
    out += "        let sep = NSBox()\n";
    out += "        sep.boxType = .separator\n";
    out += '        let vertical = (propStr(props, "orientation") ?? "horizontal") == "vertical"\n';
    out += "        sep.frame = vertical ? NSRect(x: 0, y: 0, width: 1, height: 24) : NSRect(x: 0, y: 0, width: 24, height: 1)\n";
    out += "        return sep\n";
  } else if (w.name === "Spinner") {
    out += "        let sp = NSProgressIndicator()\n";
    out += "        sp.style = .spinning\n";
    out += "        sp.isIndeterminate = true\n";
    out += `        if propBool(props, "spinning") ?? ${swiftDefaultBool(w, "spinning")} { sp.startAnimation(nil) } else { sp.stopAnimation(nil) }\n`;
    out += "        return sp\n";
  } else if (w.name === "TabView") {
    out += "        // selectedIndex is ignored at create: pages attach afterwards (mirrors genZigCreateBody).\n";
    out += "        let tabs = NSTabView()\n";
    out += "        return tabs\n";
  } else if (w.name === "Grid") {
    out += "        let grid = NSGridView(numberOfColumns: 1, rows: 0)\n";
    out += "        return grid\n";
  } else if (w.name === "ListView") {
    out += "        return makeListView(props)  // NSScrollView+NSTableView, view-based recycling (M6b-D2)\n";
  } else if (w.name === "WebView") {
    out += '        FileHandle.standardError.write("ND_WARN WebView is a v1 stub (no WKWebView); rendering placeholder label\\n".data(using: .utf8)!)\n';
    out += '        let placeholder = NSTextField(labelWithString: "WebView unavailable (v1 stub)")\n';
    out += "        return placeholder\n";
  } else if (w.name === "SplitView") {
    // NSSplitViewController (not a bare NSSplitView) is what earns the
    // automatic Liquid Glass sidebar treatment on macOS 26 — see
    // SplitController.swift. Its `view` IS `controller.splitView`, so that's
    // still what's returned/handled as this widget's ABI handle everywhere
    // else (structural/apply arms, the toolbar's tracking separator).
    out += "        let controller = NSSplitViewController()\n";
    out += "        controller.splitView.isVertical = true\n";
    out += "        controller.splitView.dividerStyle = .thin\n";
    out += "        ndSplitControllers[ObjectIdentifier(controller.splitView)] = controller\n";
    out += '        if let w = propDouble(props, "sidebarWidth"), w > 0 {\n';
    out += "            splitViewSidebarFraction[ObjectIdentifier(controller.splitView)] = w\n";
    out += "        }\n";
    out += `        if propBool(props, "collapsed") ?? ${swiftDefaultBool(w, "collapsed")} {\n`;
    out += "            splitViewCollapsed[ObjectIdentifier(controller.splitView)] = true\n";
    out += "        }\n";
    out += "        return controller.splitView\n";
  } else if (w.name === "HeaderBar") {
    out += "        let bar = NDHeaderBarView()\n";
    out += `        bar.ndTitle = propStr(props, "title") ?? ${swiftDefaultStr(w, "title")}\n`;
    out += "        return bar\n";
  } else if (w.name === "ToolbarView") {
    // A pane wrapper: its non-header child is its content (what SplitView adds
    // to its slot and vibrancy-wraps for the sidebar); its <headerbar> child
    // contributes items to the ONE window NSToolbar, not to this view's own
    // subtree. The pane's slot (sidebar/content) — which decides where those
    // items land relative to the tracking separator — isn't known until this
    // pane is appended to the SplitView, so item registration is deferred to
    // that point (see ndToolbarPaneAttachedToSplit). NDToolbarPaneView holds
    // the header/content refs and slot until then.
    out += "        return NDToolbarPaneView()\n";
  } else {
    throw new Error(`no create template for widget ${w.name} — add one when introducing it (M6b)`);
  }
  return out;
}

/** Widgets/props whose apply arm mutates a user-controlled value and must
 *  suppress the echo event while doing so (peer of the Zig blockEcho set). */
const SWIFT_SUPPRESSED = new Set([
  "TextInput.text",
  "TextArea.text",
  "Checkbox.checked",
  "Radio.checked",
  "Select.selectedIndex",
  "Slider.value",
]);

function genSwiftApplyProps(s: Schema): string {
  let out = "func ndApplyProps(_ view: NSView, _ kind: String, _ propsJson: String) {\n";
  out += "    let props = parseProps(propsJson)\n";
  let first = true;
  for (const w of s.widgets) {
    const updProps = w.props.filter((p) => p.appliesTo === "createAndUpdate");
    if (updProps.length === 0) continue;
    const kw = first ? "if" : "} else if";
    first = false;
    out += `    ${kw} kind == ${JSON.stringify(w.name)} {\n`;
    out += genSwiftApplyBody(w, updProps);
  }
  if (!first) out += "    }\n";
  out += "}\n\n";
  return out;
}

function genSwiftApplyBody(w: Widget, updProps: Prop[]): string {
  let out = "";
  for (const p of updProps) {
    const key = `${w.name}.${p.name}`;
    if (w.name === "Window" && p.name === "title") {
      out += '        if let t = propStr(props, "title"), let win = view.window { win.title = t }\n';
    } else if (w.name === "Box" && p.name === "spacing") {
      out += '        if let sp = propInt(props, "spacing"), let stack = view as? NSStackView {\n';
      out += "            stack.spacing = CGFloat(sp)\n";
      out += "        }\n";
    } else if (w.name === "TextInput" && p.name === "text") {
      out += '        if let t = propStr(props, "text"), let field = view as? NSTextField, field.stringValue != t {\n';
      out += "            withEchoSuppressed(view) { field.stringValue = t }\n";
      out += "        }\n";
    } else if (w.name === "TextInput" && p.name === "placeholder") {
      out += '        if let ph = propStr(props, "placeholder"), let field = view as? NSTextField {\n';
      out += "            field.placeholderString = ph\n";
      out += "        }\n";
    } else if (w.name === "TextInput" && p.name === "editable") {
      out += '        if let e = propBool(props, "editable"), let field = view as? NSTextField {\n';
      out += "            field.isEditable = e\n";
      out += "        }\n";
    } else if (w.name === "TextArea" && p.name === "text") {
      out += '        if let t = propStr(props, "text"), let scroll = view as? NSScrollView,\n';
      out += "           let textView = scroll.documentView as? NSTextView, textView.string != t {\n";
      out += "            withEchoSuppressed(view) { textView.string = t }\n";
      out += "        }\n";
    } else if ((w.name === "Checkbox" || w.name === "Radio") && p.name === "checked") {
      out += '        if let c = propBool(props, "checked"), let btn = view as? NSButton {\n';
      out += "            let want: NSControl.StateValue = c ? .on : .off\n";
      out += "            if btn.state != want {\n";
      out += "                withEchoSuppressed(view) { btn.state = want }\n";
      out += "            }\n";
      out += "        }\n";
    } else if ((w.name === "Checkbox" || w.name === "Radio") && p.name === "label") {
      out += '        if let l = propStr(props, "label"), let btn = view as? NSButton {\n';
      out += "            btn.title = l\n";
      out += "        }\n";
    } else if (w.name === "Select" && p.name === "selectedIndex") {
      out += '        if let idx = propInt(props, "selectedIndex"), let pop = view as? NSPopUpButton, pop.indexOfSelectedItem != idx {\n';
      out += "            withEchoSuppressed(view) { pop.selectItem(at: idx) }\n";
      out += "        }\n";
    } else if (w.name === "Slider" && p.name === "value") {
      out += '        if let v = propDouble(props, "value"), let slider = view as? NSSlider, abs(slider.doubleValue - v) > 1e-9 {\n';
      out += "            withEchoSuppressed(view) { slider.doubleValue = v }\n";
      out += "        }\n";
    } else if (w.name === "ProgressBar" && p.name === "fraction") {
      out += '        if let f = propDouble(props, "fraction"), let pb = view as? NSProgressIndicator {\n';
      out += "            pb.doubleValue = f * 100\n";
      out += "        }\n";
    } else if (w.name === "Image" && p.name === "path") {
      out += '        if let p_ = propStr(props, "path"), let iv = view as? NSImageView {\n';
      out += "            iv.image = NSImage(contentsOfFile: p_)\n";
      out += "        }\n";
    } else if (w.name === "Image" && p.name === "iconName") {
      out += '        if let n = propStr(props, "iconName"), let iv = view as? NSImageView {\n';
      out += "            iv.image = NSImage(named: n)\n";
      out += "        }\n";
    } else if (w.name === "Spinner" && p.name === "spinning") {
      out += '        if let sp = propBool(props, "spinning"), let ind = view as? NSProgressIndicator {\n';
      out += "            if sp { ind.startAnimation(nil) } else { ind.stopAnimation(nil) }\n";
      out += "        }\n";
    } else if (w.name === "TabView" && p.name === "selectedIndex") {
      out += '        if let idx = propInt(props, "selectedIndex"), let tabs = view as? NSTabView,\n';
      out += "           idx >= 0 && idx < tabs.numberOfTabViewItems {\n";
      out += "            tabs.selectTabViewItem(at: idx)\n";
      out += "        }\n";
    } else if (w.name === "ListView" && p.name === "items") {
      out += '        if let items = propArray(props, "items") {\n';
      out += "            ndListViewSetItems(view, items)  // NDGen/ListView.swift (T3, hand-written)\n";
      out += "        }\n";
    } else if (w.name === "ListView" && p.name === "selectedIndex") {
      out += '        if let idx = propInt(props, "selectedIndex") {\n';
      out += "            ndListViewSetSelectedIndex(view, idx)  // NDGen/ListView.swift (T3, hand-written)\n";
      out += "        }\n";
    } else if (w.name === "SplitView" && p.name === "collapsed") {
      out += '        if let c = propBool(props, "collapsed"), let split = view as? NSSplitView,\n';
      out += "           let controller = ndSplitViewController(for: split), let sidebarItem = controller.splitViewItems.first {\n";
      out += "            sidebarItem.isCollapsed = c\n";
      out += "        }\n";
    } else {
      throw new Error(`no applyProps template for ${key} — add one when introducing it (M6b)`);
    }
  }
  return out;
}

interface SwiftSignalTemplate { selector: string; payload: PayloadKind }
const SWIFT_SIGNALS: Record<string, SwiftSignalTemplate> = {
  "Button.clicked":          { selector: "fireNone",    payload: "none" },
  "TextInput.changed":       { selector: "fireText",    payload: "text" },
  "TextInput.activate":      { selector: "fireText",    payload: "text" },
  "TextArea.changed":        { selector: "fireText",    payload: "text" },
  "Checkbox.toggled":        { selector: "fireChecked", payload: "checked" },
  "Radio.toggled":           { selector: "fireChecked", payload: "checked" },
  "Select.selectionChanged": { selector: "fireIndex",   payload: "index" },
  "Slider.valueChanged":     { selector: "fireValue",   payload: "value" },
  "ListView.rowActivated":   { selector: "fireIndex",   payload: "index" },
};

/** Emits `ndConnectEvents`, wiring each widget's controls to
 *  `EventDispatcher.shared` (target/action; Task 4 defines the class this
 *  references). Throws on any schema event without a template — the same
 *  fail-loud contract as `genZigEvents`. */
function genSwiftEvents(s: Schema): string {
  for (const w of s.widgets) for (const e of w.events) {
    const key = `${w.name}.${e.name}`;
    if (!SWIFT_SIGNALS[key]) throw new Error(`no signal template for event ${key} — add one when introducing it (M6b)`);
  }

  let out = "func ndConnectEvents(_ view: NSView, _ kind: String, _ nodeID: UInt32) {\n";
  const withEvents = s.widgets.filter((w) => w.events.length > 0);
  if (withEvents.length === 0) {
    out += "    _ = view; _ = kind; _ = nodeID\n";
    out += "}\n\n";
    return out;
  }
  let first = true;
  for (const w of s.widgets) {
    if (w.events.length === 0) continue;
    out += `    ${first ? "if" : "} else if"} kind == ${JSON.stringify(w.name)} {\n`;
    first = false;
    for (const e of w.events) {
      const t = SWIFT_SIGNALS[`${w.name}.${e.name}`]!;
      out += `        EventDispatcher.shared.wire(view, nodeID: nodeID, name: ${JSON.stringify(e.name)}, payload: .${t.payload}, action: #selector(EventDispatcher.${t.selector}(_:)))\n`;
    }
  }
  if (!first) out += "    }\n";
  out += "}\n\n";
  return out;
}

interface SwiftStructuralTemplate {
  append: (childExpr: string) => string;
  insertBefore?: (childExpr: string, beforeExpr: string) => string;
  remove: (childExpr: string) => string;
}

// Shared between SplitView's append/insertBefore (identical body — slots
// aren't order-addressed, so `before` plays no part). M11 Phase C: the
// sidebar/content panes are now real NSSplitViewItems on the controller
// stashed at create time (SplitController.swift) — that's what earns the
// automatic Liquid Glass sidebar (floating glass pane on macOS 26, correct
// vibrancy pre-26) from one un-guarded code path, so there's no more manual
// NSVisualEffectView/NDPaneHostView wrapper or safe-area pin: the split view
// item itself supplies material, safe-area inset, and holding behavior.
const SPLITVIEW_STRUCTURAL_BODY =
  "        let split = parent as! NSSplitView\n" +
  "        let controller = ndSplitViewController(for: split)!\n" +
  // A ToolbarView pane is a LOGICAL holder: it merges its <headerbar>'s items
  // into the window toolbar (sidebar items left of the tracking separator,
  // content items right), but the pane VIEW never enters the hierarchy. Its
  // CONTENT box (an NSStackView) is what becomes the split item's view —
  // wrapped directly, exactly like a non-toolbarview child, so the item sizes
  // it to fill. (A plain-NSView pane wrapper would only hug its content's
  // intrinsic size, collapsing the pane to a narrow column.)
  "        var realChild = child\n" +
  "        if let pane = child as? NDToolbarPaneView {\n" +
  "            ndToolbarPaneAttachedToSplit(pane, split: split, slot: attachedSlot)\n" +
  "            realChild = pane.contentView ?? child\n" +
  "        }\n" +
  // ndMakePaneViewController (SplitController.swift) wraps realChild in a
  // flipped plain-NSView host pinned below the safe area: the split view
  // item supplies the material/glass, but nothing insets an NSStackView
  // below the titlebar of a fullSizeContentView window on its own — without
  // this pin, sidebar/editor content renders under the traffic lights
  // (measured: search-input at y=20). A plain NSView host does NOT block
  // the glass (unlike the old NSVisualEffectView wrapper).
  "        let vc = ndMakePaneViewController(realChild)\n" +
  '        if attachedSlot == "sidebar" {\n' +
  "            let item = NSSplitViewItem(sidebarWithViewController: vc)\n" +
  "            if let fraction = splitViewSidebarFraction[ObjectIdentifier(split)] {\n" +
  "                item.preferredThicknessFraction = fraction\n" +
  "            }\n" +
  "            item.canCollapse = true\n" +
  "            item.isCollapsed = splitViewCollapsed[ObjectIdentifier(split)] ?? false\n" +
  "            controller.insertSplitViewItem(item, at: 0)\n" +
  "        } else {\n" +
  "            let item = NSSplitViewItem(viewController: vc)\n" +
  "            item.automaticallyAdjustsSafeAreaInsets = true\n" +
  "            controller.addSplitViewItem(item)\n" +
  "        }\n";

const SWIFT_STRUCTURAL: Record<string, SwiftStructuralTemplate> = {
  Window: {
    // `parent` here is the Window's tracked handle: the flipped contentView
    // itself (returned by the Window create arm) — reachable via
    // `parent.window` since it WAS the window's contentView at creation.
    // Window chrome on the Mac (M11 Phase B) is the unified NSToolbar the
    // pane <headerbar>s feed via the SplitView, not a window-level header
    // child — so there is no NDHeaderBarView branch here.
    //
    // M11 Phase C: a registered SplitView child must enter the window as
    // `contentViewController` (not a plain subview) — only that path earns
    // the automatic Liquid Glass sidebar treatment on macOS 26. This orphans
    // `parent` (Risk 1) — Backend.swift's get_window and Overlay.swift's
    // ndShowOverlay resolve the LIVE content via `contentViewController?.view`
    // first for this reason, and src/tree.zig's post-crash respawn path binds
    // the new Window node to whatever get_window returns, so that resolution
    // must stay live too. Any other child (counter/gallery, no split) keeps
    // the plain-subview path untouched.
    // `parent.window ?? gWindow`: once a split is installed as
    // contentViewController, `parent` (the create-arm FlippedView) is
    // orphaned and `parent.window` is nil — a REMOUNT (HMR / crash-restart
    // generation swap) must still find the window, so fall back to the
    // gWindow global. The non-split branch is self-healing for the same
    // reason: if a controller is still installed, clear it and re-seat
    // `parent` as contentView before parenting the plain child into it.
    append: () =>
      "        let window = parent.window ?? gWindow\n" +
      "        parent.subviews.forEach { $0.removeFromSuperview() }\n" +
      "        if let split = child as? NSSplitView, let controller = ndSplitViewController(for: split), let win = window {\n" +
      // Assigning contentViewController resizes the window to the
      // controller's preferredContentSize (default zero -> the split view's
      // tiny fitting size), clobbering Window defaultWidth/Height — measured
      // 900x600 -> 500x500, and a post-assignment setFrame gets re-clobbered
      // on a later layout pass. Feed the mechanism instead: the current
      // contentView (the Window handle) still holds the intended size.
      "            controller.preferredContentSize = win.contentView?.frame.size ?? win.frame.size\n" +
      "            win.contentViewController = controller\n" +
      "        } else {\n" +
      "            if let win = window, win.contentViewController != nil {\n" +
      "                win.contentViewController = nil\n" +
      "                win.contentView = parent\n" +
      "            }\n" +
      "            parent.addSubview(child)\n" +
      "            child.frame = parent.bounds\n" +
      "            child.autoresizingMask = [.width, .height]\n" +
      "        }\n",
    // A registered split currently installed as contentViewController has no
    // superview to remove from (removeFromSuperview() would no-op or, worse,
    // reach into the window's private frame view) — clear
    // contentViewController instead so a later re-append can install a fresh
    // one cleanly (HMR remove+re-append of the root split).
    // Guard notes: compare CONTROLLERS, not `contentViewController?.view ===
    // child` — the controller's `view` is a distinct wrapper, never the
    // splitView handle (see SplitController.swift), so a view comparison is
    // dead code. And `parent.window` is nil in exactly this case (parent is
    // orphaned while a split is installed) — resolve via gWindow. After
    // clearing, re-seat `parent` as contentView so later appends of either
    // kind land in a live hierarchy.
    remove: () =>
      "        if let split = child as? NSSplitView, let controller = ndSplitViewController(for: split),\n" +
      "           let window = parent.window ?? gWindow, window.contentViewController === controller {\n" +
      "            window.contentViewController = nil\n" +
      "            window.contentView = parent\n" +
      "        } else {\n" +
      "            child.removeFromSuperview()\n" +
      "        }\n",
  },
  Box: {
    // Cross-axis "fill" + main-axis expand are both handled by
    // ndBoxChildAttached (Layout.swift), driven off the hexpand/vexpand/
    // halign/valign flags ndApplyStyle records per child.
    append: () => "        let stack = parent as! NSStackView\n        stack.addArrangedSubview(child)\n        ndBoxChildAttached(stack, child)\n",
    // The index must be computed on the child-less list: insertArrangedSubview(_:at:)
    // implicitly removes `child` first if it's already arranged, which shifts
    // `before`'s index down by one whenever child currently sits above it —
    // so detach child from its stale slot BEFORE finding `before`'s index
    // (mirrors src/tree.zig:156 recordInsertBefore's detach-first model).
    insertBefore: () =>
      "        let stack = parent as! NSStackView\n" +
      "        if stack.arrangedSubviews.contains(child) { stack.removeArrangedSubview(child) }\n" +
      "        let idx = stack.arrangedSubviews.firstIndex(of: before) ?? stack.arrangedSubviews.count\n" +
      "        stack.insertArrangedSubview(child, at: idx)\n" +
      "        ndBoxChildAttached(stack, child)\n",
    remove: () => "        let stack = parent as! NSStackView\n        stack.removeArrangedSubview(child)\n        ndBoxChildDetached(stack, child)\n        child.removeFromSuperview()\n",
  },
  ScrollView: {
    // childModel is "single" (schema/widgets.json): documentView itself is
    // never reassigned (create's FlippedView stays put, see genSwiftCreateBody)
    // — the child is pinned inside it instead, leading+trailing+top+bottom, so
    // its own intrinsic/fitting height drives the document's scrollable height
    // while the width tracks the clip view via doc's own constraints. Any
    // prior child is cleared first to preserve single-child semantics (mirrors
    // SWIFT_STRUCTURAL.Window's `parent.subviews.forEach { removeFromSuperview() }`).
    append: () =>
      "        let sv = parent as! NSScrollView\n" +
      "        let doc = sv.documentView!\n" +
      "        doc.subviews.forEach { $0.removeFromSuperview() }\n" +
      "        child.translatesAutoresizingMaskIntoConstraints = false\n" +
      "        doc.addSubview(child)\n" +
      "        NSLayoutConstraint.activate([\n" +
      "            child.leadingAnchor.constraint(equalTo: doc.leadingAnchor),\n" +
      "            child.trailingAnchor.constraint(equalTo: doc.trailingAnchor),\n" +
      "            child.topAnchor.constraint(equalTo: doc.topAnchor),\n" +
      "            child.bottomAnchor.constraint(equalTo: doc.bottomAnchor),\n" +
      "        ])\n",
    remove: () =>
      "        let sv = parent as! NSScrollView\n" +
      "        if child.superview === sv.documentView { child.removeFromSuperview() }\n",
  },
  TabView: {
    append: () => "        let tabs = parent as! NSTabView\n        let item = NSTabViewItem()\n        item.view = child\n        item.label = attachedTabLabel\n        tabs.addTabViewItem(item)\n",
    insertBefore: () => "        let tabs = parent as! NSTabView\n        let item = NSTabViewItem()\n        item.view = child\n        item.label = attachedTabLabel\n        let idx = tabs.tabViewItems.firstIndex { $0.view === before } ?? tabs.tabViewItems.count\n        tabs.insertTabViewItem(item, at: idx)\n",
    remove: () => "        let tabs = parent as! NSTabView\n        if let item = tabs.tabViewItems.first(where: { $0.view === child }) {\n            tabs.removeTabViewItem(item)\n        }\n",
  },
  Grid: {
    append: () => "        let grid = parent as! NSGridView\n        ndGridPlace(grid, child, row: attachedGridRow, column: attachedGridColumn, rowSpan: attachedGridRowSpan, columnSpan: attachedGridColumnSpan)\n",
    insertBefore: () => "        // Grid children are position-addressed; sibling order is irrelevant.\n        let grid = parent as! NSGridView\n        ndGridPlace(grid, child, row: attachedGridRow, column: attachedGridColumn, rowSpan: attachedGridRowSpan, columnSpan: attachedGridColumnSpan)\n",
    remove: () => "        let grid = parent as! NSGridView\n        ndGridRemove(grid, child)\n",
  },
  SplitView: {
    // Two named slots, not an ordered list — insertBefore is set-by-slot, same
    // as append (mirrors the Zig STRUCTURAL.SplitView shape); `before` is
    // unused. NSSplitViewItem order is enforced regardless of mount order —
    // sidebar always inserted at index 0, content always appended at the end.
    append: () => SPLITVIEW_STRUCTURAL_BODY,
    insertBefore: () => SPLITVIEW_STRUCTURAL_BODY,
    remove: () =>
      "        let split = parent as! NSSplitView\n" +
      "        let controller = ndSplitViewController(for: split)!\n" +
      "        var realChild = child\n" +
      "        if let pane = child as? NDToolbarPaneView {\n" +
      "            ndToolbarPaneDetachedFromSplit(pane)\n" +
      "            realChild = pane.contentView ?? child\n" +
      "        }\n" +
      // realChild is directly a split view item's viewController.view now (no
      // wrapper) — find the owning item by that identity and remove it via
      // the controller so its NSSplitViewItem bookkeeping stays consistent.
      // The superview-removal fallback below only covers a non-item child
      // (shouldn't occur via the generated arms, kept for defense in depth).
      // realChild sits INSIDE the pane host view (ndMakePaneViewController),
      // so match by descendant, not view identity.
      "        if let item = controller.splitViewItems.first(where: { $0.viewController.view === realChild || realChild.isDescendant(of: $0.viewController.view) }) {\n" +
      "            controller.removeSplitViewItem(item)\n" +
      "        } else {\n" +
      "            split.removeArrangedSubview(realChild)\n" +
      "            realChild.removeFromSuperview()\n" +
      "        }\n",
  },
  HeaderBar: {
    append: () => '        ndHeaderBarPack(parent as! NDHeaderBarView, child, slot: attachedSlot)\n',
    insertBefore: () => '        ndHeaderBarPack(parent as! NDHeaderBarView, child, slot: attachedSlot)\n',
    remove: () => "        ndHeaderBarUnpack(parent as! NDHeaderBarView, child)\n",
  },
  ToolbarView: {
    // Child routing is by widget TYPE (like Window's HeaderBar check): a
    // <headerbar> child is recorded as the pane's header (its items feed the
    // window toolbar, tagged by pane slot, once the pane is in the split); any
    // other child becomes the pane's content view. `before` is irrelevant —
    // a pane has at most one header and one content child.
    append: () => "        ndToolbarPanePack(parent as! NDToolbarPaneView, child)\n",
    insertBefore: () => "        ndToolbarPanePack(parent as! NDToolbarPaneView, child)\n",
    remove: () => "        ndToolbarPaneUnpack(parent as! NDToolbarPaneView, child)\n",
  },
};

/** Emits `ndAppendChild`/`ndInsertBefore`/`ndRemoveChild`, one arm per
 *  container widget. Throws on a container without a structural template —
 *  the same fail-loud contract as `genZigStructural`. Attached-prop values
 *  (`tabLabel`, `gridRow`/`gridColumn`/`gridRowSpan`/`gridColumnSpan`) are
 *  decoded from `attachedJson` up front so every arm can read them by name. */
function genSwiftStructural(s: Schema): string {
  const containers = s.widgets.filter((w) => w.container !== null);
  for (const w of containers) {
    if (!SWIFT_STRUCTURAL[w.name]) throw new Error(`no structural template for container widget ${w.name} — add one when introducing it (M6b)`);
  }

  const attachedPrelude =
    "    let attached = parseProps(attachedJson)\n" +
    '    let attachedTabLabel = propStr(attached, "tabLabel") ?? ""\n' +
    '    let attachedGridRow = propInt(attached, "gridRow") ?? 0\n' +
    '    let attachedGridColumn = propInt(attached, "gridColumn") ?? 0\n' +
    '    let attachedGridRowSpan = propInt(attached, "gridRowSpan") ?? 1\n' +
    '    let attachedGridColumnSpan = propInt(attached, "gridColumnSpan") ?? 1\n' +
    '    let attachedSlot = propStr(attached, "slot") ?? "content"\n';

  let out = "func ndAppendChild(_ parent: NSView, _ parentKind: String, _ child: NSView, _ attachedJson: String) {\n";
  out += attachedPrelude;
  let first = true;
  for (const w of containers) {
    out += `    ${first ? "if" : "} else if"} parentKind == ${JSON.stringify(w.name)} {\n`;
    first = false;
    out += SWIFT_STRUCTURAL[w.name]!.append("child");
  }
  if (!first) out += "    } else {\n";
  else out += "    {\n";
  out += '        FileHandle.standardError.write("ND_WARN append to non-container kind=\\(parentKind)\\n".data(using: .utf8)!)\n';
  out += "    }\n";
  out += "}\n\n";

  out += "func ndInsertBefore(_ parent: NSView, _ parentKind: String, _ child: NSView, _ before: NSView?, _ attachedJson: String) {\n";
  out += "    // nil `before` degenerates to append everywhere (matches the M4 hand-written contract).\n";
  out += "    guard let before = before else { return ndAppendChild(parent, parentKind, child, attachedJson) }\n";
  out += attachedPrelude;
  first = true;
  const withInsert = containers.filter((w) => SWIFT_STRUCTURAL[w.name]!.insertBefore);
  for (const w of withInsert) {
    out += `    ${first ? "if" : "} else if"} parentKind == ${JSON.stringify(w.name)} {\n`;
    first = false;
    out += SWIFT_STRUCTURAL[w.name]!.insertBefore!("child", "before");
  }
  if (!first) out += "    } else {\n";
  else out += "    {\n";
  out += "        // single-child containers: insertBefore degenerates to appendChild.\n";
  out += "        ndAppendChild(parent, parentKind, child, attachedJson)\n";
  out += "    }\n";
  out += "}\n\n";

  out += "func ndRemoveChild(_ parent: NSView, _ parentKind: String, _ child: NSView) {\n";
  first = true;
  for (const w of containers) {
    out += `    ${first ? "if" : "} else if"} parentKind == ${JSON.stringify(w.name)} {\n`;
    first = false;
    out += SWIFT_STRUCTURAL[w.name]!.remove("child");
  }
  if (!first) out += "    } else {\n";
  else out += "    {\n";
  out += '        FileHandle.standardError.write("ND_WARN remove from non-container kind=\\(parentKind)\\n".data(using: .utf8)!)\n';
  out += "    }\n";
  out += "}\n";
  return out;
}

// ---- artifact (c): docs ----
function genDocs(s: Schema): string {
  let out = "<!-- GENERATED by tools/codegen.ts — do not edit -->\n\n";
  out += "# Widget reference\n\n";
  out += `Schema version: ${s.schemaVersion}. Generated from \`schema/widgets.json\`.\n\n`;
  for (const w of s.widgets) {
    out += `## ${w.name} (\`<${w.intrinsic}>\`)\n\n`;
    if (w.stub) out += `> **v1 stub** — renders a placeholder Label; see M5b-D7.\n\n`;
    out += `Automation role: \`${w.automation.role}\`. `;
    out += `Text source: ${w.automation.textFrom ? "`" + w.automation.textFrom + "`" : "none"}. `;
    out += `Children: ${w.container ? w.container.childModel : "none"}.\n\n`;
    out += "| Prop | Type | Default | Applied |\n|---|---|---|---|\n";
    for (const p of w.props) {
      const type = p.type === "enum" ? (p.values ?? []).join(" \\| ") : p.type;
      const def = p.default === undefined ? "—" : String(p.default);
      out += `| \`${p.name}\` | ${type} | ${def} | ${p.appliesTo} |\n`;
    }
    out += "\n";
    if (w.events.length) {
      out += "| Event | Handler | Payload |\n|---|---|---|\n";
      for (const e of w.events) {
        out += `| \`${e.name}\` | \`${e.ndpName ?? e.name}\` | ${e.payload ?? "none"} |\n`;
      }
      out += "\n";
    }
    if (w.container?.attachedProps?.length) {
      out += "Attached props (set on children):\n\n";
      out += "| Prop | Type | Default |\n|---|---|---|\n";
      for (const ap of w.container.attachedProps) {
        out += `| \`${ap.name}\` | ${ap.type} | ${ap.default === undefined ? "—" : String(ap.default)} |\n`;
      }
      out += "\nAttached props are attach-time-only; changing them after mount is a no-op.\n\n";
    }
    if (w.name === "Select") out += "`options` is create-only in v1.\n\n";
    if (w.name === "TabView") out += "`selectedIndex` takes effect on update; initial page is 0.\n\n";
  }
  return out;
}

// ---- artifact (e): styling reference ----
function genStyleDocs(s: Schema): string {
  let out = "<!-- GENERATED by tools/codegen.ts — do not edit -->\n\n";
  out += "# Styling\n\n";
  out += "`style` is an explicit, **non-web** prop on every widget. GTK styling is NOT web CSS: there is no `flex`, `grid`, `position`, `display`, or `justifyContent`. Layout comes from container widgets (`<box>`/`<grid>`), not from `style`. Unknown keys are rejected at the React renderer with a fix-it message and defensively rejected host-side.\n\n";
  if (s.style) {
    out += "## Valid keys\n\n| Key | Shape | Compiles to |\n|---|---|---|\n";
    for (const [k, def] of Object.entries(s.style.keys)) {
      const shape = def.kind === "object" ? "object (" + Object.keys(def.fields ?? {}).join(", ") + ")" : def.kind;
      const to = def.target === "widget" ? "GTK widget property (not CSS)" : "GTK CSS (`" + (def.css ?? "nested") + "`)";
      out += `| \`${k}\` | ${shape} | ${to} |\n`;
    }
    out += "\n";
  }
  out += "## Why `margin` differs from `padding`\n\nGTK widget **margins are widget properties** (`gtk_widget_set_margin_*`), not CSS — so `margin` compiles to `setMarginStart/End/Top/Bottom`. `padding` IS a GTK CSS property and stays in the generated `.nd-<id>` CSS block, alongside colors, fonts, and borders. (M5c-D2.)\n\n";
  out += "## React item-templates for ListView\n\nDeferred (M5c-D-followup): `<listview>` renders native string rows in v1. Item-template components need the synchronous bind design from spec D10.\n";
  return out;
}

// ---- artifact (f): binary NDP widgetType u16 table (ndp-binary spec §7) ----
// Schema declaration order, 1-based, value 0 reserved/invalid, NEVER renumbered or reused.
function genWidgetTypesTs(s: Schema): string {
  let out = HEADER_TS + "export const WIDGET_TYPE_RESERVED = 0;\n";
  out += "export const WIDGET_TYPE: Record<string, number> = {\n";
  for (let i = 0; i < s.widgets.length; i++) {
    out += `  ${s.widgets[i]!.name}: ${i + 1},\n`;
  }
  out += "};\n";
  return out;
}

function genWidgetTypesZig(s: Schema): string {
  let out = HEADER_ZIG + "const std = @import(\"std\");\n\n";
  out += "const Entry = struct { name: []const u8, value: u16 };\n";
  out += "pub const widget_types = [_]Entry{\n";
  for (let i = 0; i < s.widgets.length; i++) {
    out += `    .{ .name = ${JSON.stringify(s.widgets[i]!.name)}, .value = ${i + 1} },\n`;
  }
  out += "};\n\n";
  out += "pub fn widgetTypeOf(name: []const u8) ?u16 {\n";
  out += "    for (widget_types) |e| if (std.mem.eql(u8, e.name, name)) return e.value;\n";
  out += "    return null;\n}\n\n";
  out += "pub fn widgetNameOf(v: u16) ?[]const u8 {\n";
  out += "    for (widget_types) |e| if (e.value == v) return e.name;\n";
  out += "    return null;\n}\n";
  return out;
}

async function writeIfChanged(rel: string, content: string): Promise<void> {
  const path = resolve(ROOT, rel);
  await Bun.write(path, content);
  console.log("wrote", rel, `(${content.length} bytes)`);
}

const schema = (await Bun.file(resolve(ROOT, "schema/widgets.json")).json()) as Schema;
await writeIfChanged("packages/react/src/generated/intrinsics.ts", genIntrinsics(schema));
await writeIfChanged("packages/react/src/generated/schema-meta.ts", genSchemaMeta(schema));
await writeIfChanged("src/generated/widgets.zig", genZig(schema));
await writeIfChanged("docs/widgets.md", genDocs(schema));
await writeIfChanged("docs/styling.md", genStyleDocs(schema));
await writeIfChanged("swift/Sources/NDGen/Widgets.swift", genSwift(schema));
await writeIfChanged("packages/react/src/generated/widget-types.ts", genWidgetTypesTs(schema));
await writeIfChanged("src/generated/widget_types.zig", genWidgetTypesZig(schema));
console.log("codegen complete");
