#!/usr/bin/env bun
// tools/codegen.ts — reads schema/widgets.json and emits the generated
// TS/JSX intrinsics, Zig widget appliers, docs, and automation meta tables.
// Deterministic: widgets and props are emitted in schema-declaration order.
// Run: `bun tools/codegen.ts`. Never hand-edit the generated files.

import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const HEADER_TS = "// GENERATED by tools/codegen.ts — do not edit\n";
const HEADER_ZIG = "// GENERATED by tools/codegen.ts — do not edit\n";

type PropType = "string" | "int" | "bool" | "enum";
type AppliesTo = "create" | "createAndUpdate" | "meta";

interface Prop {
  name: string;
  type: PropType;
  values?: string[];
  default?: string | number | boolean;
  required?: boolean;
  appliesTo: AppliesTo;
}
interface Event { name: string; ndpName?: string }
interface Widget {
  name: string;
  intrinsic: string;
  container: { childModel: "single" | "multi" } | null;
  props: Prop[];
  events: Event[];
  automation: { role: string; textFrom: string | null };
}
interface Schema { schemaVersion: number; widgets: Widget[] }

function tsTypeOf(p: Prop): string {
  switch (p.type) {
    case "string": return "string";
    case "int": return "number";
    case "bool": return "boolean";
    case "enum": return (p.values ?? []).map((v) => JSON.stringify(v)).join(" | ");
  }
}

function zigLit(p: Prop): string {
  if (p.type === "int") return String(p.default ?? 0);
  if (p.type === "bool") return String(p.default ?? false);
  return JSON.stringify(String(p.default ?? "")); // string/enum default as a Zig string literal
}

// ---- artifact (a): TS/JSX intrinsics ----
function genIntrinsics(s: Schema): string {
  let out = HEADER_TS;
  out += 'import type { ReactNode } from "react";\n\n';
  out += "export { jsx, jsxs, Fragment } from \"react/jsx-runtime\";\n\n";
  out += "export type WidgetName = " + s.widgets.map((w) => JSON.stringify(w.name)).join(" | ") + ";\n";
  out += "export type WidgetType = " + s.widgets.map((w) => JSON.stringify(w.intrinsic)).join(" | ") + ";\n\n";
  out += "export namespace JSX {\n";
  out += "  export interface IntrinsicElements {\n";
  for (const w of s.widgets) {
    const fields: string[] = [];
    for (const p of w.props) fields.push(`${p.name}?: ${tsTypeOf(p)}`);
    for (const e of w.events) fields.push(`${e.ndpName ?? e.name}?: () => void`);
    fields.push("children?: ReactNode");
    out += `    ${w.intrinsic}: { ${fields.join("; ")} };\n`;
  }
  out += "  }\n";
  out += "  export type Element = ReactNode;\n";
  out += "  export interface ElementChildrenAttribute {\n    children: {};\n  }\n";
  out += "}\n";
  return out;
}

// ---- artifact (d): automation role/textFrom meta ----
function genSchemaMeta(s: Schema): string {
  let out = HEADER_TS;
  out += "export interface WidgetMeta {\n  role: string;\n  textFrom: string | null;\n  childModel: \"single\" | \"multi\" | null;\n}\n\n";
  out += "export const widgetMeta: Record<string, WidgetMeta> = {\n";
  for (const w of s.widgets) {
    const cm = w.container ? JSON.stringify(w.container.childModel) : "null";
    out += `  ${JSON.stringify(w.name)}: { role: ${JSON.stringify(w.automation.role)}, textFrom: ${w.automation.textFrom === null ? "null" : JSON.stringify(w.automation.textFrom)}, childModel: ${cm} },\n`;
  }
  out += "};\n";
  return out;
}

// ---- artifact (b): Zig widget appliers ----
function genZig(s: Schema): string {
  let out = HEADER_ZIG;
  out += "const std = @import(\"std\");\n";
  out += "const gtk = @import(\"gtk\");\n\n";
  out += "// Extracts a typed prop from the on-wire `?std.json.Value`. Mirrors the\n";
  out += "// helpers that used to live inline in gtk_backend.zig.\n";
  out += "fn propStr(props: ?std.json.Value, key: []const u8) ?[]const u8 {\n";
  out += "    const v = props orelse return null;\n";
  out += "    if (v != .object) return null;\n";
  out += "    const field = v.object.get(key) orelse return null;\n";
  out += "    return switch (field) {\n        .string => field.string,\n        else => null,\n    };\n}\n\n";
  out += "fn propInt(props: ?std.json.Value, key: []const u8) ?i64 {\n";
  out += "    const v = props orelse return null;\n";
  out += "    if (v != .object) return null;\n";
  out += "    const field = v.object.get(key) orelse return null;\n";
  out += "    return switch (field) {\n        .integer => field.integer,\n        else => null,\n    };\n}\n\n";
  out += "/// The GTK create dispatcher. `dupeZ` turns a wire string into a NUL-\n";
  out += "/// terminated GTK string using the backend arena (passed by the caller).\n";
  out += "pub fn create(\n";
  out += "    app: *gtk.Application,\n";
  out += "    kind: []const u8,\n";
  out += "    props: ?std.json.Value,\n";
  out += "    dupeZ: *const fn ([]const u8) [:0]const u8,\n";
  out += "    the_window: *?*gtk.Window,\n";
  out += ") !*gtk.Widget {\n";
  for (let i = 0; i < s.widgets.length; i++) {
    const w = s.widgets[i];
    const kw = i === 0 ? "if" : "} else if";
    out += `    ${kw} (std.mem.eql(u8, kind, ${JSON.stringify(w.name)})) {\n`;
    out += genZigCreateBody(w);
  }
  out += "    }\n";
  out += "    std.debug.print(\"ND_WARN unknown widget kind={s}\\n\", .{kind});\n";
  out += "    return error.UnknownWidget;\n";
  out += "}\n\n";
  out += "/// The GTK update dispatcher for createAndUpdate props.\n";
  out += "pub fn applyProps(widget: *gtk.Widget, kind: []const u8, props: ?std.json.Value, dupeZ: *const fn ([]const u8) [:0]const u8) void {\n";
  let firstApply = true;
  for (const w of s.widgets) {
    const updProps = w.props.filter((p) => p.appliesTo === "createAndUpdate");
    if (updProps.length === 0) continue;
    const kw = firstApply ? "if" : "} else if";
    firstApply = false;
    out += `    ${kw} (std.mem.eql(u8, kind, ${JSON.stringify(w.name)})) {\n`;
    out += genZigApplyBody(w, updProps);
  }
  if (!firstApply) out += "    }\n";
  out += "}\n";
  return out;
}

function genZigCreateBody(w: Widget): string {
  let out = "";
  if (w.name === "Window") {
    out += "        const window = gtk.ApplicationWindow.new(app);\n";
    out += "        const win = window.as(gtk.Window);\n";
    out += "        the_window.* = win;\n";
    out += "        if (propStr(props, \"title\")) |t| gtk.Window.setTitle(win, dupeZ(t));\n";
    out += `        const w: c_int = @intCast(propInt(props, "defaultWidth") orelse ${dflt(w, "defaultWidth")});\n`;
    out += `        const h: c_int = @intCast(propInt(props, "defaultHeight") orelse ${dflt(w, "defaultHeight")});\n`;
    out += "        gtk.Window.setDefaultSize(win, w, h);\n";
    out += "        gtk.Window.present(win);\n";
    out += "        return window.as(gtk.Widget);\n";
  } else if (w.name === "Box") {
    out += "        const vertical = if (propStr(props, \"orientation\")) |o| std.mem.eql(u8, o, \"vertical\") else true;\n";
    out += "        const orientation: gtk.Orientation = if (vertical) .vertical else .horizontal;\n";
    out += `        const spacing: c_int = @intCast(propInt(props, "spacing") orelse ${dflt(w, "spacing")});\n`;
    out += "        const box = gtk.Box.new(orientation, spacing);\n";
    out += "        return box.as(gtk.Widget);\n";
  } else if (w.name === "Label") {
    out += `        const text = propStr(props, "text") orelse ${zigDefaultStr(w, "text")};\n`;
    out += "        const label = gtk.Label.new(dupeZ(text));\n";
    out += "        return label.as(gtk.Widget);\n";
  } else if (w.name === "Button") {
    out += `        const lbl = propStr(props, "label") orelse ${zigDefaultStr(w, "label")};\n`;
    out += "        const button = gtk.Button.newWithLabel(dupeZ(lbl));\n";
    out += "        return button.as(gtk.Widget);\n";
  } else {
    throw new Error(`no create template for widget ${w.name} — add one when introducing it (M5b)`);
  }
  return out;
}

function genZigApplyBody(w: Widget, updProps: Prop[]): string {
  let out = "";
  for (const p of updProps) {
    if (w.name === "Box" && p.name === "spacing") {
      out += "        if (propInt(props, \"spacing\")) |s| {\n";
      out += "            const box: *gtk.Box = @ptrCast(@alignCast(widget));\n";
      out += "            gtk.Box.setSpacing(box, @intCast(s));\n";
      out += "        }\n";
    } else if (w.name === "Window" && p.name === "title") {
      out += "        if (propStr(props, \"title\")) |t| {\n";
      out += "            const win: *gtk.Window = @ptrCast(@alignCast(widget));\n";
      out += "            gtk.Window.setTitle(win, dupeZ(t));\n";
      out += "        }\n";
    } else {
      throw new Error(`no applyProps template for ${w.name}.${p.name} — add one when introducing it (M5b)`);
    }
  }
  return out;
}

function dflt(w: Widget, prop: string): string {
  const p = w.props.find((x) => x.name === prop)!;
  return String(p.default);
}
function zigDefaultStr(w: Widget, prop: string): string {
  const p = w.props.find((x) => x.name === prop)!;
  return JSON.stringify(String(p.default ?? ""));
}

// ---- artifact (c): docs ----
function genDocs(s: Schema): string {
  let out = "<!-- GENERATED by tools/codegen.ts — do not edit -->\n\n";
  out += "# Widget reference\n\n";
  out += `Schema version: ${s.schemaVersion}. Generated from \`schema/widgets.json\`.\n\n`;
  for (const w of s.widgets) {
    out += `## ${w.name} (\`<${w.intrinsic}>\`)\n\n`;
    out += `Automation role: \`${w.automation.role}\`. `;
    out += `Text source: ${w.automation.textFrom ? "`" + w.automation.textFrom + "`" : "none"}. `;
    out += `Children: ${w.container ? w.container.childModel : "none"}.\n\n`;
    out += "| Prop | Type | Default | Applied |\n|---|---|---|---|\n";
    for (const p of w.props) {
      const type = p.type === "enum" ? (p.values ?? []).join(" \\| ") : p.type;
      const def = p.default === undefined ? "—" : String(p.default);
      out += `| \`${p.name}\` | ${type} | ${def} | ${p.appliesTo} |\n`;
    }
    out += "\n";
    if (w.events.length) {
      out += "Events: " + w.events.map((e) => `\`${e.name}\` (\`${e.ndpName ?? e.name}\`)`).join(", ") + ".\n\n";
    }
  }
  return out;
}

async function writeIfChanged(rel: string, content: string): Promise<void> {
  const path = resolve(ROOT, rel);
  await Bun.write(path, content);
  console.log("wrote", rel, `(${content.length} bytes)`);
}

const schema = (await Bun.file(resolve(ROOT, "schema/widgets.json")).json()) as Schema;
await writeIfChanged("packages/react/src/generated/intrinsics.ts", genIntrinsics(schema));
await writeIfChanged("packages/react/src/generated/schema-meta.ts", genSchemaMeta(schema));
await writeIfChanged("src/generated/widgets.zig", genZig(schema));
await writeIfChanged("docs/widgets.md", genDocs(schema));
console.log("codegen complete");
