#!/usr/bin/env bun
// tools/codegen.ts — reads schema/widgets.json and emits the generated
// TS/JSX intrinsics, Zig widget appliers, docs, and automation meta tables.
// Deterministic: widgets and props are emitted in schema-declaration order.
// Run: `bun tools/codegen.ts`. Never hand-edit the generated files.

import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const HEADER_TS = "// GENERATED by tools/codegen.ts — do not edit\n";
const HEADER_ZIG = "// GENERATED by tools/codegen.ts — do not edit\n";

type PropType = "string" | "int" | "bool" | "enum" | "float" | "stringList";
type AppliesTo = "create" | "createAndUpdate" | "meta";
type PayloadKind = "none" | "text" | "checked" | "value" | "index";

interface Prop {
  name: string;
  type: PropType;
  values?: string[];
  default?: string | number | boolean;
  required?: boolean;
  appliesTo: AppliesTo;
}
interface Event { name: string; ndpName?: string; payload?: PayloadKind }
interface AttachedProp { name: string; type: PropType; default?: string | number | boolean }
interface Container { childModel: "single" | "multi"; attachedProps?: AttachedProp[] }
interface Widget {
  name: string;
  intrinsic: string;
  container: Container | null;
  stub?: boolean;
  props: Prop[];
  events: Event[];
  automation: { role: string; textFrom: string | null };
}
type StyleKeyKind = "color" | "int" | "enum" | "string" | "object" | "spacing";
interface StyleField { kind: StyleKeyKind; css?: string; unit?: string; values?: string[] }
interface StyleKey extends StyleField { fields?: Record<string, StyleField>; target?: "css" | "widget" }
interface StyleDef { keys: Record<string, StyleKey> }
interface Schema { schemaVersion: number; style?: StyleDef; widgets: Widget[] }

function tsTypeOf(p: { type: PropType; values?: string[] }): string {
  switch (p.type) {
    case "string": return "string";
    case "int": return "number";
    case "float": return "number";
    case "bool": return "boolean";
    case "stringList": return "string[]";
    case "enum": return (p.values ?? []).map((v) => JSON.stringify(v)).join(" | ");
  }
}

function tsHandlerType(e: Event): string {
  switch (e.payload ?? "none") {
    case "none": return "() => void";
    case "text": return "(e: { text: string }) => void";
    case "checked": return "(e: { checked: boolean }) => void";
    case "value": return "(e: { value: number }) => void";
    case "index": return "(e: { index: number }) => void";
  }
}

/** Union of all containers' attachedProps, deduped by name, schema order. */
function collectAttachedProps(s: Schema): AttachedProp[] {
  const seen = new Set<string>();
  const out: AttachedProp[] = [];
  for (const w of s.widgets) {
    for (const ap of w.container?.attachedProps ?? []) {
      if (!seen.has(ap.name)) { seen.add(ap.name); out.push(ap); }
    }
  }
  return out;
}

function zigLit(p: Prop): string {
  if (p.type === "int") return String(p.default ?? 0);
  if (p.type === "bool") return String(p.default ?? false);
  return JSON.stringify(String(p.default ?? "")); // string/enum default as a Zig string literal
}

// ---- style: shared StyleProp TS type + runtime valid-key manifest ----
function tsStyleField(f: StyleField): string {
  switch (f.kind) {
    case "color": return "string";
    case "string": return "string";
    case "int": return "number";
    case "enum": return (f.values ?? []).map((v) => JSON.stringify(v)).join(" | ");
    case "spacing": return "number | { top?: number; right?: number; bottom?: number; left?: number }";
    case "object": return "{ " + Object.entries(f.fields ?? {}).map(([k, v]) => `${k}?: ${tsStyleField(v)}`).join("; ") + " }";
  }
}

function genStyleProp(s: Schema): string {
  const style = s.style;
  if (!style) return "export type StyleProp = Record<string, never>;\n";
  let out = "export interface StyleProp {\n";
  for (const [k, def] of Object.entries(style.keys)) out += `  ${k}?: ${tsStyleField(def)};\n`;
  out += "}\n";
  // Runtime manifest the validator consumes (nested keys included).
  out += "export const styleKeySpec: Record<string, string[] | null> = {\n";
  for (const [k, def] of Object.entries(style.keys)) {
    const nested = def.kind === "object" ? Object.keys(def.fields ?? {}) : null;
    out += `  ${JSON.stringify(k)}: ${nested ? JSON.stringify(nested) : "null"},\n`;
  }
  out += "};\n";
  return out;
}

// ---- artifact (a): TS/JSX intrinsics ----
function genIntrinsics(s: Schema): string {
  let out = HEADER_TS;
  out += 'import type { ReactNode } from "react";\n\n';
  out += "export { jsx, jsxs, Fragment } from \"react/jsx-runtime\";\n\n";
  out += "export type WidgetName = " + s.widgets.map((w) => JSON.stringify(w.name)).join(" | ") + ";\n";
  out += "export type WidgetType = " + s.widgets.map((w) => JSON.stringify(w.intrinsic)).join(" | ") + ";\n\n";
  out += genStyleProp(s);
  out += "\n";
  out += "export namespace JSX {\n";
  out += "  export interface IntrinsicElements {\n";
  const attached = collectAttachedProps(s);
  for (const w of s.widgets) {
    const fields: string[] = [];
    for (const p of w.props) fields.push(`${p.name}?: ${tsTypeOf(p)}`);
    for (const e of w.events) fields.push(`${e.ndpName ?? e.name}?: ${tsHandlerType(e)}`);
    for (const ap of attached) fields.push(`${ap.name}?: ${tsTypeOf(ap)}`);
    fields.push("style?: StyleProp");
    fields.push("key?: string | number | null");
    fields.push("children?: ReactNode");
    out += `    ${w.intrinsic}: { ${fields.join("; ")} };\n`;
  }
  out += "  }\n";
  out += "  export type Element = ReactNode;\n";
  out += "  export interface IntrinsicAttributes {\n    key?: string | number | null;\n  }\n";
  out += "  export interface ElementChildrenAttribute {\n    children: {};\n  }\n";
  out += "}\n";
  return out;
}

// ---- artifact (d): automation role/textFrom meta ----
function genSchemaMeta(s: Schema): string {
  let out = HEADER_TS;
  out += "export interface WidgetMeta {\n  role: string;\n  textFrom: string | null;\n  childModel: \"single\" | \"multi\" | null;\n}\n\n";
  out += "export const widgetMeta: Record<string, WidgetMeta> = {\n";
  for (const w of s.widgets) {
    const cm = w.container ? JSON.stringify(w.container.childModel) : "null";
    out += `  ${JSON.stringify(w.name)}: { role: ${JSON.stringify(w.automation.role)}, textFrom: ${w.automation.textFrom === null ? "null" : JSON.stringify(w.automation.textFrom)}, childModel: ${cm} },\n`;
  }
  out += "};\n";

  out += "\nexport const intrinsicToName: Record<string, string> = {\n";
  for (const w of s.widgets) out += `  ${JSON.stringify(w.intrinsic)}: ${JSON.stringify(w.name)},\n`;
  out += "};\n";

  out += "\nexport interface WidgetEvent {\n  name: string;\n  handler: string;\n  payload: \"none\" | \"text\" | \"checked\" | \"value\" | \"index\";\n}\n";
  out += "export const widgetEvents: Record<string, WidgetEvent[]> = {\n";
  for (const w of s.widgets) {
    const evs = w.events.map((e) =>
      `{ name: ${JSON.stringify(e.name)}, handler: ${JSON.stringify(e.ndpName ?? e.name)}, payload: ${JSON.stringify(e.payload ?? "none")} }`);
    out += `  ${JSON.stringify(w.intrinsic)}: [${evs.join(", ")}],\n`;
  }
  out += "};\n";

  out += "\nexport const handlerPropNames: Record<string, string[]> = {\n";
  for (const w of s.widgets) {
    out += `  ${JSON.stringify(w.intrinsic)}: [${w.events.map((e) => JSON.stringify(e.ndpName ?? e.name)).join(", ")}],\n`;
  }
  out += "};\n";
  return out;
}

// ---- artifact (b): Zig widget appliers ----
const ZIG_HELPERS = `fn propStr(props: ?std.json.Value, key: []const u8) ?[]const u8 {
    const v = props orelse return null;
    if (v != .object) return null;
    const field = v.object.get(key) orelse return null;
    return switch (field) {
        .string => field.string,
        else => null,
    };
}

fn propInt(props: ?std.json.Value, key: []const u8) ?i64 {
    const v = props orelse return null;
    if (v != .object) return null;
    const field = v.object.get(key) orelse return null;
    return switch (field) {
        .integer => field.integer,
        else => null,
    };
}

fn propFloat(props: ?std.json.Value, key: []const u8) ?f64 {
    const v = props orelse return null;
    if (v != .object) return null;
    const field = v.object.get(key) orelse return null;
    return switch (field) {
        .float => field.float,
        .integer => @floatFromInt(field.integer),
        else => null,
    };
}

fn propBool(props: ?std.json.Value, key: []const u8) ?bool {
    const v = props orelse return null;
    if (v != .object) return null;
    const field = v.object.get(key) orelse return null;
    return switch (field) {
        .bool => field.bool,
        else => null,
    };
}

fn propArray(props: ?std.json.Value, key: []const u8) ?std.json.Array {
    const v = props orelse return null;
    if (v != .object) return null;
    const field = v.object.get(key) orelse return null;
    return switch (field) {
        .array => field.array,
        else => null,
    };
}

fn asObject(ptr: anytype) *gobject.Object {
    return @ptrCast(@alignCast(ptr));
}
`;

const ZIG_EVENT_STATE = `// ---- event wiring state (installed once by gtk_backend.setEventSink via
// initEvents, BEFORE the NDP socket accepts — so before any widget exists) ----
pub const EmitFn = *const fn (node_id: u32, name: []const u8, payload: protocol.EventPayload) void;
var emit: ?EmitFn = null;
var events_gpa: std.mem.Allocator = undefined;
var events_ready = false;
/// GObject ptr -> the ONE suppressible (change-echo) handler id on it.
var suppress_map: std.AutoHashMapUnmanaged(usize, c_ulong) = .empty;
/// Radio group name -> first CheckButton in the group (lives for process lifetime).
var radio_groups: std.StringHashMapUnmanaged(*gtk.CheckButton) = .empty;

pub fn initEvents(gpa: std.mem.Allocator, emit_fn: EmitFn) void {
    events_gpa = gpa;
    emit = emit_fn;
    events_ready = true;
}

fn noteSuppressible(obj: *gobject.Object, handler_id: c_ulong) void {
    suppress_map.put(events_gpa, @intFromPtr(obj), handler_id) catch {};
}

fn blockEcho(obj: *gobject.Object) void {
    if (suppress_map.get(@intFromPtr(obj))) |hid| gobject.signalHandlerBlock(obj, hid);
}

fn unblockEcho(obj: *gobject.Object) void {
    if (suppress_map.get(@intFromPtr(obj))) |hid| gobject.signalHandlerUnblock(obj, hid);
}
`;

function genZig(s: Schema): string {
  let out = HEADER_ZIG;
  out += "const std = @import(\"std\");\n";
  out += "const gtk = @import(\"gtk\");\n";
  out += "const gio = @import(\"gio\");\n";
  out += "const glib = @import(\"glib\");\n";
  out += "const gobject = @import(\"gobject\");\n";
  out += "const protocol = @import(\"../protocol.zig\");\n\n";
  out += ZIG_HELPERS;
  out += "\n";
  out += ZIG_EVENT_STATE;
  out += "\n";
  out += "/// The GTK create dispatcher. `dupeZ` turns a wire string into a NUL-\n";
  out += "/// terminated GTK string using the backend arena (passed by the caller).\n";
  out += "pub fn create(\n";
  out += "    app: *gtk.Application,\n";
  out += "    kind: []const u8,\n";
  out += "    props: ?std.json.Value,\n";
  out += "    dupeZ: *const fn ([]const u8) [:0]const u8,\n";
  out += "    the_window: *?*gtk.Window,\n";
  out += ") !*gtk.Widget {\n";
  for (let i = 0; i < s.widgets.length; i++) {
    const w = s.widgets[i]!;
    const kw = i === 0 ? "if" : "} else if";
    out += `    ${kw} (std.mem.eql(u8, kind, ${JSON.stringify(w.name)})) {\n`;
    out += genZigCreateBody(w);
  }
  out += "    }\n";
  out += "    std.debug.print(\"ND_WARN unknown widget kind={s}\\n\", .{kind});\n";
  out += "    return error.UnknownWidget;\n";
  out += "}\n\n";
  out += "/// The GTK update dispatcher for createAndUpdate props.\n";
  out += "pub fn applyProps(widget: *gtk.Widget, kind: []const u8, props: ?std.json.Value, dupeZ: *const fn ([]const u8) [:0]const u8) void {\n";
  let firstApply = true;
  for (const w of s.widgets) {
    const updProps = w.props.filter((p) => p.appliesTo === "createAndUpdate");
    if (updProps.length === 0) continue;
    const kw = firstApply ? "if" : "} else if";
    firstApply = false;
    out += `    ${kw} (std.mem.eql(u8, kind, ${JSON.stringify(w.name)})) {\n`;
    out += genZigApplyBody(w, updProps);
  }
  if (!firstApply) out += "    }\n";
  out += "}\n\n";
  out += genZigEvents(s);
  out += genZigStructural(s);
  out += genZigStyleTable(s);
  return out;
}

/// Data-only style-key tables `src/style.zig` walks to compile any `style`
/// object with zero per-key Zig code (D6's spirit for the style surface).
function genZigStyleTable(s: Schema): string {
  const style = s.style;
  if (!style) return "pub const style_keys = [_]StyleKeyDef{};\n";
  let out = "\npub const StyleTarget = enum { css, widget };\n";
  out += "pub const StyleKeyDef = struct { name: []const u8, css: ?[]const u8, target: StyleTarget, kind: []const u8, unit: ?[]const u8 };\n";
  out += "pub const style_keys = [_]StyleKeyDef{\n";
  for (const [k, def] of Object.entries(style.keys)) {
    const target = def.target === "widget" ? ".widget" : ".css";
    const css = def.css ? JSON.stringify(def.css) : "null";
    const unit = def.unit ? JSON.stringify(def.unit) : "null";
    out += `    .{ .name = ${JSON.stringify(k)}, .css = ${css}, .target = ${target}, .kind = ${JSON.stringify(def.kind)}, .unit = ${unit} },\n`;
  }
  out += "};\n";
  // Nested object/border/font sub-fields, flattened for the compiler.
  out += "pub const StyleSubDef = struct { parent: []const u8, name: []const u8, css: []const u8, kind: []const u8, unit: ?[]const u8 };\n";
  out += "pub const style_subkeys = [_]StyleSubDef{\n";
  for (const [k, def] of Object.entries(style.keys)) {
    if (def.kind !== "object") continue;
    for (const [sk, sf] of Object.entries(def.fields ?? {})) {
      const unit = sf.unit ? JSON.stringify(sf.unit) : "null";
      out += `    .{ .parent = ${JSON.stringify(k)}, .name = ${JSON.stringify(sk)}, .css = ${JSON.stringify(sf.css ?? sk)}, .kind = ${JSON.stringify(sf.kind)}, .unit = ${unit} },\n`;
    }
  }
  out += "};\n";
  return out;
}

function dflt(w: Widget, prop: string): string {
  const p = w.props.find((x) => x.name === prop)!;
  return String(p.default);
}
function zigDefaultStr(w: Widget, prop: string): string {
  const p = w.props.find((x) => x.name === prop)!;
  return JSON.stringify(String(p.default ?? ""));
}

function genZigCreateBody(w: Widget): string {
  let out = "";
  if (w.name === "Window") {
    out += "        const window = gtk.ApplicationWindow.new(app);\n";
    out += "        const win = window.as(gtk.Window);\n";
    out += "        the_window.* = win;\n";
    out += "        if (propStr(props, \"title\")) |t| gtk.Window.setTitle(win, dupeZ(t));\n";
    out += `        const w: c_int = @intCast(propInt(props, "defaultWidth") orelse ${dflt(w, "defaultWidth")});\n`;
    out += `        const h: c_int = @intCast(propInt(props, "defaultHeight") orelse ${dflt(w, "defaultHeight")});\n`;
    out += "        gtk.Window.setDefaultSize(win, w, h);\n";
    out += "        gtk.Window.present(win);\n";
    out += "        return window.as(gtk.Widget);\n";
  } else if (w.name === "Box") {
    out += "        const vertical = if (propStr(props, \"orientation\")) |o| std.mem.eql(u8, o, \"vertical\") else true;\n";
    out += "        const orientation: gtk.Orientation = if (vertical) .vertical else .horizontal;\n";
    out += `        const spacing: c_int = @intCast(propInt(props, "spacing") orelse ${dflt(w, "spacing")});\n`;
    out += "        const box = gtk.Box.new(orientation, spacing);\n";
    out += "        return box.as(gtk.Widget);\n";
  } else if (w.name === "Label") {
    out += `        const text = propStr(props, "text") orelse ${zigDefaultStr(w, "text")};\n`;
    out += "        const label = gtk.Label.new(dupeZ(text));\n";
    out += "        return label.as(gtk.Widget);\n";
  } else if (w.name === "Button") {
    out += `        const lbl = propStr(props, "label") orelse ${zigDefaultStr(w, "label")};\n`;
    out += "        const button = gtk.Button.newWithLabel(dupeZ(lbl));\n";
    out += "        return button.as(gtk.Widget);\n";
  } else if (w.name === "TextInput") {
    out += "        const entry = gtk.Entry.new();\n";
    out += "        const editable = entry.as(gtk.Editable);\n";
    out += "        if (propStr(props, \"text\")) |t| { if (t.len > 0) gtk.Editable.setText(editable, dupeZ(t)); }\n";
    out += "        if (propStr(props, \"placeholder\")) |p| gtk.Entry.setPlaceholderText(entry, dupeZ(p));\n";
    out += "        if (propBool(props, \"editable\")) |e| gtk.Editable.setEditable(editable, @intFromBool(e));\n";
    out += "        return entry.as(gtk.Widget);\n";
  } else if (w.name === "TextArea") {
    out += "        const view = gtk.TextView.new();\n";
    out += "        const buf = gtk.TextView.getBuffer(view);\n";
    out += "        if (propStr(props, \"text\")) |t| { if (t.len > 0) gtk.TextBuffer.setText(buf, dupeZ(t), -1); }\n";
    out += "        return view.as(gtk.Widget);\n";
  } else if (w.name === "Checkbox") {
    out += `        const cb = gtk.CheckButton.newWithLabel(dupeZ(propStr(props, "label") orelse ""));\n`;
    out += "        if (propBool(props, \"checked\") orelse false) gtk.CheckButton.setActive(cb, 1);\n";
    out += "        return cb.as(gtk.Widget);\n";
  } else if (w.name === "Radio") {
    out += `        const cb = gtk.CheckButton.newWithLabel(dupeZ(propStr(props, "label") orelse ""));\n`;
    out += "        if (propStr(props, \"group\")) |g| {\n";
    out += "            std.debug.assert(events_ready); // initEvents runs before any create (runtime.zig startup order)\n";
    out += "            if (radio_groups.get(g)) |first| {\n";
    out += "                gtk.CheckButton.setGroup(cb, first);\n";
    out += "            } else {\n";
    out += "                const key = events_gpa.dupe(u8, g) catch g;\n";
    out += "                radio_groups.put(events_gpa, key, cb) catch {};\n";
    out += "            }\n";
    out += "        } else {\n";
    out += "            std.debug.print(\"ND_WARN Radio without group prop\\n\", .{});\n";
    out += "        }\n";
    out += "        if (propBool(props, \"checked\") orelse false) gtk.CheckButton.setActive(cb, 1);\n";
    out += "        return cb.as(gtk.Widget);\n";
  } else if (w.name === "Select") {
    out += "        const sl = gtk.StringList.new(null);\n";
    out += "        if (propArray(props, \"options\")) |arr| {\n";
    out += "            for (arr.items) |item| {\n";
    out += "                if (item == .string) gtk.StringList.append(sl, dupeZ(item.string));\n";
    out += "            }\n";
    out += "        }\n";
    out += "        const dd = gtk.DropDown.new(sl.as(gio.ListModel), null); // transfer-full: DropDown owns the model\n";
    out += `        const idx = propInt(props, "selectedIndex") orelse ${dflt(w, "selectedIndex")};\n`;
    out += "        if (idx > 0) gtk.DropDown.setSelected(dd, @intCast(idx));\n";
    out += "        return dd.as(gtk.Widget);\n";
  } else if (w.name === "Slider") {
    out += `        const min = propFloat(props, "min") orelse ${dflt(w, "min")};\n`;
    out += `        const max = propFloat(props, "max") orelse ${dflt(w, "max")};\n`;
    out += `        const step = propFloat(props, "step") orelse ${dflt(w, "step")};\n`;
    out += "        const vertical = if (propStr(props, \"orientation\")) |o| std.mem.eql(u8, o, \"vertical\") else false;\n";
    out += "        const scale = gtk.Scale.newWithRange(if (vertical) .vertical else .horizontal, min, max, step);\n";
    out += `        gtk.Range.setValue(scale.as(gtk.Range), propFloat(props, "value") orelse ${dflt(w, "value")});\n`;
    out += "        return scale.as(gtk.Widget);\n";
  } else if (w.name === "ProgressBar") {
    out += "        const pb = gtk.ProgressBar.new();\n";
    out += "        if (propFloat(props, \"fraction\")) |f| gtk.ProgressBar.setFraction(pb, f);\n";
    out += "        return pb.as(gtk.Widget);\n";
  } else if (w.name === "Image") {
    out += "        const img = gtk.Image.new();\n";
    out += "        if (propStr(props, \"path\")) |p| {\n";
    out += "            gtk.Image.setFromFile(img, dupeZ(p));\n";
    out += "        } else if (propStr(props, \"iconName\")) |n| {\n";
    out += "            gtk.Image.setFromIconName(img, dupeZ(n));\n";
    out += "        }\n";
    out += "        return img.as(gtk.Widget);\n";
  } else if (w.name === "ScrollView") {
    out += "        const sw = gtk.ScrolledWindow.new();\n";
    out += "        if (propInt(props, \"minContentHeight\")) |h| { if (h > 0) gtk.ScrolledWindow.setMinContentHeight(sw, @intCast(h)); }\n";
    out += "        return sw.as(gtk.Widget);\n";
  } else if (w.name === "Separator") {
    out += "        const vertical = if (propStr(props, \"orientation\")) |o| std.mem.eql(u8, o, \"vertical\") else false;\n";
    out += "        const sep = gtk.Separator.new(if (vertical) .vertical else .horizontal);\n";
    out += "        return sep.as(gtk.Widget);\n";
  } else if (w.name === "Spinner") {
    out += "        const sp = gtk.Spinner.new();\n";
    out += "        if (propBool(props, \"spinning\") orelse true) gtk.Spinner.setSpinning(sp, 1);\n";
    out += "        return sp.as(gtk.Widget);\n";
  } else if (w.name === "TabView") {
    out += "        // selectedIndex is ignored at create: pages attach afterwards (M5b-D4).\n";
    out += "        const nb = gtk.Notebook.new();\n";
    out += "        return nb.as(gtk.Widget);\n";
  } else if (w.name === "Grid") {
    out += "        const grid = gtk.Grid.new();\n";
    out += "        return grid.as(gtk.Widget);\n";
  } else if (w.name === "WebView") {
    out += "        std.debug.print(\"ND_WARN WebView is a v1 stub (no webkitgtk); rendering placeholder label\\n\", .{});\n";
    out += "        const label = gtk.Label.new(\"WebView unavailable (v1 stub)\");\n";
    out += "        return label.as(gtk.Widget);\n";
  } else {
    throw new Error(`no create template for widget ${w.name} — add one when introducing it (M5b)`);
  }
  return out;
}

function genZigApplyBody(w: Widget, updProps: Prop[]): string {
  let out = "";
  for (const p of updProps) {
    if (w.name === "Box" && p.name === "spacing") {
      out += "        if (propInt(props, \"spacing\")) |s| {\n";
      out += "            const box: *gtk.Box = @ptrCast(@alignCast(widget));\n";
      out += "            gtk.Box.setSpacing(box, @intCast(s));\n";
      out += "        }\n";
    } else if (w.name === "Window" && p.name === "title") {
      out += "        if (propStr(props, \"title\")) |t| {\n";
      out += "            const win: *gtk.Window = @ptrCast(@alignCast(widget));\n";
      out += "            gtk.Window.setTitle(win, dupeZ(t));\n";
      out += "        }\n";
    } else if (w.name === "TextInput" && p.name === "text") {
      out += "        if (propStr(props, \"text\")) |t| {\n";
      out += "            const editable = @as(*gtk.Entry, @ptrCast(@alignCast(widget))).as(gtk.Editable);\n";
      out += "            const cur = std.mem.span(gtk.Editable.getText(editable));\n";
      out += "            if (!std.mem.eql(u8, cur, t)) {\n";
      out += "                blockEcho(asObject(widget));\n";
      out += "                gtk.Editable.setText(editable, dupeZ(t));\n";
      out += "                unblockEcho(asObject(widget));\n";
      out += "            }\n";
      out += "        }\n";
    } else if (w.name === "TextInput" && p.name === "placeholder") {
      out += "        if (propStr(props, \"placeholder\")) |p_| gtk.Entry.setPlaceholderText(@ptrCast(@alignCast(widget)), dupeZ(p_));\n";
    } else if (w.name === "TextInput" && p.name === "editable") {
      out += "        if (propBool(props, \"editable\")) |e| gtk.Editable.setEditable(@as(*gtk.Entry, @ptrCast(@alignCast(widget))).as(gtk.Editable), @intFromBool(e));\n";
    } else if (w.name === "TextArea" && p.name === "text") {
      out += "        if (propStr(props, \"text\")) |t| {\n";
      out += "            const view: *gtk.TextView = @ptrCast(@alignCast(widget));\n";
      out += "            const buf = gtk.TextView.getBuffer(view);\n";
      out += "            var s_it: gtk.TextIter = undefined;\n";
      out += "            var e_it: gtk.TextIter = undefined;\n";
      out += "            gtk.TextBuffer.getStartIter(buf, &s_it);\n";
      out += "            gtk.TextBuffer.getEndIter(buf, &e_it);\n";
      out += "            const cur = gtk.TextBuffer.getText(buf, &s_it, &e_it, 0);\n";
      out += "            defer glib.free(@ptrCast(cur));\n";
      out += "            if (!std.mem.eql(u8, std.mem.span(cur), t)) {\n";
      out += "                blockEcho(asObject(buf));\n";
      out += "                gtk.TextBuffer.setText(buf, dupeZ(t), -1);\n";
      out += "                unblockEcho(asObject(buf));\n";
      out += "            }\n";
      out += "        }\n";
    } else if ((w.name === "Checkbox" || w.name === "Radio") && p.name === "checked") {
      out += "        if (propBool(props, \"checked\")) |c| {\n";
      out += "            const cb: *gtk.CheckButton = @ptrCast(@alignCast(widget));\n";
      out += "            if ((gtk.CheckButton.getActive(cb) != 0) != c) {\n";
      out += "                blockEcho(asObject(widget));\n";
      out += "                gtk.CheckButton.setActive(cb, @intFromBool(c));\n";
      out += "                unblockEcho(asObject(widget));\n";
      out += "            }\n";
      out += "        }\n";
    } else if ((w.name === "Checkbox" || w.name === "Radio") && p.name === "label") {
      out += "        if (propStr(props, \"label\")) |l| gtk.CheckButton.setLabel(@ptrCast(@alignCast(widget)), dupeZ(l));\n";
    } else if (w.name === "Select" && p.name === "selectedIndex") {
      out += "        if (propInt(props, \"selectedIndex\")) |idx| {\n";
      out += "            const dd: *gtk.DropDown = @ptrCast(@alignCast(widget));\n";
      out += "            if (gtk.DropDown.getSelected(dd) != @as(c_uint, @intCast(idx))) {\n";
      out += "                blockEcho(asObject(widget));\n";
      out += "                gtk.DropDown.setSelected(dd, @intCast(idx));\n";
      out += "                unblockEcho(asObject(widget));\n";
      out += "            }\n";
      out += "        }\n";
    } else if (w.name === "Slider" && p.name === "value") {
      out += "        if (propFloat(props, \"value\")) |v| {\n";
      out += "            const range = @as(*gtk.Scale, @ptrCast(@alignCast(widget))).as(gtk.Range);\n";
      out += "            if (@abs(gtk.Range.getValue(range) - v) > 1e-9) {\n";
      out += "                blockEcho(asObject(widget));\n";
      out += "                gtk.Range.setValue(range, v);\n";
      out += "                unblockEcho(asObject(widget));\n";
      out += "            }\n";
      out += "        }\n";
    } else if (w.name === "ProgressBar" && p.name === "fraction") {
      out += "        if (propFloat(props, \"fraction\")) |f| gtk.ProgressBar.setFraction(@ptrCast(@alignCast(widget)), f);\n";
    } else if (w.name === "Image" && p.name === "path") {
      out += "        if (propStr(props, \"path\")) |p_| gtk.Image.setFromFile(@ptrCast(@alignCast(widget)), dupeZ(p_));\n";
    } else if (w.name === "Image" && p.name === "iconName") {
      out += "        if (propStr(props, \"iconName\")) |n| gtk.Image.setFromIconName(@ptrCast(@alignCast(widget)), dupeZ(n));\n";
    } else if (w.name === "Spinner" && p.name === "spinning") {
      out += "        if (propBool(props, \"spinning\")) |sp| gtk.Spinner.setSpinning(@ptrCast(@alignCast(widget)), @intFromBool(sp));\n";
    } else if (w.name === "TabView" && p.name === "selectedIndex") {
      out += "        if (propInt(props, \"selectedIndex\")) |idx| gtk.Notebook.setCurrentPage(@ptrCast(@alignCast(widget)), @intCast(idx));\n";
    } else {
      throw new Error(`no applyProps template for ${w.name}.${p.name} — add one when introducing it (M5b)`);
    }
  }
  return out;
}

interface SignalTemplate { signal: string; target: "widget" | "buffer"; cb: string; suppress: boolean }
const SIGNALS: Record<string, SignalTemplate> = {
  "Button.clicked":          { signal: "clicked",          target: "widget", cb: "cbClicked",          suppress: false },
  "TextInput.changed":       { signal: "changed",          target: "widget", cb: "cbEditableChanged",  suppress: true },
  "TextInput.activate":      { signal: "activate",         target: "widget", cb: "cbEntryActivate",    suppress: false },
  "TextArea.changed":        { signal: "changed",          target: "buffer", cb: "cbBufferChanged",    suppress: true },
  "Checkbox.toggled":        { signal: "toggled",          target: "widget", cb: "cbCheckToggled",     suppress: true },
  "Radio.toggled":           { signal: "toggled",          target: "widget", cb: "cbCheckToggled",     suppress: true },
  "Select.selectionChanged": { signal: "notify::selected", target: "widget", cb: "cbDropDownSelected", suppress: true },
  "Slider.valueChanged":     { signal: "value-changed",    target: "widget", cb: "cbScaleValueChanged", suppress: true },
};

const CALLBACK_BODIES: Record<string, string> = {
  cbClicked: `fn cbClicked(_: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    if (emit) |f| f(node_id, "clicked", .{});
}
`,
  cbEditableChanged: `fn cbEditableChanged(obj: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const editable: *gtk.Editable = @ptrCast(@alignCast(obj));
    const text = std.mem.span(gtk.Editable.getText(editable));
    if (emit) |f| f(node_id, "changed", .{ .text = text });
}
`,
  cbEntryActivate: `fn cbEntryActivate(obj: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const editable: *gtk.Editable = @ptrCast(@alignCast(obj));
    const text = std.mem.span(gtk.Editable.getText(editable));
    if (emit) |f| f(node_id, "activate", .{ .text = text });
}
`,
  cbBufferChanged: `fn cbBufferChanged(obj: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const buf: *gtk.TextBuffer = @ptrCast(@alignCast(obj));
    var s_it: gtk.TextIter = undefined;
    var e_it: gtk.TextIter = undefined;
    gtk.TextBuffer.getStartIter(buf, &s_it);
    gtk.TextBuffer.getEndIter(buf, &e_it);
    const ctext = gtk.TextBuffer.getText(buf, &s_it, &e_it, 0);
    defer glib.free(@ptrCast(ctext));
    if (emit) |f| f(node_id, "changed", .{ .text = std.mem.span(ctext) });
}
`,
  cbCheckToggled: `fn cbCheckToggled(obj: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const cb: *gtk.CheckButton = @ptrCast(@alignCast(obj));
    if (emit) |f| f(node_id, "toggled", .{ .checked = gtk.CheckButton.getActive(cb) != 0 });
}
`,
  cbDropDownSelected: `// notify:: handlers get (object, pspec, user_data).
fn cbDropDownSelected(obj: *gobject.Object, _: ?*anyopaque, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const dd: *gtk.DropDown = @ptrCast(@alignCast(obj));
    const sel = gtk.DropDown.getSelected(dd);
    if (sel == std.math.maxInt(c_uint)) return; // GTK_INVALID_LIST_POSITION
    if (emit) |f| f(node_id, "selectionChanged", .{ .index = @intCast(sel) });
}
`,
  cbScaleValueChanged: `fn cbScaleValueChanged(obj: *gobject.Object, data: ?*anyopaque) callconv(.c) void {
    const node_id: u32 = @intCast(@intFromPtr(data));
    const range: *gtk.Range = @ptrCast(@alignCast(obj));
    if (emit) |f| f(node_id, "valueChanged", .{ .value = gtk.Range.getValue(range) });
}
`,
};

/** Emits the signal-wiring table + callbacks. Throws on a schema event without
 *  a template (same fail-loud contract as the prop-template throws). */
function genZigEvents(s: Schema): string {
  const used = new Set<string>();
  for (const w of s.widgets) for (const e of w.events) {
    const key = `${w.name}.${e.name}`;
    const t = SIGNALS[key];
    if (!t) throw new Error(`no signal template for event ${key} — add one when introducing it`);
    used.add(t.cb);
  }

  let out = "";
  for (const cb of used) out += CALLBACK_BODIES[cb]! + "\n";

  out += "pub fn connectEvents(widget: *gtk.Widget, kind: []const u8, node_id: u32) void {\n";
  const withEvents = s.widgets.filter((w) => w.events.length > 0);
  if (withEvents.length === 0) {
    out += "    _ = widget;\n    _ = kind;\n    _ = node_id;\n";
    out += "}\n\n";
    return out;
  }
  out += "    const data: ?*anyopaque = @ptrFromInt(@as(usize, node_id));\n";
  let first = true;
  for (const w of s.widgets) {
    if (w.events.length === 0) continue;
    out += `    ${first ? "if" : "} else if"} (std.mem.eql(u8, kind, ${JSON.stringify(w.name)})) {\n`;
    first = false;
    for (const e of w.events) {
      const t = SIGNALS[`${w.name}.${e.name}`]!;
      const objExpr = t.target === "buffer"
        ? "asObject(gtk.TextView.getBuffer(@ptrCast(@alignCast(widget))))"
        : "asObject(widget)";
      const suffix = `${w.name}_${e.name}`;
      out += `        const obj_${suffix} = ${objExpr};\n`;
      out += `        const hid_${suffix} = gobject.signalConnectData(obj_${suffix}, ${JSON.stringify(t.signal)}, @ptrCast(&${t.cb}), data, null, .{});\n`;
      out += t.suppress ? `        noteSuppressible(obj_${suffix}, hid_${suffix});\n` : `        _ = hid_${suffix};\n`;
    }
  }
  if (!first) out += "    }\n";
  out += "}\n\n";
  return out;
}

interface StructuralTemplate {
  append: (childExpr: string) => string;
  insertBefore?: (childExpr: string, beforeExpr: string) => string;
  remove: (childExpr: string) => string;
}

const STRUCTURAL: Record<string, StructuralTemplate> = {
  Window: {
    append: () => "        gtk.Window.setChild(@ptrCast(@alignCast(parent)), child);\n",
    remove: () => "        gtk.Window.setChild(@ptrCast(@alignCast(parent)), null);\n",
  },
  Box: {
    append: () => "        gtk.Box.append(@ptrCast(@alignCast(parent)), child);\n",
    insertBefore: () => {
      let s = "        const box: *gtk.Box = @ptrCast(@alignCast(parent));\n";
      s += "        const prev = gtk.Widget.getPrevSibling(b);\n";
      s += "        gtk.Box.insertChildAfter(box, child, prev);\n";
      return s;
    },
    remove: () => "        gtk.Box.remove(@ptrCast(@alignCast(parent)), child);\n",
  },
  ScrollView: {
    append: () => "        gtk.ScrolledWindow.setChild(@ptrCast(@alignCast(parent)), child);\n",
    remove: () => "        gtk.ScrolledWindow.setChild(@ptrCast(@alignCast(parent)), null);\n",
  },
  TabView: {
    append: () => {
      let s = "        const nb: *gtk.Notebook = @ptrCast(@alignCast(parent));\n";
      s += "        _ = gtk.Notebook.appendPage(nb, child, null);\n";
      s += "        if (attached.tab_label) |tl| gtk.Notebook.setTabLabelText(nb, child, dupeZ(tl));\n";
      return s;
    },
    insertBefore: () => {
      let s = "        const nb: *gtk.Notebook = @ptrCast(@alignCast(parent));\n";
      s += "        const pos = gtk.Notebook.pageNum(nb, b);\n";
      s += "        _ = gtk.Notebook.insertPage(nb, child, null, pos);\n";
      s += "        if (attached.tab_label) |tl| gtk.Notebook.setTabLabelText(nb, child, dupeZ(tl));\n";
      return s;
    },
    remove: () => {
      let s = "        const nb: *gtk.Notebook = @ptrCast(@alignCast(parent));\n";
      s += "        const pos = gtk.Notebook.pageNum(nb, child);\n";
      s += "        if (pos >= 0) gtk.Notebook.removePage(nb, pos);\n";
      return s;
    },
  },
  Grid: {
    append: () => "        gtk.Grid.attach(@ptrCast(@alignCast(parent)), child, @intCast(attached.grid_column), @intCast(attached.grid_row), @intCast(attached.grid_column_span), @intCast(attached.grid_row_span));\n",
    insertBefore: () => "        // Grid children are position-addressed; sibling order is irrelevant.\n        gtk.Grid.attach(@ptrCast(@alignCast(parent)), child, @intCast(attached.grid_column), @intCast(attached.grid_row), @intCast(attached.grid_column_span), @intCast(attached.grid_row_span));\n",
    remove: () => "        gtk.Grid.remove(@ptrCast(@alignCast(parent)), child);\n",
  },
};

/** Kind-aware container ops, generated per container template. Throws if a
 *  schema widget declares `container != null` but has no structural template. */
function genZigStructural(s: Schema): string {
  const containers = s.widgets.filter((w) => w.container !== null);
  for (const w of containers) {
    if (!STRUCTURAL[w.name]) throw new Error(`no structural template for container widget ${w.name} — add one when introducing it (M5b)`);
  }

  let out = "";
  out += "pub fn appendChild(parent: *gtk.Widget, parent_kind: []const u8, child: *gtk.Widget, attached: protocol.Attached, dupeZ: *const fn ([]const u8) [:0]const u8) void {\n";
  let first = true;
  let appendBodies = "";
  for (const w of containers) {
    appendBodies += `    ${first ? "if" : "} else if"} (std.mem.eql(u8, parent_kind, ${JSON.stringify(w.name)})) {\n`;
    first = false;
    appendBodies += STRUCTURAL[w.name]!.append("child");
  }
  if (!appendBodies.includes("dupeZ(")) out += "    _ = dupeZ;\n";
  out += appendBodies;
  if (!first) out += "    } else {\n";
  else out += "    {\n";
  out += "        std.debug.print(\"ND_WARN append to non-container kind={s}\\n\", .{parent_kind});\n";
  out += "    }\n";
  out += "}\n\n";

  out += "pub fn insertBefore(parent: *gtk.Widget, parent_kind: []const u8, child: *gtk.Widget, before: ?*gtk.Widget, attached: protocol.Attached, dupeZ: *const fn ([]const u8) [:0]const u8) void {\n";
  out += "    // null `before` degenerates to append everywhere (matches the M4 hand-written contract).\n";
  out += "    const b = before orelse return appendChild(parent, parent_kind, child, attached, dupeZ);\n";
  first = true;
  const withInsert = containers.filter((w) => STRUCTURAL[w.name]!.insertBefore);
  for (const w of withInsert) {
    out += `    ${first ? "if" : "} else if"} (std.mem.eql(u8, parent_kind, ${JSON.stringify(w.name)})) {\n`;
    first = false;
    out += STRUCTURAL[w.name]!.insertBefore!("child", "b");
  }
  if (!first) out += "    } else {\n";
  else out += "    {\n";
  out += "        // single-child containers: insertBefore degenerates to appendChild.\n";
  out += "        appendChild(parent, parent_kind, child, attached, dupeZ);\n";
  out += "    }\n";
  out += "}\n\n";

  out += "pub fn removeChild(parent: *gtk.Widget, parent_kind: []const u8, child: *gtk.Widget) void {\n";
  first = true;
  for (const w of containers) {
    out += `    ${first ? "if" : "} else if"} (std.mem.eql(u8, parent_kind, ${JSON.stringify(w.name)})) {\n`;
    first = false;
    out += STRUCTURAL[w.name]!.remove("child");
  }
  if (!first) out += "    } else {\n";
  else out += "    {\n";
  out += "        std.debug.print(\"ND_WARN remove from non-container kind={s}\\n\", .{parent_kind});\n";
  out += "    }\n";
  out += "}\n";
  return out;
}

// ---- artifact (c): docs ----
function genDocs(s: Schema): string {
  let out = "<!-- GENERATED by tools/codegen.ts — do not edit -->\n\n";
  out += "# Widget reference\n\n";
  out += `Schema version: ${s.schemaVersion}. Generated from \`schema/widgets.json\`.\n\n`;
  for (const w of s.widgets) {
    out += `## ${w.name} (\`<${w.intrinsic}>\`)\n\n`;
    if (w.stub) out += `> **v1 stub** — renders a placeholder Label; see M5b-D7.\n\n`;
    out += `Automation role: \`${w.automation.role}\`. `;
    out += `Text source: ${w.automation.textFrom ? "`" + w.automation.textFrom + "`" : "none"}. `;
    out += `Children: ${w.container ? w.container.childModel : "none"}.\n\n`;
    out += "| Prop | Type | Default | Applied |\n|---|---|---|---|\n";
    for (const p of w.props) {
      const type = p.type === "enum" ? (p.values ?? []).join(" \\| ") : p.type;
      const def = p.default === undefined ? "—" : String(p.default);
      out += `| \`${p.name}\` | ${type} | ${def} | ${p.appliesTo} |\n`;
    }
    out += "\n";
    if (w.events.length) {
      out += "| Event | Handler | Payload |\n|---|---|---|\n";
      for (const e of w.events) {
        out += `| \`${e.name}\` | \`${e.ndpName ?? e.name}\` | ${e.payload ?? "none"} |\n`;
      }
      out += "\n";
    }
    if (w.container?.attachedProps?.length) {
      out += "Attached props (set on children):\n\n";
      out += "| Prop | Type | Default |\n|---|---|---|\n";
      for (const ap of w.container.attachedProps) {
        out += `| \`${ap.name}\` | ${ap.type} | ${ap.default === undefined ? "—" : String(ap.default)} |\n`;
      }
      out += "\nAttached props are attach-time-only; changing them after mount is a no-op.\n\n";
    }
    if (w.name === "Select") out += "`options` is create-only in v1.\n\n";
    if (w.name === "TabView") out += "`selectedIndex` takes effect on update; initial page is 0.\n\n";
  }
  return out;
}

// ---- artifact (e): styling reference ----
function genStyleDocs(s: Schema): string {
  let out = "<!-- GENERATED by tools/codegen.ts — do not edit -->\n\n";
  out += "# Styling\n\n";
  out += "`style` is an explicit, **non-web** prop on every widget. GTK styling is NOT web CSS: there is no `flex`, `grid`, `position`, `display`, or `justifyContent`. Layout comes from container widgets (`<box>`/`<grid>`), not from `style`. Unknown keys are rejected at the React renderer with a fix-it message and defensively rejected host-side.\n\n";
  if (s.style) {
    out += "## Valid keys\n\n| Key | Shape | Compiles to |\n|---|---|---|\n";
    for (const [k, def] of Object.entries(s.style.keys)) {
      const shape = def.kind === "object" ? "object (" + Object.keys(def.fields ?? {}).join(", ") + ")" : def.kind;
      const to = def.target === "widget" ? "widget margin properties" : "GTK CSS (`" + (def.css ?? "nested") + "`)";
      out += `| \`${k}\` | ${shape} | ${to} |\n`;
    }
    out += "\n";
  }
  out += "## Why `margin` differs from `padding`\n\nGTK widget **margins are widget properties** (`gtk_widget_set_margin_*`), not CSS — so `margin` compiles to `setMarginStart/End/Top/Bottom`. `padding` IS a GTK CSS property and stays in the generated `.nd-<id>` CSS block, alongside colors, fonts, and borders. (M5c-D2.)\n\n";
  out += "## React item-templates for ListView\n\nDeferred (M5c-D-followup): `<listview>` renders native string rows in v1. Item-template components need the synchronous bind design from spec D10.\n";
  return out;
}

async function writeIfChanged(rel: string, content: string): Promise<void> {
  const path = resolve(ROOT, rel);
  await Bun.write(path, content);
  console.log("wrote", rel, `(${content.length} bytes)`);
}

const schema = (await Bun.file(resolve(ROOT, "schema/widgets.json")).json()) as Schema;
await writeIfChanged("packages/react/src/generated/intrinsics.ts", genIntrinsics(schema));
await writeIfChanged("packages/react/src/generated/schema-meta.ts", genSchemaMeta(schema));
await writeIfChanged("src/generated/widgets.zig", genZig(schema));
await writeIfChanged("docs/widgets.md", genDocs(schema));
await writeIfChanged("docs/styling.md", genStyleDocs(schema));
console.log("codegen complete");
